// export const urunler1 = [
//   [
//     { image: "./images/", name: "B – 1" },
//     { image: "./images/", name: "B – 2" },
//     { image: "./images/", name: "B – 3" },
//     { image: "./images/", name: "B – 4" },
//     { image: "./images/", name: "B – 5" },
//     { image: "./images/", name: "B – 6" },
//     { image: "./images/", name: "B – 7" },
//     { image: "./images/", name: "B – 8" },
//     { image: "./images/", name: "B – 9" },
//     { image: "./images/", name: "B – 10" },
//     { image: "./images/", name: "B – 11" },
//     { image: "./images/", name: "B – 12" },
//     { image: "./images/", name: "B – 13" },
//     { image: "./images/", name: "Masa Referans 1001" },
//     { image: "./images/", name: "Masa Referans 1002" },
//     { image: "./images/", name: "Masa Referans 1003" },
//     { image: "./images/", name: "Masa Referans 1004" },
//     { image: "./images/", name: "Masa Referans 1005" },
//     { image: "./images/", name: "Masa Referans 1006" },
//     { image: "./images/", name: "Masa Referans 1007" },
//     { image: "./images/", name: "Masa Referans 1008" },
//     { image: "./images/", name: "Masa Referans 1009" },
//     { image: "./images/", name: "Masa Referans 1010" },
//     { image: "./images/", name: "Masa Referans 1011" },
//   ],
//   [
//     { image: "./images/", name: "Masa Referans 1012" },
//     { image: "./images/", name: "Masa Referans 1013" },
//     { image: "./images/", name: "Masa Referans 1014" },
//     { image: "./images/", name: "Masa Referans 1015" },
//     { image: "./images/", name: "Masa Referans 1016" },
//     { image: "./images/", name: "Masa Referans 1017" },
//     { image: "./images/", name: "Masa Referans 1018" },
//     { image: "./images/", name: "Masa Referans 1019" },
//     { image: "./images/", name: "Sehpa Referans 1001" },
//     { image: "./images/", name: "Sehpa Referans 1002" },
//     { image: "./images/", name: "Sehpa Referans 1003" },
//     { image: "./images/", name: "Sehpa Referans 1004" },
//     { image: "./images/", name: "Sehpa Referans 1005" },
//     { image: "./images/", name: "Sehpa Referans 1006" },
//     { image: "./images/", name: "Sehpa Referans 1007" },
//     { image: "./images/", name: "Sehpa Referans 1008" },
//     { image: "./images/", name: "Sehpa Referans 1009" },
//     { image: "./images/", name: "Sehpa Referans 1010" },
//     { image: "./images/", name: "Sehpa Referans 1011" },
//     { image: "./images/", name: "Sehpa Referans 1012" },
//     { image: "./images/", name: "Sehpa Referans 1013" },
//     { image: "./images/", name: "Sehpa Referans 1014" },
//     { image: "./images/", name: "Sehpa Referans 1015" },
//     { image: "./images/", name: "Sehpa Referans 1016" },
//     { image: "./images/", name: "Sehpa Referans 1017" },
//   ],
//   [
//     { image: "./images/", name: "Sehpa Referans 1018" },
//     { image: "./images/", name: "Sehpa Referans 1019" },
//     { image: "./images/", name: "Sehpa Referans 1020" },
//     { image: "./images/", name: "Sehpa Referans 1021" },
//     { image: "./images/", name: "Sehpa Referans 1022" },
//     { image: "./images/", name: "Sehpa Referans 1023" },
//     { image: "./images/", name: "Sehpa Referans 1024" },
//     { image: "./images/", name: "Sehpa Referans 1025" },
//     { image: "./images/", name: "Sehpa Referans 1026" },
//     { image: "./images/", name: "Sehpa Referans 1027" },
//     { image: "./images/", name: "Sehpa Referans 1028" },
//     { image: "./images/", name: "Sehpa Referans 1029" },
//     { image: "./images/", name: "Sehpa Referans 1030" },
//     { image: "./images/", name: "Sehpa Referans 1031" },
//     { image: "./images/", name: "Sehpa Referans 1032" },
//     { image: "./images/", name: "Sehpa Referans 1033" },
//     { image: "./images/", name: "Sehpa Referans 1034" },
//     { image: "./images/", name: "Sehpa Referans 1035" },
//     { image: "./images/", name: "Sehpa Referans 1036" },
//     { image: "./images/", name: "Sehpa Referans 1037" },
//     { image: "./images/", name: "Sehpa Referans 1038" },
//     { image: "./images/", name: "Sehpa Referans 1039" },
//     { image: "./images/", name: "Sehpa Referans 1040" },
//     { image: "./images/", name: "Sehpa Referans 1041" },
//   ],
//   [
//     { image: "./images/", name: "H -1" },
//     { image: "./images/", name: "H -5" },
//     { image: "./images/", name: "H -11" },
//     { image: "./images/", name: "Waterjet Madalyon 1" },
//     { image: "./images/", name: "Waterjet Madalyon 2" },
//     { image: "./images/", name: "Waterjet Madalyon 3" },
//     { image: "./images/", name: "Waterjet Madalyon 4" },
//     { image: "./images/", name: "Waterjet Madalyon 5" },
//     { image: "./images/", name: "Waterjet Madalyon 6" },
//     { image: "./images/", name: "Waterjet Madalyon 7" },
//     { image: "./images/", name: "Waterjet Madalyon 8" },
//     { image: "./images/", name: "Waterjet Madalyon 9" },
//     { image: "./images/", name: "Waterjet Madalyon 10" },
//     { image: "./images/", name: "Waterjet Madalyon 11" },
//     { image: "./images/", name: "Waterjet Madalyon 12" },
//     { image: "./images/", name: "Waterjet Madalyon 13" },
//     { image: "./images/", name: "Waterjet Madalyon 14" },
//     { image: "./images/", name: "Kenar Detayları 1001" },
//     { image: "./images/", name: "Kenar Detayları 1002" },
//     { image: "./images/", name: "Kenar Detayları 1003" },
//     { image: "./images/", name: "Kenar Detayları 1004" },
//     { image: "./images/", name: "Kenar Detayları 1005" },
//     { image: "./images/", name: "Kenar Detayları 1006" },
//     { image: "./images/", name: "Kenar Detayları 1007" },
//   ],
//   [
//     { image: "./images/", name: "Kenar Detayları 1008" },
//     { image: "./images/", name: "Kenar Detayları 1008-1" },
//     { image: "./images/", name: "Kenar Detayları 1009" },
//     { image: "./images/", name: "Kenar Detayları 1011" },
//     { image: "./images/", name: "Kenar Detayları 1012" },
//     { image: "./images/", name: "Kenar Detayları 1013" },
//     { image: "./images/", name: "Kenar Detayları 1014" },
//     { image: "./images/", name: "Kenar Detayları 1015" },
//     { image: "./images/", name: "Kenar Detayları 1016" },
//     { image: "./images/", name: "Kenar Detayları 1017" },
//     { image: "./images/", name: "Kenar Detayları 1018" },
//     { image: "./images/", name: "Kenar Detayları 1019" },
//     { image: "./images/", name: "Kenar Detayları 1020" },
//     { image: "./images/", name: "Kenar Detayları 1021" },
//     { image: "./images/", name: "Kenar Detayları 1022" },
//     { image: "./images/", name: "Kenar Detayları 1023" },
//     { image: "./images/", name: "Kenar Detayları 1024" },
//     { image: "./images/", name: "Kenar Detayları 1025" },
//     { image: "./images/", name: "Kenar Detayları 1026" },
//     { image: "./images/", name: "Kenar Detayları 1027" },
//     { image: "./images/", name: "Kenar Detayları 1028" },
//     { image: "./images/", name: "Kenar Detayları 1029" },
//     { image: "./images/", name: "Kenar Detayları 1030" },
//     { image: "./images/", name: "Kenar Detayları 1031" },
//   ],
//   [
//     { image: "./images/", name: "Kenar Detayları 1032" },
//     { image: "./images/", name: "Kenar Detayları 1033" },
//     { image: "./images/", name: "Kenar Detayları 1034" },
//     { image: "./images/", name: "Kenar Detayları 1035" },
//     { image: "./images/", name: "Kenar Detayları 1036" },
//     { image: "./images/", name: "Kenar Detayları 1037" },
//     { image: "./images/", name: "Kenar Detayları 1038" },
//     { image: "./images/", name: "Kenar Detayları 1039" },
//     { image: "./images/", name: "Kenar Detayları 1040" },
//     { image: "./images/", name: "Duş Teknesi – Referans" },
//     { image: "./images/", name: "Kolon – Referans 1001" },
//     { image: "./images/", name: "Kolon – Referans 1002" },
//     { image: "./images/", name: "Kolon – Referans 1003" },
//     { image: "./images/", name: "Kolon – Referans 1004" },
//     { image: "./images/", name: "Kolon – Referans 1005" },
//     { image: "./images/", name: "Kolon – Referans 1006" },
//     { image: "./images/", name: "Kolon – Referans 1007" },
//     { image: "./images/", name: "Kolon – Referans 1008" },
//     { image: "./images/", name: "Duvar Dekorasyonları – Referans 1001" },
//     { image: "./images/", name: "Duvar Dekorasyonları – Referans 1002" },
//     { image: "./images/", name: "Duvar Dekorasyonları – Referans 1003" },
//     { image: "./images/", name: "Duvar Dekorasyonları – Referans 1004" },
//     { image: "./images/", name: "Duvar Dekorasyonları – Referans 1005" },
//     { image: "./images/", name: "Duvar Dekorasyonları – Referans 1006" },
//   ],
//   [
//     { image: "./images/", name: "Duvar Dekorasyonları – Referans 1007" },
//     { image: "./images/", name: "Mozaik – Referans 1001" },
//     { image: "./images/", name: "Mozaik – Referans 1002" },
//     { image: "./images/", name: "Mozaik – Referans 1003" },
//     { image: "./images/", name: "Mozaik – Referans 1004" },
//     { image: "./images/", name: "Mozaik – Referans 1005" },
//     { image: "./images/", name: "Mozaik – Referans 1006" },
//     { image: "./images/", name: "Mozaik – Referans 1007" },
//     { image: "./images/", name: "Mozaik – Referans 1008" },
//     { image: "./images/", name: "Mozaik – Referans 1009" },
//     { image: "./images/", name: "Mozaik – Referans 1010" },
//     { image: "./images/", name: "Mozaik – Referans 1011" },
//     { image: "./images/", name: "Mozaik – Referans 1012" },
//     { image: "./images/", name: "Mozaik – Referans 1013" },
//     { image: "./images/", name: "Mozaik – Referans 1014" },
//     { image: "./images/", name: "Mozaik – Referans 1015" },
//     { image: "./images/", name: "Mozaik – Referans 1016" },
//     { image: "./images/", name: "Mozaik – Referans 1017" },
//     { image: "./images/", name: "Mozaik – Referans 1018" },
//     { image: "./images/", name: "Mozaik – Referans 1019" },
//     { image: "./images/", name: "Mozaik – Referans 1020" },
//     { image: "./images/", name: "Mozaik – Referans 1021" },
//     { image: "./images/", name: "Mozaik – Referans 1022" },
//     { image: "./images/", name: "Mozaik – Referans 1023" },
//   ],
//   [
//     { image: "./images/", name: "Mozaik – Referans 1024" },
//     { image: "./images/", name: "Mozaik – Referans 1025" },
//     { image: "./images/", name: "Mozaik – Referans 1026" },
//     { image: "./images/", name: "Mozaik – Referans 1027" },
//     { image: "./images/", name: "Afyon Beyaz CNC 1001" },
//     { image: "./images/", name: "Afyon Beyaz CNC 1001" },
//     { image: "./images/", name: "Afyon Beyaz CNC 1001" },
//     { image: "./images/", name: "CT-02 Afyon Beyaz Arcobaleno" },
//     { image: "./images/", name: "CT-02 Violet" },
//     { image: "./images/", name: "CT-03 Blackberry" },
//     { image: "./images/", name: "CT-04 Beyaz Traverten" },
//     { image: "./images/", name: "CT-04 Carrara" },
//     { image: "./images/", name: "CT-04-1 Carrara" },
//     { image: "./images/", name: "CT-04 Gümüş Traverten Düz Kesim" },
//     { image: "./images/", name: "CT-04 Kırmızı Traverten" },
//     { image: "./images/", name: "CT-05 Afyon Beyaz Mermer Eternal" },
//     { image: "./images/", name: "CT-05 Pearl" },
//     { image: "./images/", name: "CT-05 Silver Dragon" },
//     { image: "./images/", name: "CT-07 Olive Maron" },
//     { image: "./images/", name: "CT-08 Olive Maron" },
//     { image: "./images/", name: "CT-09 Blue Bahia" },
//     { image: "./images/", name: "CT-10 Blue Moon" },
//     { image: "./images/", name: "CT-12 Portoro" },
//     { image: "./images/", name: "CT-13 Afyon Beyaz Arcobaleno" },
//   ],
//   [
//     { image: "./images/", name: "CT-13 Amarante, Nuage Miel, Iris" },
//     { image: "./images/", name: "CT-13 Blue Bahia" },
//     { image: "./images/", name: "CT-13 Ice Jade" },
//     { image: "./images/", name: "CT-14 Nero Marquina" },
//     { image: "./images/", name: "CT-15 Afyon Beyaz Mermer Eternal" },
//     { image: "./images/", name: "CT-16 Afyon Beyaz Mermer Eternal" },
//     { image: "./images/", name: "CT-17 Silver Dragon" },
//     { image: "./images/", name: "CT-18 Dark Emperador" },
//     { image: "./images/", name: "CT-18 Silver Dragon" },
//     { image: "./images/", name: "CT-19 Carrara" },
//     { image: "./images/", name: "CT-20 İspanyol Dark Emperador" },
//     { image: "./images/", name: "CT-21 Afyon Beyaz Arcobaleno" },
//     { image: "./images/", name: "CT-22 Afyon Beyaz A La Vogue" },
//     { image: "./images/", name: "CT-23 Violet" },
//     { image: "./images/", name: "CT-24 İspanyol Dark Emperador" },
//     { image: "./images/", name: "CT-26 Afyon Beyaz Arcobaleno" },
//     {
//       image: "./images/",
//       name: "CT-26 Afyon Beyaz Arcobaleno, Blue Moon, Blue Bahia",
//     },
//     { image: "./images/", name: "CT-26 Blue Moon" },
//     { image: "./images/", name: "CT-27 Afyon Beyaz A La Vogue" },
//     { image: "./images/", name: "Dekoratif Ürünler – Duş Teknesi 1001" },
//     { image: "./images/", name: "Dekoratif Ürünler – Duş Teknesi 1002" },
//     { image: "./images/", name: "Dekoratif Ürünler – Duş Teknesi 1003" },
//     { image: "./images/", name: "Dekoratif Ürünler – Duş Teknesi 1004" },
//     { image: "./images/", name: "Dekoratif Ürünler – Duş Teknesi 1005" },
//   ],
//   [
//     { image: "./images/", name: "Dekoratif Ürünler – Kolon 1001" },
//     { image: "./images/", name: "Dekoratif Ürünler – Kolon 1002" },
//     { image: "./images/", name: "Dekoratif Ürünler – Kolon 1003" },
//     { image: "./images/", name: "Dekoratif Ürünler – Kolon 1004" },
//     { image: "./images/", name: "Dekoratif Ürünler – Kolon 1005" },
//     { image: "./images/", name: "Dekoratif Ürünler – Korkuluk 1001" },
//     { image: "./images/", name: "Dekoratif Ürünler – Korkuluk 1002" },
//     { image: "./images/", name: "Dekoratif Ürünler – Korkuluk 1003" },
//     { image: "./images/", name: "Dekoratif Ürünler – Korkuluk 1004" },
//     { image: "./images/", name: "Dekoratif Ürünler – Korkuluk 1005" },
//     { image: "./images/", name: "Kurna BS-01" },
//     { image: "./images/", name: "Kurna BS-02" },
//     { image: "./images/", name: "Kurna BS-03" },
//     { image: "./images/", name: "Kurna BS-04" },
//     { image: "./images/", name: "Kurna BS-05" },
//     { image: "./images/", name: "Kurna BS-06" },
//     { image: "./images/", name: "Kurna BS-07" },
//     { image: "./images/", name: "Kurna BS-08" },
//     { image: "./images/", name: "Kurna BS-09" },
//     { image: "./images/", name: "Kurna BS-10" },
//     { image: "./images/", name: "Dekoratif Ürünler – Söve 1001" },
//     { image: "./images/", name: "Dekoratif Ürünler – Söve 1002" },
//     { image: "./images/", name: "Dekoratif Ürünler – Söve 1003" },
//     { image: "./images/", name: "Dekoratif Ürünler – Söve 1004" },
//   ],
//   [
//     { image: "./images/", name: "Süpürgelik EFM-18" },
//     { image: "./images/", name: "Süpürgelik EFM-19" },
//     { image: "./images/", name: "Süpürgelik EFM-20" },
//     { image: "./images/", name: "Süpürgelik EFM-25" },
//     { image: "./images/", name: "Süpürgelik EFM-26" },
//     { image: "./images/", name: "Süpürgelik EFM-27" },
//     { image: "./images/", name: "Süpürgelik EFM-43" },
//     { image: "./images/", name: "Süpürgelik EFM-44" },
//     { image: "./images/", name: "Süpürgelik EFM-45" },
//     { image: "./images/", name: "Süpürgelik EFM-46" },
//     { image: "./images/", name: "Süpürgelik EFM-47" },
//     { image: "./images/", name: "Süpürgelik EFM-48" },
//     { image: "./images/", name: "Süpürgelik EFM-49" },
//     { image: "./images/", name: "Süpürgelik EFM-50" },
//     { image: "./images/", name: "Süpürgelik EFM-51" },
//     { image: "./images/", name: "Süpürgelik EFM-52" },
//     { image: "./images/", name: "Süpürgelik EFM-54" },
//     { image: "./images/", name: "Dekoratif Ürünler – Sütun 1001" },
//     { image: "./images/", name: "Dekoratif Ürünler – Sütun 1002" },
//     { image: "./images/", name: "Dekoratif Ürünler – Sütun 1003" },
//     { image: "./images/", name: "Dekoratif Ürünler – Sütun 1004" },
//     { image: "./images/", name: "Dizayn Mozaik DM01" },
//     { image: "./images/", name: "Dizayn Mozaik DM02-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM02-2" },
//   ],
//   [
//     { image: "./images/", name: "Dizayn Mozaik DM02-3" },
//     { image: "./images/", name: "Dizayn Mozaik DM03-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM03-2" },
//     { image: "./images/", name: "Dizayn Mozaik DM03-3" },
//     { image: "./images/", name: "Dizayn Mozaik DM03-4" },
//     { image: "./images/", name: "Dizayn Mozaik DM03-5" },
//     { image: "./images/", name: "Dizayn Mozaik DM03-6" },
//     { image: "./images/", name: "Dizayn Mozaik DM03/A-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM03/A-2" },
//     { image: "./images/", name: "Dizayn Mozaik DM03/B-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM03/B-2" },
//     { image: "./images/", name: "Dizayn Mozaik DM03/C-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM03/C-2" },
//     { image: "./images/", name: "Dizayn Mozaik DM04-3" },
//     { image: "./images/", name: "Dizayn Mozaik DM04-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM04-2" },
//     { image: "./images/", name: "Dizayn Mozaik DM05-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM05-2" },
//     { image: "./images/", name: "Dizayn Mozaik DM05-3" },
//     { image: "./images/", name: "Dizayn Mozaik DM06-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM06-2" },
//     { image: "./images/", name: "Dizayn Mozaik DM06-3" },
//     { image: "./images/", name: "Dizayn Mozaik DM08" },
//     { image: "./images/", name: "Dizayn Mozaik DM09" },
//   ],
//   [
//     { image: "./images/", name: "Dizayn Mozaik DM10" },
//     { image: "./images/", name: "Dizayn Mozaik DM13" },
//     { image: "./images/", name: "Dizayn Mozaik DM14" },
//     { image: "./images/", name: "Dizayn Mozaik DM15" },
//     { image: "./images/", name: "Dizayn Mozaik DM16" },
//     { image: "./images/", name: "Dizayn Mozaik DM17-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM17-2" },
//     { image: "./images/", name: "Dizayn Mozaik DM17-3" },
//     { image: "./images/", name: "Dizayn Mozaik DM18" },
//     { image: "./images/", name: "Dizayn Mozaik DM18-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM22" },
//     { image: "./images/", name: "Dizayn Mozaik DM23-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM23-2" },
//     { image: "./images/", name: "Dizayn Mozaik DM24-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM24-2" },
//     { image: "./images/", name: "Dizayn Mozaik DM25" },
//     { image: "./images/", name: "Dizayn Mozaik DM27" },
//     { image: "./images/", name: "Dizayn Mozaik DM28" },
//     { image: "./images/", name: "Dizayn Mozaik DM29-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM29-2" },
//     { image: "./images/", name: "Dizayn Mozaik DM29-3" },
//     { image: "./images/", name: "Dizayn Mozaik DM31" },
//     { image: "./images/", name: "Dizayn Mozaik DM32" },
//     { image: "./images/", name: "Dizayn Mozaik DM34" },
//   ],
//   [
//     { image: "./images/", name: "Dizayn Mozaik DM35-2" },
//     { image: "./images/", name: "Dizayn Mozaik DM35-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM39-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM39-2" },
//     { image: "./images/", name: "Dizayn Mozaik DM40" },
//     { image: "./images/", name: "Dizayn Mozaik DM41-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM41-2" },
//     { image: "./images/", name: "Dizayn Mozaik DM41-3" },
//     { image: "./images/", name: "Dizayn Mozaik DM42-1" },
//     { image: "./images/", name: "Dizayn Mozaik DM42-2" },
//     { image: "./images/", name: "Dizayn Mozaik DM42-3" },
//     { image: "./images/", name: "Dizayn Mozaik DM42-4" },
//     { image: "./images/", name: "Dizayn Mozaik DM42-5" },
//     { image: "./images/", name: "Dizayn Mozaik DM42-6" },
//     { image: "./images/", name: "Dizayn Mozaik DM42-7" },
//     { image: "./images/", name: "Dizayn Mozaik DM42-8" },
//     { image: "./images/", name: "Dizayn Mozaik DM42-9" },
//     { image: "./images/", name: "ED-01 Beyaz Traverten" },
//     { image: "./images/", name: "ED-02 Bianco Crema" },
//     { image: "./images/", name: "ED-03 Bianco Crema" },
//     { image: "./images/", name: "ED-04 Beyaz Traverten" },
//     { image: "./images/", name: "ED-06 Afyon Beyaz Mermer" },
//     { image: "./images/", name: "ED-06 Beyaz Traverten" },
//     { image: "./images/", name: "ED-07 Beyaz Traverten" },
//   ],
//   [
//     { image: "./images/", name: "ED-08 Afyon Beyaz Mermer" },
//     { image: "./images/", name: "ED-08 Pearl" },
//     { image: "./images/", name: "ED-09 Pearl" },
//     { image: "./images/", name: "Fine Line Mozaik MM18-2" },
//     { image: "./images/", name: "Fine Line Mozaik MM18-1" },
//     { image: "./images/", name: "Fine Line Mozaik MM21" },
//     { image: "./images/", name: "Fine Line Mozaik MM22-1" },
//     { image: "./images/", name: "Fine Line Mozaik MM22-2" },
//     { image: "./images/", name: "Fine Line Mozaik MM22-3" },
//     { image: "./images/", name: "Fine Line Mozaik MM22-4" },
//     { image: "./images/", name: "Fine Line Mozaik MM23-1" },
//     { image: "./images/", name: "Fine Line Mozaik MM23-2" },
//     { image: "./images/", name: "Fine Line Mozaik MM32-1" },
//     { image: "./images/", name: "Fine Line Mozaik MM32-2" },
//     { image: "./images/", name: "Fine Line Mozaik MM38-1" },
//     { image: "./images/", name: "Fine Line Mozaik MM38-2" },
//     { image: "./images/", name: "Fine Line Mozaik MM38-3" },
//     { image: "./images/", name: "Fine Line Mozaik MM38-4" },
//     { image: "./images/", name: "Fine Line Mozaik MM38-5" },
//     { image: "./images/", name: "Fine Line Mozaik MM38-6" },
//     { image: "./images/", name: "Fine Line Mozaik MM38-7" },
//     { image: "./images/", name: "Fine Line Mozaik MM38-8" },
//     { image: "./images/", name: "Fine Line Mozaik MM38-9" },
//     { image: "./images/", name: "Fine Line Mozaik MM58-1" },
//   ],
//   [
//     { image: "./images/", name: "Fine Line Mozaik MM58-2" },
//     { image: "./images/", name: "Fine Line Mozaik MM66-1" },
//     { image: "./images/", name: "Fine Line Mozaik MM66-2" },
//     { image: "./images/", name: "Fine Line Mozaik MM66-3" },
//     { image: "./images/", name: "Fine Line Mozaik MM66-4" },
//     { image: "./images/", name: "Fine Line Mozaik MM66-5" },
//     { image: "./images/", name: "Fine Line Mozaik MM66-6" },
//     { image: "./images/", name: "Fine Line Mozaik MM66-7" },
//     { image: "./images/", name: "Fine Line Mozaik MM72-1" },
//     { image: "./images/", name: "Fine Line Mozaik MM72-2" },
//     { image: "./images/", name: "Klasik Mozaik MM01" },
//     { image: "./images/", name: "Klasik Mozaik MM02" },
//     { image: "./images/", name: "Klasik Mozaik MM03" },
//     { image: "./images/", name: "Klasik Mozaik MM04" },
//     { image: "./images/", name: "Klasik Mozaik MM05-1" },
//     { image: "./images/", name: "Klasik Mozaik MM05-2" },
//     { image: "./images/", name: "Klasik Mozaik MM06-1" },
//     { image: "./images/", name: "Klasik Mozaik MM06-2" },
//     { image: "./images/", name: "Klasik Mozaik MM07-1" },
//     { image: "./images/", name: "Klasik Mozaik MM07-2" },
//     { image: "./images/", name: "Klasik Mozaik MM09" },
//     { image: "./images/", name: "Klasik Mozaik MM10-1" },
//     { image: "./images/", name: "Klasik Mozaik MM10-2" },
//     { image: "./images/", name: "Klasik Mozaik MM11-1" },
//   ],
//   [
//     { image: "./images/", name: "Klasik Mozaik MM11-2" },
//     { image: "./images/", name: "Klasik Mozaik MM11-3" },
//     { image: "./images/", name: "Klasik Mozaik MM12-1" },
//     { image: "./images/", name: "Klasik Mozaik MM12-2" },
//     { image: "./images/", name: "Klasik Mozaik MM13-1" },
//     { image: "./images/", name: "Klasik Mozaik MM13-2" },
//     { image: "./images/", name: "Klasik Mozaik MM13-3" },
//     { image: "./images/", name: "Klasik Mozaik MM16-1" },
//     { image: "./images/", name: "Klasik Mozaik MM16-1/1" },
//     { image: "./images/", name: "Klasik Mozaik MM16-2" },
//     { image: "./images/", name: "Klasik Mozaik MM16-3" },
//     { image: "./images/", name: "Klasik Mozaik MM16-4" },
//     { image: "./images/", name: "Klasik Mozaik MM16-5" },
//     { image: "./images/", name: "Klasik Mozaik MM16-6" },
//     { image: "./images/", name: "Klasik Mozaik MM16-7" },
//     { image: "./images/", name: "Klasik Mozaik MM17-1" },
//     { image: "./images/", name: "Klasik Mozaik MM17-2" },
//     { image: "./images/", name: "Klasik Mozaik MM17-3" },
//     { image: "./images/", name: "Klasik Mozaik MM17-4" },
//     { image: "./images/", name: "Klasik Mozaik MM17-5" },
//     { image: "./images/", name: "Klasik Mozaik MM17-6" },
//     { image: "./images/", name: "Klasik Mozaik MM17/A-1" },
//     { image: "./images/", name: "Klasik Mozaik MM17/A-2" },
//     { image: "./images/", name: "Klasik Mozaik MM17/A-3" },
//   ],
//   [
//     { image: "./images/", name: "Klasik Mozaik MM17/A-4" },
//     { image: "./images/", name: "Klasik Mozaik MM17/A-5" },
//     { image: "./images/", name: "Klasik Mozaik MM18-1" },
//     { image: "./images/", name: "Klasik Mozaik MM18-2" },
//     { image: "./images/", name: "Klasik Mozaik MM18-3" },
//     { image: "./images/", name: "Klasik Mozaik MM18-4" },
//     { image: "./images/", name: "Klasik Mozaik MM18-5" },
//     { image: "./images/", name: "Klasik Mozaik MM18-6" },
//     { image: "./images/", name: "Klasik Mozaik MM18-7" },
//     { image: "./images/", name: "Klasik Mozaik MM19-1" },
//     { image: "./images/", name: "Klasik Mozaik MM19-2" },
//     { image: "./images/", name: "Klasik Mozaik MM20-1" },
//     { image: "./images/", name: "Klasik Mozaik MM20-2" },
//     { image: "./images/", name: "Klasik Mozaik MM21-1" },
//     { image: "./images/", name: "Klasik Mozaik MM21-2" },
//     { image: "./images/", name: "Klasik Mozaik MM21-3" },
//     { image: "./images/", name: "Klasik Mozaik MM21-4" },
//     { image: "./images/", name: "Klasik Mozaik MM21-5" },
//     { image: "./images/", name: "Klasik Mozaik MM22-1" },
//     { image: "./images/", name: "Klasik Mozaik MM22-2" },
//     { image: "./images/", name: "Klasik Mozaik MM22-3" },
//     { image: "./images/", name: "Klasik Mozaik MM22-4" },
//     { image: "./images/", name: "Klasik Mozaik MM22-5" },
//     { image: "./images/", name: "Klasik Mozaik MM22-6" },
//   ],
//   [
//     { image: "./images/", name: "Klasik Mozaik MM22/A-1" },
//     { image: "./images/", name: "Klasik Mozaik MM22/A-2" },
//     { image: "./images/", name: "Klasik Mozaik MM23-1" },
//     { image: "./images/", name: "Klasik Mozaik MM23-2" },
//     { image: "./images/", name: "Klasik Mozaik MM24-1" },
//     { image: "./images/", name: "Klasik Mozaik MM24-2" },
//     { image: "./images/", name: "Klasik Mozaik MM25" },
//     { image: "./images/", name: "Klasik Mozaik MM30" },
//     { image: "./images/", name: "Klasik Mozaik MM31" },
//     { image: "./images/", name: "Klasik Mozaik MM31/A" },
//     { image: "./images/", name: "Klasik Mozaik MM32-1" },
//     { image: "./images/", name: "Klasik Mozaik MM32-2" },
//     { image: "./images/", name: "Klasik Mozaik MM32-3" },
//     { image: "./images/", name: "Klasik Mozaik MM32-4" },
//     { image: "./images/", name: "Klasik Mozaik MM33-1" },
//     { image: "./images/", name: "Klasik Mozaik MM33-2" },
//     { image: "./images/", name: "Klasik Mozaik MM33-3" },
//     { image: "./images/", name: "Klasik Mozaik MM33-4" },
//     { image: "./images/", name: "Klasik Mozaik MM34-1" },
//     { image: "./images/", name: "Klasik Mozaik MM34-2" },
//     { image: "./images/", name: "Klasik Mozaik MM34-3" },
//     { image: "./images/", name: "Klasik Mozaik MM38-1" },
//     { image: "./images/", name: "Klasik Mozaik MM38-2" },
//     { image: "./images/", name: "Klasik Mozaik MM38-3" },
//   ],
//   [
//     { image: "./images/", name: "Klasik Mozaik MM38-4" },
//     { image: "./images/", name: "Klasik Mozaik MM38-5" },
//     { image: "./images/", name: "Klasik Mozaik MM38-6" },
//     { image: "./images/", name: "Klasik Mozaik MM38-7" },
//     { image: "./images/", name: "Klasik Mozaik MM38-8" },
//     { image: "./images/", name: "Klasik Mozaik MM38-9" },
//     { image: "./images/", name: "Klasik Mozaik MM45-1" },
//     { image: "./images/", name: "Klasik Mozaik MM45-2" },
//     { image: "./images/", name: "Klasik Mozaik MM45-3" },
//     { image: "./images/", name: "Klasik Mozaik MM45-4" },
//     { image: "./images/", name: "Klasik Mozaik MM47-1" },
//     { image: "./images/", name: "Klasik Mozaik MM47-2" },
//     { image: "./images/", name: "Klasik Mozaik MM47-3" },
//     { image: "./images/", name: "Klasik Mozaik MM50" },
//     { image: "./images/", name: "Klasik Mozaik MM52" },
//     { image: "./images/", name: "Klasik Mozaik MM56" },
//     { image: "./images/", name: "Klasik Mozaik MM57" },
//     { image: "./images/", name: "Klasik Mozaik MM58-1" },
//     { image: "./images/", name: "Klasik Mozaik MM58-2" },
//     { image: "./images/", name: "Klasik Mozaik MM58-3" },
//     { image: "./images/", name: "Klasik Mozaik MM58-4" },
//     { image: "./images/", name: "Klasik Mozaik MM59" },
//     { image: "./images/", name: "Klasik Mozaik MM60" },
//     { image: "./images/", name: "Klasik Mozaik MM61-1" },
//   ],
//   [
//     { image: "./images/", name: "Klasik Mozaik MM61-2" },
//     { image: "./images/", name: "Klasik Mozaik MM61-3" },
//     { image: "./images/", name: "Klasik Mozaik MM62-1" },
//     { image: "./images/", name: "Klasik Mozaik MM62-2" },
//     { image: "./images/", name: "Klasik Mozaik MM64-1" },
//     { image: "./images/", name: "Klasik Mozaik MM64-2" },
//     { image: "./images/", name: "Klasik Mozaik MM65-1" },
//     { image: "./images/", name: "Klasik Mozaik MM65-2" },
//     { image: "./images/", name: "Klasik Mozaik MM65-3" },
//     { image: "./images/", name: "Klasik Mozaik MM66-1" },
//     { image: "./images/", name: "Klasik Mozaik MM66-2" },
//     { image: "./images/", name: "Klasik Mozaik MM69" },
//     { image: "./images/", name: "Klasik Mozaik MM70" },
//     { image: "./images/", name: "Klasik Mozaik MM71" },
//     { image: "./images/", name: "Dekoratif Ürünler – Şampuanlık 1001" },
//     { image: "./images/", name: "Dekoratif Ürünler – Şampuanlık 1002" },
//     { image: "./images/", name: "Dekoratif Ürünler – Şampuanlık 1003" },
//     { image: "./images/", name: "Dekoratif Ürünler – Şampuanlık 1004" },
//     { image: "./images/", name: "Dekoratif Ürünler – Şampuanlık 1005" },
//     { image: "./images/", name: "Dekoratif Ürünler – Şampuanlık 1006" },
//     { image: "./images/", name: "Dekoratif Ürünler – Şampuanlık 1007" },
//     { image: "./images/", name: "Dekoratif Ürünler – Şampuanlık 1008" },
//     { image: "./images/", name: "Dekoratif Ürünler – Aksesuar 1001" },
//     { image: "./images/", name: "Dekoratif Ürünler – Aksesuar 1002" },
//   ],
//   [
//     { image: "./images/", name: "Dekoratif Ürünler – Aksesuar 1003" },
//     { image: "./images/", name: "Dekoratif Ürünler – Aksesuar 1004" },
//     { image: "./images/", name: "Dekoratif Ürünler – Aksesuar 1005" },
//     { image: "./images/", name: "Dekoratif Ürünler – Aksesuar 1006" },
//     { image: "./images/", name: "Dekoratif Ürünler – Aksesuar 1007" },
//     { image: "./images/", name: "Dekoratif Ürünler – Aksesuar 1008" },
//     { image: "./images/", name: "Dekoratif Ürünler – Aksesuar 1009" },
//     { image: "./images/", name: "Dekoratif Ürünler – Aksesuar 1010" },
//     { image: "./images/", name: "Dekoratif Ürünler – Aksesuar 1011" },
//     { image: "./images/", name: "Dekoratif Ürünler – Bahçe Süslemesi 1001" },
//     { image: "./images/", name: "Dekoratif Ürünler – Bahçe Süslemesi 1002" },
//     { image: "./images/", name: "Dekoratif Ürünler – Bahçe Süslemesi 1003" },
//     { image: "./images/", name: "Dekoratif Ürünler – Bahçe Süslemesi 1004" },
//     { image: "./images/", name: "Dekoratif Ürünler – Bahçe Süslemesi 1005" },
//     { image: "./images/", name: "Dekoratif Ürünler – Bahçe Süslemesi 1006" },
//     { image: "./images/", name: "Dekoratif Ürünler – Bahçe Süslemesi 1007" },
//     { image: "./images/", name: "Dekoratif Ürünler – Bahçe Süslemesi 1008" },
//     { image: "./images/", name: "Dekoratif Ürünler – Bahçe Süslemesi 1009" },
//     { image: "./images/", name: "Dekoratif Ürünler – Bahçe Süslemesi 1010" },
//     { image: "./images/", name: "Dekoratif Ürünler – Aplik 1001" },
//     { image: "./images/", name: "Dekoratif Ürünler – Aplik 1002" },
//     { image: "./images/", name: "Mini Pattern Mozaik MP02" },
//     { image: "./images/", name: "Mini Pattern Mozaik MP04" },
//     { image: "./images/", name: "Mini Pattern Mozaik MP05" },
//   ],
//   [
//     { image: "./images/", name: "Mini Pattern Mozaik MP06" },
//     { image: "./images/", name: "Patlatma Mozaik SF01-1" },
//     { image: "./images/", name: "Patlatma Mozaik SF01-3" },
//     { image: "./images/", name: "Patlatma Mozaik SF02-1" },
//     { image: "./images/", name: "Patlatma Mozaik SF02-2" },
//     { image: "./images/", name: "Patlatma Mozaik SF03-1" },
//     { image: "./images/", name: "Patlatma Mozaik SF03-2" },
//     { image: "./images/", name: "Patlatma Mozaik SF03-3" },
//     { image: "./images/", name: "Patlatma Mozaik SF04-1" },
//     { image: "./images/", name: "Patlatma Mozaik SF04-2" },
//     { image: "./images/", name: "Patlatma Mozaik SF04-3" },
//     { image: "./images/", name: "Patlatma Mozaik SF04-4" },
//     { image: "./images/", name: "Patlatma Mozaik SF04-5" },
//     { image: "./images/", name: "Patlatma Mozaik SF04-6" },
//     { image: "./images/", name: "Patlatma Mozaik SF04-7" },
//     { image: "./images/", name: "Patlatma Mozaik SF04-8" },
//     { image: "./images/", name: "Patlatma Mozaik SF05" },
//     { image: "./images/", name: "Patlatma Mozaik SF06" },
//     { image: "./images/", name: "Patlatma Mozaik SF07" },
//     { image: "./images/", name: "Patlatma Mozaik SF08" },
//     { image: "./images/", name: "Patlatma Mozaik SF09" },
//     { image: "./images/", name: "Patlatma Mozaik SF10" },
//     { image: "./images/", name: "Patlatma Mozaik SF11" },
//     { image: "./images/", name: "Patlatma Mozaik SF13" },
//   ],
//   [
//     { image: "./images/", name: "Patlatma Mozaik SF14" },
//     { image: "./images/", name: "Patlatma Mozaik SF15" },
//     { image: "./images/", name: "Patlatma Mozaik SF16" },
//     { image: "./images/", name: "Patlatma Mozaik SF17" },
//     { image: "./images/", name: "Patlatma Mozaik SF18" },
//     { image: "./images/", name: "Patlatma Mozaik SF19" },
//     { image: "./images/", name: "Patlatma Mozaik SF20" },
//     { image: "./images/", name: "Patlatma Mozaik SF22" },
//     { image: "./images/", name: "Patlatma Mozaik SF23-1" },
//     { image: "./images/", name: "Patlatma Mozaik SF23-2" },
//     { image: "./images/", name: "Patlatma Mozaik SF23-3" },
//     { image: "./images/", name: "Patlatma Mozaik SF23-4" },
//     { image: "./images/", name: "Patlatma Mozaik SF24" },
//     { image: "./images/", name: "Patlatma Mozaik SF26" },
//     { image: "./images/", name: "Patlatma Mozaik SF27-1" },
//     { image: "./images/", name: "Patlatma Mozaik SF27-2" },
//     { image: "./images/", name: "Patlatma Mozaik SF27-3" },
//     { image: "./images/", name: "Patlatma Mozaik SF29" },
//     { image: "./images/", name: "Patlatma Mozaik SF31" },
//     { image: "./images/", name: "Patlatma Mozaik SF32" },
//     { image: "./images/", name: "Patlatma Mozaik SF34" },
//     { image: "./images/", name: "Patlatma Mozaik SF35" },
//     { image: "./images/", name: "Patlatma Mozaik SF36" },
//     { image: "./images/", name: "Pinguino" },
//   ],
//   [
//     { image: "./images/", name: "Portoro" },
//     { image: "./images/", name: "Bordür Mozaik BM01" },
//     { image: "./images/", name: "Bordür Mozaik BM02" },
//     { image: "./images/", name: "Bordür Mozaik BM03" },
//     { image: "./images/", name: "Bordür Mozaik BM04" },
//     { image: "./images/", name: "Bordür Mozaik BM05" },
//     { image: "./images/", name: "Bordür Mozaik BM06" },
//     { image: "./images/", name: "Bordür Mozaik BM07" },
//     { image: "./images/", name: "Bordür Mozaik BM08" },
//     { image: "./images/", name: "Bordür Mozaik BM09" },
//     { image: "./images/", name: "Bordür Mozaik BM10" },
//     { image: "./images/", name: "Bordür Mozaik BM11" },
//     { image: "./images/", name: "Bordür Mozaik BM12" },
//     { image: "./images/", name: "Bordür Mozaik BM13" },
//     { image: "./images/", name: "Bordür Mozaik BM14" },
//     { image: "./images/", name: "Bordür Mozaik BM16" },
//     { image: "./images/", name: "Bordür Mozaik BM17" },
//     { image: "./images/", name: "Bordür Mozaik BM18" },
//     { image: "./images/", name: "Bordür Mozaik BM22" },
//     { image: "./images/", name: "Bordür Mozaik BM26" },
//     { image: "./images/", name: "Bordür Mozaik BM28" },
//     { image: "./images/", name: "Bordür Mozaik BM29" },
//     { image: "./images/", name: "Bordür Mozaik BM30" },
//     { image: "./images/", name: "Bordür Mozaik BM31" },
//   ],
//   [
//     { image: "./images/", name: "Bordür Mozaik BM32" },
//     { image: "./images/", name: "Bordür Mozaik BM33" },
//     { image: "./images/", name: "Bordür Mozaik BM34" },
//     { image: "./images/", name: "Bordür Mozaik BM35" },
//     { image: "./images/", name: "Bordür Mozaik BM37" },
//     { image: "./images/", name: "Bordür Mozaik BM39" },
//     { image: "./images/", name: "Bordür Mozaik BM42" },
//     { image: "./images/", name: "Bordür Mozaik BM43" },
//     { image: "./images/", name: "Bordür Mozaik BM44" },
//     { image: "./images/", name: "Bordür Mozaik BM45" },
//     { image: "./images/", name: "Bordür Mozaik BM46" },
//     { image: "./images/", name: "Bordür Mozaik BM47" },
//     { image: "./images/", name: "Bordür Mozaik BM48" },
//     { image: "./images/", name: "Bordür Mozaik BM49" },
//     { image: "./images/", name: "Bordür Mozaik BM50" },
//     { image: "./images/", name: "Bordür Mozaik BM51" },
//     { image: "./images/", name: "Bordür Mozaik BM52" },
//     { image: "./images/", name: "Bordür Mozaik BM53" },
//     { image: "./images/", name: "Bordür Mozaik BM54" },
//     { image: "./images/", name: "Bordür Mozaik BM55" },
//     { image: "./images/", name: "Bordür Mozaik BM56" },
//     { image: "./images/", name: "Silver Dragon" },
//     { image: "./images/", name: "T-02 Afyon Beyaz Arcobaleno" },
//     { image: "./images/", name: "T-03 Afyon Beyaz Arcobaleno" },
//   ],
//   [
//     { image: "./images/", name: "T-04 Lilla" },
//     { image: "./images/", name: "T-05 Afyon Beyaz Arcobaleno" },
//     { image: "./images/", name: "T-06 Beyaz Traverten" },
//     { image: "./images/", name: "T-07 Blue Bahia" },
//     { image: "./images/", name: "T-07 Gümüş Traverten Düz Kesim" },
//     { image: "./images/", name: "T-08 Gümüş Traverten Düz Kesim" },
//     { image: "./images/", name: "T-09 Metell" },
//     { image: "./images/", name: "T-11 Afyon Beyaz Arcobaleno" },
//     { image: "./images/", name: "T-12 Afyon Beyaz Arcobaleno" },
//     { image: "./images/", name: "T-13 Nero Marquina" },
//     { image: "./images/", name: "T-14 Gümüş Traverten Düz Kesim" },
//     { image: "./images/", name: "T-15 Carrara" },
//     { image: "./images/", name: "K-01 Dark Emperador" },
//     { image: "./images/", name: "K-03 Lilla" },
//     { image: "./images/", name: "K-05 Pearl" },
//     { image: "./images/", name: "K-07 Pinguino" },
//     { image: "./images/", name: "K-09 Warm Walnut" },
//     { image: "./images/", name: "K-10 Lilla" },
//     { image: "./images/", name: "Tabure1 – Beyaz Traverten" },
//     { image: "./images/", name: "Tabure2 – Beyaz Traverten" },
//     { image: "./images/", name: "Waterjet Bordür WJB-05" },
//     { image: "./images/", name: "Waterjet Bordür WJB-06" },
//     { image: "./images/", name: "Waterjet Bordür WJB-07" },
//     { image: "./images/", name: "Waterjet Karo WJK-01" },
//   ],
//   [
//     { image: "./images/", name: "Waterjet Karo WJK-02" },
//     { image: "./images/", name: "Waterjet Karo WJK-03" },
//     { image: "./images/", name: "Waterjet Karo WJK-04" },
//     { image: "./images/", name: "Waterjet Karo WJK-05" },
//     { image: "./images/", name: "Waterjet Karo WJK-06" },
//     { image: "./images/", name: "Waterjet Karo WJK-07" },
//     { image: "./images/", name: "Waterjet Karo WJK-08" },
//     { image: "./images/", name: "Waterjet Karo WJK-09" },
//     { image: "./images/", name: "Waterjet Karo WJK-10" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-01" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-02" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-03" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-04" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-05" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-07" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-08" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-09" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-10" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-11" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-12" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-13" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-14-1" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-14-2" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-15-1" },
//   ],
//   [
//     { image: "./images/", name: "Waterjet Madalyon WJM-15-2" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-16" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-17" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-18" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-19-1" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-19-2" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-19-3" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-20" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-21" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-22" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-24" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-25" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-26" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-27" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-28" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-29" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-30-1" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-30-2" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-30-3" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-31" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-32" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-33" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-34-1" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-34-2" },
//   ],
//   [
//     { image: "./images/", name: "Waterjet Madalyon WJM-35" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-36-1" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-36-2" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-37" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-38" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-39" },
//     { image: "./images/", name: "Waterjet Madalyon WJM-40" },
//     { image: "./images/", name: "Waterjet Mozaik WJC-01" },
//     { image: "./images/", name: "Waterjet Mozaik WJC-02-1" },
//     { image: "./images/", name: "Waterjet Mozaik WJC-02-2" },
//     { image: "./images/", name: "Waterjet Mozaik WJC-03" },
//   ],
// ];
