// export const ozelKoleksiyon = [
//   [
//     {
//       image: "./images/koleksiyon/page-1/panda-emerald-marble.jpg",
//       name: "Panda Emerald Marble 101",
//     },
//     {
//       image: "./images/koleksiyon/page-1/RAIN-FOREST-BROWN-3.avif",
//       name: "Rain Forest Brown 103",
//     },
//     {
//       image: "./images/koleksiyon/page-1/RAIN-FOREST-GREEN1-300x300.avif",
//       name: "Rain Forest Green 101",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Panda-Azul-300x300.avif",
//       name: "Panda Azul 101",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Panda-Azul-2-300x300.avif",
//       name: "Panda Azul 102",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Agate-Blue-1-1-300x300.avif",
//       name: "Agate Blue 1",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Agate-Blue-2-300x300.avif",
//       name: "Agate Blue 2",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Agate-Green-1-300x300.avif",
//       name: "Agate Green 1",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Agate-Green-2-300x300.avif",
//       name: "Agate Green 2",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Agate-Purple-300x300.avif",
//       name: "Agate Purple 1",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Grey-Agate-300x300.avif",
//       name: "Grey Agate 1",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Petrified-Wood-300x300.avif",
//       name: "Petrified Wood 1",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Agate-White-300x300.avif",
//       name: "Agate White 1",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Round-Agathe-1-300x300.avif",
//       name: "Round Agathe 1",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Round-Agathe-2-300x300.avif",
//       name: "Round Agathe 2",
//     },
//     {
//       image: "./images/koleksiyon/page-1/AGATE-ATHENA-GOLD-1-300x300.avif",
//       name: "Agate Athena Gold",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Rosa-Quartz-300x300.avif",
//       name: "Rosa Quartz 1",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Yellow-Tiger-Agate-300x300.avif",
//       name: "Yellow Tiger Agate 1",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Agate-Black-Dim-Gold-1-300x300.avif",
//       name: "Agate Black Dim Gold",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Agate-Cezanne-Gold-1-300x300.avif",
//       name: "Agate Cezanne Gold",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Agate-Phoenix-1-300x300.avif",
//       name: "Agate Phoenix",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Amazonite-1-300x300.avif",
//       name: "Amazonite",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Fluorite-1-300x300.avif",
//       name: "Fluorite",
//     },
//     {
//       image: "./images/koleksiyon/page-1/Green-Agate-1-300x300.avif",
//       name: "Green Agate",
//     },
//   ],
//   [
//     {
//       image: "./images/koleksiyon/page-2/turtle-1-300x300.avif",
//       name: "Turtle 101",
//     },
//     {
//       image: "./images/koleksiyon/page-2/Emerald1-1-300x300.avif",
//       name: "Turtle 102",
//     },
//     {
//       image: "./images/koleksiyon/page-2/Emerald2-1-300x300.avif",
//       name: "Emerald 101",
//     },
//     {
//       image: "./images/koleksiyon/page-2/Emerald3-1-300x300.avif",
//       name: "Emerald 102",
//     },
//     {
//       image: "./images/koleksiyon/page-2/Emerald4-1-300x300.avif",
//       name: "Emerald 103",
//     },
//     {
//       image: "./images/koleksiyon/page-2/Hills-300x300.avif",
//       name: "Emerald 104",
//     },
//     {
//       image: "./images/koleksiyon/page-2/WHITE-ONYX-2-300x300.avif",
//       name: "Hills 101",
//     },
//     {
//       image: "./images/koleksiyon/page-2/RAIN-FOREST-BROWN-2-300x300.avif",
//       name: "Beyaz Oniks 102",
//     },
//     {
//       image: "./images/koleksiyon/page-2/Turtle-300x300.avif",
//       name: "Rain Forest Brown 102",
//     },
//     {
//       image: "./images/koleksiyon/page-2/VERDE-FOREST-300x300.avif",
//       name: "Verde Forest 101",
//     },
//     {
//       image: "./images/koleksiyon/page-2/BLACK-AZIZA-300x300.avif",
//       name: "Black Aziza 101",
//     },
//     {
//       image: "./images/koleksiyon/page-2/ICE-JADE-300x300.avif",
//       name: "Ice Jade 101",
//     },
//     {
//       image: "./images/koleksiyon/page-2/DESERT-WAVE-300x300.avif",
//       name: "Desert Wave 101",
//     },
//   ],
// ];

// export const dogalTaslar = [
//     [
//       {
//         image: "./images/dogal/Oniks/Blue-Ice-Onyx-1-300x300.avif",
//         name: "Blue Ice Onyx 101",
//       },
//       {
//         image: "./images/dogal/Oniks/greenIceOnyx.avif",
//         name: "Green Ice Onyx 101",
//       },
//       {
//         image: "./images/dogal/Oniks/pinkIceOnyx.avif",
//         name: "Pink Ice Onyx 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/DESERT-WAVE-2-300x300.avif",
//         name: "Desert Wave 102",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-1/panda-emerald-marble-300x300.avif",
//         name: "Panda Emerald Marble 101",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-1/RAIN-FOREST-BROWN-3-300x300.avif",
//         name: "Rain Forest Brown 103",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-1/RAIN-FOREST-GREEN1-300x300.avif",
//         name: "Rain Forest Green 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/Panda-Azul-300x300.avif",
//         name: "Panda Azul 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/Panda-Azul-2-300x300.avif",
//         name: "Panda Azul 102",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/Black-Leopar2-300x300.avif",
//         name: "Magma Gold 102",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/ICE-JADE-5-300x300.avif",
//         name: "Ice Jade 106",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-1/Petrified-Wood-Marble-1-300x300.avif",
//         name: "Petrified Wood Marble 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/DARK-EMPERADOR2-300x300.avif",
//         name: "Dark Emperador 102",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/Agate-Blue-1-1-300x300.avif",
//         name: "Agate Blue 1",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/Agate-Blue-2-300x300.avif",
//         name: "Agate Blue 2",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/Agate-Green-1-300x300.avif",
//         name: "Agate Green 1",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/Agate-Green-2-300x300.avif",
//         name: "Agate Green 2",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/Agate-Purple-300x300.avif",
//         name: "Agate Purple 1",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/Grey-Agate-300x300.avif",
//         name: "Grey Agate 1",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/Petrified-Wood-300x300.avif",
//         name: "Petrified Wood 1",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/Agate-White-300x300.avif",
//         name: "Agate White 1",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/Round-Agathe-1-300x300.avif",
//         name: "Round Agathe 1",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/Round-Agathe-2-300x300.avif",
//         name: "Round Agathe 2",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/Azul-Macaubas-300x300.avif",
//         name: "Azul Macaubas 101",
//       },
//     ],
//     [
//       {
//         image: "./images/dogal/Mermer/MermerPage-1/Azul-Macaubas2-300x300.avif",
//         name: "Azul Macaubas 102",
//       },
//       {
//         image: "./images/dogal/Granit/Black-Leopar-300x300.avif",
//         name: "Black Leopar 101",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-1/Serpegiante-light-300x300.avif",
//         name: "Serpegiante Light 101",
//       },
//       { image: "./images/dogal/Oniks/tigerOnyx-1.avif", name: "Tiger Oniks 101" },
//       { image: "./images/dogal/Oniks/tigerOnyx-2.avif", name: "Tiger Oniks 102" },
//       { image: "./images/dogal/Oniks/woodenOnyx.avif", name: "Wooden Onyx 101" },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-1/AFYON-WHITE-SPIDER-300x300.avif",
//         name: "Afyon Beyaz Mermer Spider 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-2/PANDA-WHITE-5-300x300.avif",
//         name: "Panda White 105",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-2/PANDA-WHITE-6-300x300.avif",
//         name: "Panda White 106",
//       },
//       {
//         image: "./images/dogal/BejMermer/BejMermerPage-1/BEACH-300x300.avif",
//         name: "Beach 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-2/Cafe-Chino-300x300.avif",
//         name: "Picasso 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-2/Nero-Gold-300x300.avif",
//         name: "Nero Gold 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-2/Armani-300x300.avif",
//         name: "Armani",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-2/Chateaux-300x300.avif",
//         name: "Chateaux",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-2/Pinguino-Classic-1-300x300.avif",
//         name: "Pinguino Klasik",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-2/Bardiglio-Black-1-300x300.avif",
//         name: "Bardiglio Black 101",
//       },
//       {
//         image: "./images/dogal/BejMermer/BejMermerPage-1/Botticino-300x300.avif",
//         name: "Botticino 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-2/PINGUINO2-300x300.avif",
//         name: "Pinguino 102",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-2/AGATE-ATHENA-GOLD-1-300x300.avif",
//         name: "Agate Athena Gold",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-2/Rosa-Quartz-300x300.avif",
//         name: "Rosa Quartz 1",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-2/Yellow-Tiger-Agate-300x300.avif",
//         name: "Yellow Tiger Agate 1",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-2/Agate-Black-Dim-Gold-1-300x300.avif",
//         name: "Agate Black Dim Gold",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-2/Agate-Cezanne-Gold-1-300x300.avif",
//         name: "Agate Cezanne Gold",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-2/Agate-Phoenix-1-300x300.avif",
//         name: "Agate Phoenix",
//       },
//     ],
//     [
//       {
//         image: "./images/dogal/koleksiyon/page-1/Amazonite-1-300x300.avif",
//         name: "Amazonite",
//       },
//       {
//         image: "./images/dogal/koleksiyon/page-1/Fluorite-1-300x300.avif",
//         name: "Fluorite",
//       },
//       {
//         image: "./images/dogal/koleksiyon/page-1/Green-Agate-1-300x300.avif",
//         name: "Green Agate",
//       },
//       {
//         image: "./images/dogal/koleksiyon/page-2/turtle-1-300x300.avif",
//         name: "Turtle 102",
//       },
//       {
//         image: "./images/dogal/koleksiyon/page-2/Emerald1-1-300x300.avif",
//         name: "Emerald 101",
//       },
//       {
//         image: "./images/dogal/koleksiyon/page-2/Emerald2-1-300x300.avif",
//         name: "Emerald 102",
//       },
//       {
//         image: "./images/dogal/koleksiyon/page-2/Emerald3-1-300x300.avif",
//         name: "Emerald 103",
//       },
//       {
//         image: "./images/dogal/koleksiyon/page-2/Emerald4-1-300x300.avif",
//         name: "Emerald 104",
//       },
//       {
//         image: "./images/dogal/koleksiyon/page-2/Hills-300x300.avif",
//         name: "Hills 101",
//       },
//       {
//         image: "./images/dogal/Oniks/WHITE-ONYX-2-300x300.avif",
//         name: "Beyaz Oniks 102",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-3/PANDA-WHITE2-300x300.avif",
//         name: "Panda White 104",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-3/Serpegiante-300x300.avif",
//         name: "Serpegiante 101",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-3/Marmara-White-Marble-300x300.avif",
//         name: "Marmara Beyaz Mermer 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-3/Zebra-White-1-300x300.avif",
//         name: "Zebra White 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-3/Blue-Rain-300x300.avif",
//         name: "Blue Rain 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-3/Fusion-300x300.avif",
//         name: "Fusion 101",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-3/RAIN-FOREST-BROWN-2-300x300.avif",
//         name: "Rain Forest Brown 102",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-3/Statuario-300x300.avif",
//         name: "Statuario 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-3/Nero1-300x300.avif",
//         name: "Nero 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-3/Bruno-perla-1-300x300.avif",
//         name: "Bruno Perla 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-3/Zebra-White-300x300.avif",
//         name: "Zebra Black 102",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-3/Bruno-300x300.avif",
//         name: "Bruno 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-3/ICE-JADE-1-300x300.avif",
//         name: "Ice Jade 102",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-3/PANDA-WHITE-2-300x300.avif",
//         name: "Panda White 102",
//       },
//     ],
//     [
//       {
//         image: "./images/dogal/Mermer/MermerPage-3/Turtle-300x300.avif",
//         name: "Turtle 101",
//       },
//       {
//         image: "./images/dogal/Oniks/AFYON-WHITE-MARBLE-ONYX-1-300x300.avif",
//         name: "Afyon Beyaz Oniks 101",
//       },
//       {
//         image: "./images/dogal/Oniks/AFYON-WHITE-MARBLE-ONYX-2-300x300.avif",
//         name: "Afyon Beyaz Oniks 102",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-3/AFYON-WHITE-BILLUR-GOLD-1-300x300.avif",
//         name: "Afyon Beyaz Mermer Billur Gold 101",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-3/AFYON-WHITE-BILLUR-GOLD-2-300x300.avif",
//         name: "Afyon Beyaz Mermer Billur Gold 102",
//       },
//       {
//         image: "./images/dogal/Granit/Pedras-Granite-300x300.avif",
//         name: "Pedras Granit – Cilalı 101",
//       },
//       {
//         image: "./images/dogal/Granit/pedras1-300x300.avif",
//         name: "Pedras Granit – Kumlama 102",
//       },
//       {
//         image: "./images/dogal/Traverten/antiquepewter-honed-300x300.avif",
//         name: "Antique Pewter – Honlu 101",
//       },
//       {
//         image: "./images/dogal/Traverten/antiquepewter-tumbled-300x300.avif",
//         name: "Antique Pewter – Eskitme 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-3/calacattaoro-1-300x300.avif",
//         name: "Calacatta Oro 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-3/zebragrey-1-300x300.avif",
//         name: "Zebra Grey 101",
//       },
//       {
//         image: "./images/dogal/Oniks/honeyonyx1-1-300x300.avif",
//         name: "Bal Oniks 101",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-3/White-Beauty-Premium-300x300.avif",
//         name: "White Beauty Premium",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-3/Carrara-Arabescato-1-300x300.avif",
//         name: "Carrara Arabescato 101",
//       },
//       {
//         image: "./images/dogal/Oniks/Bubble-Onyx1-300x300.avif",
//         name: "Bubble Oniks 101",
//       },
//       {
//         image: "./images/dogal/Oniks/Cappuccino-Onyx2-300x300.avif",
//         name: "Cappuccino Oniks 101",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanBlueBahia101.avif",
//         name: "Dış Mekan – Blue Bahia 101",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanWhiteWalker101.avif",
//         name: "Dış Mekan – White Walker 101",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanWhiteWalker102.avif",
//         name: "Dış Mekan – White Walker 102",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans101.avif",
//         name: "Dış Mekan – Referans 101",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans102.avif",
//         name: "Dış Mekan – Referans 102",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans103.avif",
//         name: "Dış Mekan – Referans 103",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans104.avif",
//         name: "Dış Mekan – Referans 104",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans105.avif",
//         name: "Dış Mekan – Referans 105",
//       },
//     ],
//     [
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans106.avif",
//         name: "Dış Mekan – Referans 106",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans107.avif",
//         name: "Dış Mekan – Referans 107",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans108.avif",
//         name: "Dış Mekan – Referans 108",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans109.avif",
//         name: "Dış Mekan – Referans 109",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans110.avif",
//         name: "Dış Mekan – Referans 110",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans111.avif",
//         name: "Dış Mekan – Referans 111",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans112.avif",
//         name: "Dış Mekan – Referans 112",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans113.avif",
//         name: "Dış Mekan – Referans 113",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans114.avif",
//         name: "Dış Mekan – Referans 114",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans115.avif",
//         name: "Dış Mekan – Referans 115",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans116.avif",
//         name: "Dış Mekan – Referans 116",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans117.avif",
//         name: "Dış Mekan – Referans 117",
//       },
//       {
//         image: "./images/dogal/DisMekan/DisMekanReferans118.avif",
//         name: "Dış Mekan – Referans 118",
//       },
//       {
//         image: "./images/dogal/Oniks/Velluto-Onyx2-300x300.avif",
//         name: "Velluto Oniks 101",
//       },
//       {
//         image: "./images/dogal/Oniks/SILVER-ONYX-2-300x300.avif",
//         name: "Gümüş Oniks 101",
//       },
//       {
//         image: "./images/dogal/Oniks/SILVER-ONYX-4-300x300.avif",
//         name: "Gümüş Oniks 102",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-4/AFYON-WHITE-ARCOBALENO-1-300x300.avif",
//         name: "Afyon Beyaz Mermer Arcobaleno 101",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-4/AFYON-WHITE-GOLDEN-GRAY-300x300.avif",
//         name: "Afyon Beyaz Mermer Golden Gray 101",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-4/afyon_beyaz_a_la_vogue-1-300x300.avif",
//         name: "Afyon Beyaz Mermer A La Vogue 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/",
//         name: "Afyon Beyaz Mermer Billur 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/",
//         name: "Afyon Beyaz Mermer Billur 102",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/",
//         name: "Afyon Beyaz Mermer Billur 103",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/SPERENZA-300x300.avif",
//         name: "Sperenza 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/AMARANTE-1-300x300.avif",
//         name: "Calacatta 101",
//       },
//     ],
//     [
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/AMARANTE-2-300x300.avif",
//         name: "Calacatta 102",
//       },
//       { image: "./images/dogal/Oniks/goldOnyx.avif", name: "Gold Oniks 101" },
//       {
//         image: "./images/dogal/Oniks/cocacolaonyx1-300x300.avif",
//         name: "Cocacola Oniks 101",
//       },
//       {
//         image: "./images/dogal/Limestone/COQUILLAGE-300x300.avif",
//         name: "Coquillage 101",
//       },
//       {
//         image: "./images/dogal/Limestone/BIANCO-CREMA-300x300.avif",
//         name: "Bianco Crema 101",
//       },
//       {
//         image:
//           "./images/dogal/Limestone/bianco-crema-bombe-4-scaled-1-300x300.avif",
//         name: "Bianco Crema 102",
//       },
//       {
//         image:
//           "./images/dogal/Limestonebianco-crema-bombe-3-scaled103-300x300.avif/",
//         name: "Bianco Crema 103",
//       },
//       {
//         image: "./images/dogal/Limestone/GOLDEN-CREMA-300x300.avif",
//         name: "Golden Crema 101",
//       },
//       { image: "./images/dogal/Limestone/SUNNY-300x300.avif", name: "Sunny 101" },
//       {
//         image: "./images/dogal/Limestone/SUNNY-LIGHT-300x300.avif",
//         name: "Sunny Light 101",
//       },
//       {
//         image: "./images/dogal/Limestone/mocca-cilali-1-300x300.avif",
//         name: "Mocca – Cilalı 101",
//       },
//       {
//         image: "./images/dogal/Bazalt/GARGAMEL-300x300.avif",
//         name: "Gargamel 101",
//       },
//       {
//         image: "./images/dogal/Bazalt/CALIMERO-300x300.avif",
//         name: "Calimero 101",
//       },
//       {
//         image: "./images/dogal/Bazalt/Kup-Tas-Siyah-Bazalt1-300x300.avif",
//         name: "Calimero – Küp Taşlar 101",
//       },
//       {
//         image: "./images/dogal/Bazalt/Kup-Tas-Siyah-Bazalt2-300x300.avif",
//         name: "Calimero – Küp Taşlar 102",
//       },
//       {
//         image: "./images/dogal/Bazalt/Kup-Tas-Siyah-Bazalt3-300x300.avif",
//         name: "Calimero – Küp Taşlar 103",
//       },
//       {
//         image:
//           "./images/dogal/Traverten/SILVER-TRAVERTINE-VEIN-CUT-1-300x300.avif",
//         name: "Gümüş Traverten 101",
//       },
//       {
//         image: "./images/dogal/Traverten/SILVER-TRAVERTINE-1-300x300.avif",
//         name: "Gümüş Traverten 102",
//       },
//       {
//         image: "./images/dogal/Traverten/SILVER-TRAVERTINE-2-300x300.avif",
//         name: "Gümüş Traverten 103",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-4/VERDE-GUATEMALA-1-300x300.avif",
//         name: "Verde Guatemala 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/VERDE-FOREST-300x300.avif",
//         name: "Verde Forest 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/ELAZIG-VISNE-300x300.avif",
//         name: "Elazığ Vişne 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/VOLAKAS-BIANCO-300x300.avif",
//         name: "Volakas Bianco 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/LILLA-2-300x300.avif",
//         name: "Lilla 102",
//       },
//     ],
//     [
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/Rosalia1-2-300x300.avif",
//         name: "Rosalia 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/rosaliaLight.avif",
//         name: "Rosalia Light 101",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-4/LIGHT-EMPERADOR-CLASSIC-300x300.avif",
//         name: "Light Emperador Klasik Mermer",
//       },
//       {
//         image: "./images/dogal/Granit/pedras3-300x300.avif",
//         name: "Pedras Granit – Kumlama 103",
//       },
//       {
//         image: "./images/dogal/Granit/White-Walker-300x300.avif",
//         name: "White Walker 101",
//       },
//       {
//         image:
//           "./images/dogal/Granit/White-Walker-kuptaslar-referans-kapak.png-300x300.avif",
//         name: "White Walker – Küp Taşlar 101",
//       },
//       {
//         image: "./images/dogal/Granit/Kup-Tas-White-Walker1-300x300.avif",
//         name: "White Walker – Küp Taşlar 102",
//       },
//       {
//         image: "./images/dogal/Granit/Kup-Tas-White-Walker2-300x300.avif",
//         name: "White Walker – Küp Taşlar 103",
//       },
//       {
//         image: "./images/dogal/Granit/DESERT-BLACK-300x300.avif",
//         name: "Desert Black 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/NERO-MARQUINA-300x300.avif",
//         name: "Nero Marquina 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/NEBEL-300x300.avif",
//         name: "Nebel 101",
//       },
//       {
//         image: "./images/dogal/Granit/ABSOLUTE-BLACK-300x300.avif",
//         name: "Absolute Black 101",
//       },
//       {
//         image: "./images/dogal/Granit/STAR-GALAXY-300x300.avif",
//         name: "Star Galaxy 101",
//       },
//       {
//         image: "./images/dogal/Granit/PARADISO1-300x300.avif",
//         name: "Paradiso 101",
//       },
//       {
//         image: "./images/dogal/Granit/P-WHITE-300x300.avif",
//         name: "P White 101",
//       },
//       {
//         image: "./images/dogal/Limestone/mocca-honlu1-300x300.avif",
//         name: "Mocca – Honlu 101",
//       },
//       {
//         image: "./images/dogal/Limestone/mocca-eskitme-1-300x300.avif",
//         name: "Mocca – Eskitme 101",
//       },
//       {
//         image: "./images/dogal/Limestone/mocca-fircali-1-300x300.avif",
//         name: "Mocca – Fırçalı 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/AFYON-SUGAR-300x300.jpg",
//         name: "Afyon Beyaz Mermer Şeker 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/AMARANTE-BLU-300x300.avif",
//         name: "Calacatta 103",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/AMARANTE-BLU2-300x300.avif",
//         name: "Calacatta 104",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/BLUEMOON-3-300x300.avif",
//         name: "Blue Moon 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/BLUE-MOON-2-300x300.avif",
//         name: "Blue Moon 102",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-4/BLUE-MOON-1-2-300x300.avif",
//         name: "Blue Moon 103",
//       },
//     ],
//     [
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/NUAGE-MIEL-300x300.avif",
//         name: "Nuage Miel 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/NUAGE-DORE-300x300.avif",
//         name: "Nuage Doré 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/BLUE-BAHIA-1-300x300.avif",
//         name: "Blue Bahia 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/BLUE-BAHIA2-300x300.avif",
//         name: "Blue Bahia 102",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/MARINE-BLUE-1-300x300.avif",
//         name: "Afyon Beyaz Marine Blue 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/MARINE-BLUE-2-300x300.avif",
//         name: "Afyon Beyaz Marine Blue 106",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/bluestone-300x300.avif",
//         name: "Blue Stone 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/bluemoongold-1-300x300.avif",
//         name: "Blue Moon Gold 101",
//       },
//       {
//         image:
//           "./images/dogal/BejMermer/BejMermerPage-1/CREMA-BELLA-300x300.avif",
//         name: "Crema Bella 101",
//       },
//       {
//         image:
//           "./images/dogal/BejMermer/BejMermerPage-1/Crema-Foret-300x300.avif",
//         name: "Crema Foret 101",
//       },
//       {
//         image: "./images/dogal/BejMermer/BejMermerPage-1/LUNA-300x300.avif",
//         name: "Luna 101",
//       },
//       {
//         image: "./images/dogal/BejMermer/BejMermerPage-1/BOTANICA-300x300.avif",
//         name: "Botanica 101",
//       },
//       {
//         image: "./images/dogal/BejMermer/BejMermerPage-1/LIMPIDO-300x300.avif",
//         name: "Limpido 101",
//       },
//       {
//         image: "./images/dogal/BejMermer/BejMermerPage-1/LUNA-PIERA-300x300.avif",
//         name: "Luna Piera 101",
//       },
//       {
//         image:
//           "./images/dogal/BejMermer/BejMermerPage-1/DARK-EMPERADOR-300x300.avif",
//         name: "Dark Emperador 101",
//       },
//       {
//         image:
//           "./images/dogal/BejMermer/BejMermerPage-1/DARK-EMPERADOR-CLASSIC-300x300.avif",
//         name: "Dark Emperador Klasik 101",
//       },
//       {
//         image:
//           "./images/dogal/BejMermer/BejMermerPage-1/Bruno-perla-2-300x300.avif",
//         name: "Bruno Perla 102",
//       },
//       {
//         image:
//           "./images/dogal/BejMermer/BejMermerPage-1/emperador-perla-300x300.avif",
//         name: "Emperador Perla 101",
//       },
//       {
//         image:
//           "./images/dogal/BejMermer/BejMermerPage-1/EMPERADOR-PERLA-CLASSIC-300x300.avif",
//         name: "Emperador Perla Klasik 101",
//       },
//       {
//         image: "./images/dogal/BejMermer/BejMermerPage-1/MONDO-300x300.avif",
//         name: "Mondo 101",
//       },
//       {
//         image: "./images/dogal/BejMermer/BejMermerPage-2/DUNE-300x300.avif",
//         name: "Dune 101",
//       },
//       {
//         image: "./images/dogal/BejMermer/BejMermerPage-2/BRUME-300x300.avif",
//         name: "Brume 101",
//       },
//       {
//         image: "./images/dogal/BejMermer/BejMermerPage-2/AVORIO-300x300.avif",
//         name: "Avorio 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/bardiglio-1-300x300.avif",
//         name: "Bardiglio Blu 101",
//       },
//     ],
//     [
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/BARDIGLIO-BLU-2-300x300.avif",
//         name: "Bardiglio Blu 102",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/BARDIGLIO-BLU-3-300x300.avif",
//         name: "Bardiglio Blu 103",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/BARDIGLIO-BLU-4-300x300.avif",
//         name: "Bardiglio Blu 104",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/IRIS-1-300x300.avif",
//         name: "Iris 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/IRIS-2-300x300.avif",
//         name: "Iris 102",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/IRIS-3-300x300.avif",
//         name: "Iris 103",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/IRIS-4-300x300.avif",
//         name: "Iris 104",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-5/Nero-1-300x300.avif",
//         name: "Nero 102",
//       },
//       {
//         image:
//           "./images/dogal/Traverten/SILVER-TRAVERTINE-VEIN-CUT-POLFIL-300x300.avif",
//         name: "Gümüş Traverten Düz Kesim 101",
//       },
//       {
//         image:
//           "./images/dogal/Traverten/SILVER-TRAVERTINE-VEIN-CUT-SAWCUT-300x300.avif",
//         name: "Gümüş Traverten Düz Kesim 102",
//       },
//       {
//         image: "./images/dogal/Traverten/SILVER-TRAVERTINE-VEIN-CUT-300x300.avif",
//         name: "Gümüş Traverten Düz Kesim 103",
//       },
//       {
//         image:
//           "./images/dogal/Traverten/SILVER-TRAVERTINE-VEIN-CUT-1-1-300x300.avif",
//         name: "Gümüş Traverten Düz Kesim 104",
//       },
//       {
//         image: "./images/dogal/Traverten/RIVER--300x300.avif",
//         name: "River 101",
//       },
//       {
//         image: "./images/dogal/Traverten/Imperial-Blend-300x300.avif",
//         name: "Imperial Blend 101",
//       },
//       {
//         image: "./images/dogal/Traverten/Royal-Blend-2-300x300.avif",
//         name: "Royal Blend 101",
//       },
//       {
//         image: "./images/dogal/Traverten/WARM-WALNUT-300x300.avif",
//         name: "Warm Walnut 101",
//       },
//       {
//         image: "./images/dogal/Traverten/CASHMERE-1-300x300.avif",
//         name: "Cashmere 101",
//       },
//       {
//         image: "./images/dogal/Traverten/WHITE-TRAVERTINE-300x300.avif",
//         name: "Beyaz Traverten 101",
//       },
//       {
//         image: "./images/dogal/Traverten/WHITE-TRAVERTINE-POLFIL-300x300.avif",
//         name: "Beyaz Traverten 102",
//       },
//       {
//         image: "./images/dogal/Traverten/WHITE-TRAVERTINE-VEIN-CUT-300x300.avif",
//         name: "Beyaz Traverten Düz Kesim 101",
//       },
//       {
//         image:
//           "./images/dogal/Traverten/WHITE-TRAVERTINE-VEIN-CUT-1-300x300.avif",
//         name: "Beyaz Traverten Düz Kesim 102",
//       },
//       {
//         image: "./images/dogal/Traverten/CLASSIC-TRAVERTINE-300x300.avif",
//         name: "Klasik Traverten 101",
//       },
//       {
//         image:
//           "./images/dogal/Traverten/CLASSIC-TRAVERTINE-VEIN-CUT-300x300.avif",
//         name: "Klasik Traverten Düz Kesim 101",
//       },
//       { image: "./images/dogal/Traverten/KALE-300x300.avif", name: "Kale 101" },
//     ],
//     [
//       {
//         image:
//           "./images/dogal/BejMermer/BejMermerPage-2/BLACK-PEARL-300x300.avif",
//         name: "Black Pearl 101",
//       },
//       {
//         image: "./images/dogal/Traverten/RED-TRAVERTINE-300x300.avif",
//         name: "Kırmızı Traverten 101",
//       },
//       {
//         image: "./images/dogal/Traverten/Rouge-Fleurs-300x300.avif",
//         name: "Kırmızı Traverten 102",
//       },
//       {
//         image: "./images/dogal/Traverten/Rouge-Fleurs2-300x300.avif",
//         name: "Kırmızı Traverten 103",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/BLACKBERRY-300x300.avif",
//         name: "Blackberry 101",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-6/BLACKBERRY-VEIN-CUT-300x300.avif",
//         name: "Blackberry Düz Kesim 101",
//       },

//       {
//         image: "./images/dogal/Traverten/RED-TRAVERTINE-VEIN-CUT-300x300.avif",
//         name: "Kırmızı Traverten Düz Kesim 101",
//       },
//       {
//         image: "./images/dogal/Traverten/RED-TRAVERTINE-VEIN-CUT2-300x300.avif",
//         name: "Kırmızı Traverten Düz Kesim 102",
//       },
//       {
//         image: "./images/dogal/Traverten/Cascade-White-300x300.avif",
//         name: "Cascade White 101",
//       },
//       {
//         image: "./images/dogal/Traverten/Cascade-White-Vein-Cut-300x300.avif",
//         name: "Cascade White Düz Kesim 101",
//       },
//       {
//         image: "./images/dogal/Traverten/GUNES-DUZ-KESIM-300x300.avif",
//         name: "Güneş Düz Kesim 101",
//       },
//       {
//         image: "./images/dogal/Traverten/SAFFRON-300x300.avif",
//         name: "Saffron 101",
//       },
//       {
//         image: "./images/dogal/Traverten/SAFFRON-VEIN-CUT-300x300.avif",
//         name: "Saffron Düz Kesim 101",
//       },
//       {
//         image:
//           "./images/dogal/BejMermer/BejMermerPage-2/BURSA-BEIGE-300x300.avif",
//         name: "Bursa Bej 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/EPICA-LIGHT-300x300.avif",
//         name: "Epica Light 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/EPICA-DARK-300x300.avif",
//         name: "Epica Dark 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/INSULA-ALBA-300x300.avif",
//         name: "Insula Alba 101",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-6/VERDE-GUATEMALA-2-300x300.avif",
//         name: "Verde Guatemala 102",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/VERDE-ESCURO-300x300.avif",
//         name: "Verde Escuro 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/BLACK-OLIVE-300x300.avif",
//         name: "Black Olive 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/FUME-300x300.avif",
//         name: "Füme 101",
//       },
//       {
//         image: "./images/dogal/BejMermer/Colorata-300x300.avif",
//         name: "Colorata 101",
//       },
//       {
//         image: "./images/dogal/BejMermer/LIGHT-EMPERADOR-300x300.avif",
//         name: "Light Emperador 101",
//       },
//       { image: "./images/dogal/BejMermer/DURU-300x300.avif", name: "Duru 101" },
//     ],
//     [
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/PINGUINO-300x300.avif",
//         name: "Pinguino 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/BLACK-ORION-1-300x300.avif",
//         name: "Black Orion 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/BLACK-AZIZA-300x300.avif",
//         name: "Black Aziza 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/PORTORO-300x300.avif",
//         name: "Portoro 101",
//       },
//       {
//         image:
//           "./images/dogal/BejMermer/BejMermerPage-2/SPANISH-DARK-EMPERADOR-300x300.avif",
//         name: "İspanyol Dark Emperador 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/SILVER-DRAGON-300x300.avif",
//         name: "Silver Dragon 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/SAINT-LAURENT-300x300.avif",
//         name: "Saint Laurent 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/zebrablack-300x300.avif",
//         name: "Zebra Black 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/MONT-BLANC-300x300.avif",
//         name: "Mont Blanc 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/METELL-300x300.avif",
//         name: "Metell 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/METELL-CLASSIC-300x300.avif",
//         name: "Metell Klasik 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/OCEAN-300x300.avif",
//         name: "Ocean 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/LILLA-300x300.avif",
//         name: "Lilla 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/NEW-YORK-300x300.avif",
//         name: "New York 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-6/VOLAKAS-300x300.avif",
//         name: "Volakas 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/calacatta-1-300x300.avif",
//         name: "Calacatta 105",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/CARRARA-300x300.avif",
//         name: "Carrara 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/CARRARA-BREZZA-300x300.avif",
//         name: "Carrara Brezza 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/MADREPERLA-300x300.avif",
//         name: "Madreperla 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/POLAR-WHITE-300x300.avif",
//         name: "Polar White 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/MUGLA-GRILI-300x300.avif",
//         name: "Muğla Grili 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/OLEA-300x300.avif",
//         name: "Olea 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/PANDA-WHITE-300x300.avif",
//         name: "Panda White 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/PANDA-WHITE-3-300x300.avif",
//         name: "Panda White 103",
//       },
//     ],
//     [
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/ICE-JADE-300x300.avif",
//         name: "Ice Jade 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/ICE-JADE-2-300x300.avif",
//         name: "Ice Jade 103",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/ICE-JADE-3-300x300.avif",
//         name: "Ice Jade 104",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/ICE-JADE-4-300x300.avif",
//         name: "Ice Jade 105",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/DESERT-WAVE-300x300.avif",
//         name: "Desert Wave 101",
//       },
//       {
//         image: "./images/dogal/Granit/S-Black-Granite-Cilali-1-1-300x300.avif",
//         name: "S Black – Cilalı 101",
//       },
//       {
//         image: "./images/dogal/Granit/S-Black-Granite-Cilali-2-300x300.avif",
//         name: "S Black – Cilalı 102",
//       },
//       {
//         image: "./images/dogal/Granit/S-Black-Granite-Honlu-1-1-300x300.avif",
//         name: "S Black – Honlu 101",
//       },
//       {
//         image: "./images/dogal/Granit/S-Black-Granite-Honlu-2-300x300.avif",
//         name: "S Black – Honlu 102",
//       },
//       {
//         image: "./images/dogal/Granit/S-Black-Granite-Kumlama-1-300x300.avif",
//         name: "S Black – Kumlama 101",
//       },
//       {
//         image: "./images/dogal/Granit/S-Black-Granite-Kumlama-2-300x300.avif",
//         name: "S Black – Kumlama 102",
//       },
//       {
//         image:
//           "./images/dogal/Granit/S-Black-Granite-Kumlu-Fircali-1-300x300.avif",
//         name: "S Black – Kumlama Fırçalı 101",
//       },
//       {
//         image:
//           "./images/dogal/Granit/S-Black-Granite-Kumlu-Fircali-2-300x300.avif",
//         name: "S Black – Kumlama Fırçalı 102",
//       },
//       { image: "./images/dogal/Granit/AMAZON-300x300.avif", name: "Amazon 101" },
//       {
//         image: "./images/dogal/Granit/ROSA-BETA-300x300.avif",
//         name: "Rosa Beta 101",
//       },
//       {
//         image: "./images/dogal/Granit/ROSA-MINHO-300x300.avif",
//         name: "Rosa Minho 101",
//       },
//       {
//         image: "./images/dogal/Dolomit/glacier-300x300.avif",
//         name: "Glacier 101",
//       },
//       {
//         image: "./images/dogal/Dolomit/glacierwhite-300x300.avif",
//         name: "Glacier White 101",
//       },
//       {
//         image: "./images/dogal/Oniks/SATIN-ONYX-300x300.avif",
//         name: "Satin Oniks 101",
//       },
//       {
//         image: "./images/dogal/Granit/IMPEARIAL-RED-300x300.avif",
//         name: "Imperial Red 101",
//       },
//       {
//         image: "./images/dogal/Traverten/Magnifica-300x300.avif",
//         name: "Magnifica 101",
//       },
//       {
//         image: "./images/dogal/Traverten/MAGNIFICA-VEIN-CUT-1-300x300.avif",
//         name: "Magnifica Düz Kesim 101",
//       },
//       {
//         image: "./images/dogal/Traverten/CAPPADOCE-VEIN-CUT-1-300x300.avif",
//         name: "Cappadoce Düz Kesim 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/MARMELADE-300x300.avif",
//         name: "Marmelade 101",
//       },
//     ],
//     [
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/VIOLET-300x300.avif",
//         name: "Violet 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/Medium-Emperador-300x300.avif",
//         name: "Medium Emperador 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/ZAMBAK-300x300.avif",
//         name: "Zambak 101",
//       },
//       {
//         image: "./images/dogal/Andezit/NIGELLA-300x300.avif",
//         name: "Nigella 101",
//       },
//       {
//         image: "./images/dogal/Andezit/NIGELLA-ROSE-300x300.avif",
//         name: "Nigella Rose 101",
//       },
//       {
//         image:
//           "./images/dogal/BejMermer/BejMermerPage-2/PIETRA-GREY-300x300.avif",
//         name: "Pietra Grey 101",
//       },
//       {
//         image:
//           "./images/dogal/Mermer/MermerPage-7/RAIN-FOREST-BROWN-300x300.avif",
//         name: "Rain Forest Brown 101",
//       },
//       {
//         image: "./images/dogal/Granit/ROSA-PORINHO-300x300.avif",
//         name: "Rosa Porinho 101",
//       },
//       {
//         image: "./images/dogal/Granit/AKSARAY-YAYLAK-300x300.avif",
//         name: "Aksaray Yaylak 101",
//       },
//       {
//         image: "./images/dogal/Oniks/SALMON-ONYX-300x300.avif",
//         name: "Salmon Oniks 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/BELLISSIMA-300x300.avif",
//         name: "Bellissima 101",
//       },
//       {
//         image: "./images/dogal/Limestone/Bianco-Bandia-1-300x300.avif",
//         name: "Suni Taş – Bianco Bandia – Honlu 101",
//       },
//       {
//         image: "./images/dogal/Limestone/Bianco-Bandia-eskitme-300x300.avif",
//         name: "Suni Taş – Bianco Bandia – Eskitme 101",
//       },
//       {
//         image: "./images/dogal/Limestone/Bianco-Bandia-kumlu-300x300.avif",
//         name: "Suni Taş – Bianco Bandia – Kumlama 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/TIGRATO-300x300.avif",
//         name: "Tigrato 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/CRYSTAL-WHITE-300x300.avif",
//         name: "Crystal White 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/armonia-1-300x300.avif",
//         name: "Armonia 101",
//       },
//       {
//         image: "./images/dogal/Mermer/MermerPage-7/woodenlight1-300x300.avif",
//         name: "Wooden Light 101",
//       },
//       {
//         image: "./images/dogal/Oniks/WHITE-ONYX-300x300.avif",
//         name: "Beyaz Oniks 101",
//       },
//       {
//         image: "./images/dogal/Oniks/DARK-DESERT-ROSE-300x300.avif",
//         name: "Dark Desert Rose 101",
//       },
//       {
//         image: "./images/dogal/Oniks/LIGHT-DESERT-ROSE-300x300.avif",
//         name: "Light Desert Rose 101",
//       },
//     ],
//   ];

export const plakalar = [
  [
    { image: "./images/mermer.avif", name: "Blue Ice Onyx 1001" },
    { image: "./images/mermer.avif", name: "Green Ice Onyx 1001" },
    { image: "./images/mermer.avif", name: "Pink Ice Onyx 1001" },
    { image: "./images/mermer.avif", name: "Amazonite 10001" },
    { image: "./images/mermer.avif", name: "Patagonia 10001" },
    { image: "./images/mermer.avif", name: "Azul Macoubas 10001" },
    { image: "./images/mermer.avif", name: "Desert Wave 1002" },
    { image: "./images/mermer.avif", name: "Panda Emerald Marble 1001" },
    { image: "./images/mermer.avif", name: "Rain Forest Brown 1003" },
    { image: "./images/mermer.avif", name: "Rain Forest Green 1001" },
    { image: "./images/mermer.avif", name: "Panda Azul 1001" },
    { image: "./images/mermer.avif", name: "Panda Azul 1002" },
    { image: "./images/mermer.avif", name: "Agate Blue 1001" },
    { image: "./images/mermer.avif", name: "Agate Green 1001" },
    { image: "./images/mermer.avif", name: "Agate Purple 1001" },
    { image: "./images/mermer.avif", name: "Grey Agate 1001" },
    { image: "./images/mermer.avif", name: "Petrified Wood 1001" },
    { image: "./images/mermer.avif", name: "Agate White 1001" },
    { image: "./images/mermer.avif", name: "Rosa Quartz 1001" },
    { image: "./images/mermer.avif", name: "Yellow Tiger Agate 1001" },
    { image: "./images/mermer.avif", name: "Round Agathe 1001" },
    { image: "./images/mermer.avif", name: "Dark Emperador 1002" },
    { image: "./images/mermer.avif", name: "Ice Jade 1010" },
    { image: "./images/mermer.avif", name: "Lilla 1005" },
  ],
  [
    { image: "./images/mermer.avif", name: "Magma Gold 1002" },
    { image: "./images/mermer.avif", name: "Petrified Wood Marble 1001" },
    { image: "./images/mermer.avif", name: "Black Aziza 1003" },
    { image: "./images/mermer.avif", name: "Green Oniks 1001" },
    { image: "./images/mermer.avif", name: "Nero Marquina 10001" },
    { image: "./images/mermer.avif", name: "Panda White 10001" },
    { image: "./images/mermer.avif", name: "Roma Black 101" },
    { image: "./images/mermer.avif", name: "Picasso 1002" },
    { image: "./images/mermer.avif", name: "Serpegiante Light 1002" },
    { image: "./images/mermer.avif", name: "Zebra Black 1003" },
    { image: "./images/mermer.avif", name: "Turtle 1002" },
    { image: "./images/mermer.avif", name: "Aqua Limo 101" },
    { image: "./images/mermer.avif", name: "Arabescato Gold 101" },
    { image: "./images/mermer.avif", name: "Salmon Oniks 1001" },
    { image: "./images/mermer.avif", name: "Black Marquina 101" },
    { image: "./images/mermer.avif", name: "Carrara 101" },
    { image: "./images/mermer.avif", name: "Diamond Gold 101" },
    { image: "./images/mermer.avif", name: "Pietra Grey 101" },
    { image: "./images/mermer.avif", name: "Salmon Oniks 1002" },
    { image: "./images/mermer.avif", name: "Tiger Oniks 1001" },
    { image: "./images/mermer.avif", name: "Tiger Oniks 1002" },
    { image: "./images/mermer.avif", name: "Wooden Oniks 1001" },
    { image: "./images/mermer.avif", name: "Travertino Grey 101" },
    { image: "./images/mermer.avif", name: "Volga Blue 101" },
  ],
  [
    { image: "./images/mermer.avif", name: "Wooden Oniks 1002" },
    { image: "./images/mermer.avif", name: "Beyaz Oniks 1001" },
    { image: "./images/mermer.avif", name: "Vivid White" },
    { image: "./images/mermer.avif", name: "Snow" },
    { image: "./images/mermer.avif", name: "White Shimmer" },
    { image: "./images/mermer.avif", name: "Frosty Carrina" },
    { image: "./images/mermer.avif", name: "Pure White" },
    { image: "./images/mermer.avif", name: "Nougat" },
    { image: "./images/mermer.avif", name: "Organic White" },
    { image: "./images/mermer.avif", name: "Ocean Foam" },
    { image: "./images/mermer.avif", name: "Intense White" },
    { image: "./images/mermer.avif", name: "London Grey" },
    { image: "./images/mermer.avif", name: "Empira White" },
    { image: "./images/mermer.avif", name: "White Attica" },
    { image: "./images/mermer.avif", name: "Ice Snow" },
    { image: "./images/mermer.avif", name: "Statuario Maximus" },
    { image: "./images/mermer.avif", name: "Cosmopolitan White" },
    { image: "./images/mermer.avif", name: "Calacatta Maximus" },
    { image: "./images/mermer.avif", name: "Cloudburst Concrete" },
    { image: "./images/mermer.avif", name: "Statuario Nuvo" },
    { image: "./images/mermer.avif", name: "Montblanc" },
    { image: "./images/mermer.avif", name: "Frozen Terra" },
    { image: "./images/mermer.avif", name: "Georgian Bluffs" },
    { image: "./images/mermer.avif", name: "Misty Carrera" },
  ],
  [
    { image: "./images/mermer.avif", name: "Nordic Loft" },
    { image: "./images/mermer.avif", name: "Alpine Mist" },
    { image: "./images/mermer.avif", name: "Dreamy Marfil" },
    { image: "./images/mermer.avif", name: "Clamshell" },
    { image: "./images/mermer.avif", name: "Calacatta Nuvo" },
    { image: "./images/mermer.avif", name: "Bianco Drift" },
    { image: "./images/mermer.avif", name: "Taj Royale" },
    { image: "./images/mermer.avif", name: "Buttermilk" },
    { image: "./images/mermer.avif", name: "Haze" },
    { image: "./images/mermer.avif", name: "Linen" },
    { image: "./images/mermer.avif", name: "Raw Concrete" },
    { image: "./images/mermer.avif", name: "Urban" },
    { image: "./images/mermer.avif", name: "Topus Concrete" },
    { image: "./images/mermer.avif", name: "Primordia" },
    { image: "./images/mermer.avif", name: "Symphony Grey" },
    { image: "./images/mermer.avif", name: "Airy Concrete" },
    { image: "./images/mermer.avif", name: "Noble Grey" },
    { image: "./images/mermer.avif", name: "Sleek Concrete" },
    { image: "./images/mermer.avif", name: "Shitake" },
    { image: "./images/mermer.avif", name: "Turbine Grey" },
    { image: "./images/mermer.avif", name: "Oyster" },
    { image: "./images/mermer.avif", name: "Atlantic Salt" },
    { image: "./images/mermer.avif", name: "Titan" },
    { image: "./images/mermer.avif", name: "Woodlands" },
  ],
  [
    { image: "./images/mermer.avif", name: "Oxidian" },
    { image: "./images/mermer.avif", name: "Fresh Concrete" },
    { image: "./images/mermer.avif", name: "Bianco Carrara 1" },
    { image: "./images/mermer.avif", name: "Concrete" },
    { image: "./images/mermer.avif", name: "Raven" },
    { image: "./images/mermer.avif", name: "Ginger" },
    { image: "./images/mermer.avif", name: "Lagos Blue" },
    { image: "./images/mermer.avif", name: "Excava" },
    { image: "./images/mermer.avif", name: "Rugged Concrete" },
    { image: "./images/mermer.avif", name: "Piatra Grey" },
    { image: "./images/mermer.avif", name: "Black Tempal" },
    { image: "./images/mermer.avif", name: "Vanilla Noir" },
    { image: "./images/mermer.avif", name: "Piatto Black" },
    { image: "./images/mermer.avif", name: "Black Noir" },
    { image: "./images/mermer.avif", name: "Calcatta Caldia 1" },
    { image: "./images/mermer.avif", name: "Jet Black" },
    { image: "./images/mermer.avif", name: "Pearl White 1" },
    { image: "./images/mermer.avif", name: "Sahara Noir 1" },
    { image: "./images/mermer.avif", name: "Serpegiante Light 10001" },
    { image: "./images/mermer.avif", name: "Azul Macaubas 1001" },
    { image: "./images/mermer.avif", name: "Azul Macaubas 1002" },
    { image: "./images/mermer.avif", name: "Black Leopar 1001" },
    { image: "./images/mermer.avif", name: "Panda White 1008" },
    { image: "./images/mermer.avif", name: "Serpegiante Light 1001" },
  ],
  [
    { image: "./images/mermer.avif", name: "Alps Blue 10001" },
    { image: "./images/mermer.avif", name: "Azul Macobus 10001" },
    { image: "./images/mermer.avif", name: "Van Gogh Blue 10001" },
    { image: "./images/mermer.avif", name: "Afyon White Spider 1001" },
    { image: "./images/mermer.avif", name: "Daisy" },
    { image: "./images/mermer.avif", name: "Aymina" },
    { image: "./images/mermer.avif", name: "Alaska" },
    { image: "./images/mermer.avif", name: "Bolera" },
    { image: "./images/mermer.avif", name: "Cordelia" },
    { image: "./images/mermer.avif", name: "Lusetia White" },
    { image: "./images/mermer.avif", name: "Sierra White" },
    { image: "./images/mermer.avif", name: "Mia" },
    { image: "./images/mermer.avif", name: "Aria" },
    { image: "./images/mermer.avif", name: "Rossa White" },
    { image: "./images/mermer.avif", name: "Visendra" },
    { image: "./images/mermer.avif", name: "Tornado" },
    { image: "./images/mermer.avif", name: "Admira" },
    { image: "./images/mermer.avif", name: "Lusida Grey" },
    { image: "./images/mermer.avif", name: "Olivia" },
    { image: "./images/mermer.avif", name: "Sima" },
    { image: "./images/mermer.avif", name: "Elatris" },
    { image: "./images/mermer.avif", name: "Caramela" },
    { image: "./images/mermer.avif", name: "Lusida Black" },
    { image: "./images/mermer.avif", name: "Rugiada" },
  ],
  [
    { image: "./images/mermer.avif", name: "Santa" },
    { image: "./images/mermer.avif", name: "Nidia" },
    { image: "./images/mermer.avif", name: "Sadira" },
    { image: "./images/mermer.avif", name: "Mirat" },
    { image: "./images/mermer.avif", name: "Hiearapolis" },
    { image: "./images/mermer.avif", name: "Arcadia" },
    { image: "./images/mermer.avif", name: "Artemis" },
    { image: "./images/mermer.avif", name: "Barents" },
    { image: "./images/mermer.avif", name: "Beach 1001" },
    { image: "./images/mermer.avif", name: "Lapland" },
    { image: "./images/mermer.avif", name: "Lilla 1002" },
    { image: "./images/mermer.avif", name: "Lilla 1003" },
    { image: "./images/mermer.avif", name: "Nebula" },
    { image: "./images/mermer.avif", name: "Nephila" },
    { image: "./images/mermer.avif", name: "Olympos" },
    { image: "./images/mermer.avif", name: "Sineda" },
    { image: "./images/mermer.avif", name: "Alpino" },
    { image: "./images/mermer.avif", name: "Tundra" },
    { image: "./images/mermer.avif", name: "Mora" },
    { image: "./images/mermer.avif", name: "Fuga" },
    { image: "./images/mermer.avif", name: "Versilia" },
    { image: "./images/mermer.avif", name: "Lebedos" },
    { image: "./images/mermer.avif", name: "Keops" },
    { image: "./images/mermer.avif", name: "Linen" },
  ],
  [
    { image: "./images/mermer.avif", name: "Terra" },
    { image: "./images/mermer.avif", name: "Smyrna" },
    { image: "./images/mermer.avif", name: "Lapaz" },
    { image: "./images/mermer.avif", name: "Troas" },
    { image: "./images/mermer.avif", name: "Etna" },
    { image: "./images/mermer.avif", name: "Ares" },
    { image: "./images/mermer.avif", name: "Boreas" },
    { image: "./images/mermer.avif", name: "Elvas" },
    { image: "./images/mermer.avif", name: "Kromit" },
    { image: "./images/mermer.avif", name: "Savana" },
    { image: "./images/mermer.avif", name: "Gharma" },
    { image: "./images/mermer.avif", name: "Toros" },
    { image: "./images/mermer.avif", name: "Carbone" },
    { image: "./images/mermer.avif", name: "Hermes" },
    { image: "./images/mermer.avif", name: "Armani Grey 10001" },
    { image: "./images/mermer.avif", name: "Calacatta Victory" },
    { image: "./images/mermer.avif", name: "Carrara 10001" },
    { image: "./images/mermer.avif", name: "Carrara Ultimo 10001" },
    { image: "./images/mermer.avif", name: "Invisible White 10001" },
    { image: "./images/mermer.avif", name: "Felisia" },
    { image: "./images/mermer.avif", name: "Macchia 10001" },
    { image: "./images/mermer.avif", name: "Marquina Venato 10001" },
    { image: "./images/mermer.avif", name: "Modern Statuario 10001" },
    { image: "./images/mermer.avif", name: "Pantheon" },
  ],
  [
    { image: "./images/mermer.avif", name: "Pietra Grey 10001" },
    { image: "./images/mermer.avif", name: "Rome 10001" },
    { image: "./images/mermer.avif", name: "Sahara Noir 10001" },
    { image: "./images/mermer.avif", name: "Statuario Elite 10001" },
    { image: "./images/mermer.avif", name: "Polaris" },
    { image: "./images/mermer.avif", name: "Anemon" },
    { image: "./images/mermer.avif", name: "Alinda" },
    { image: "./images/mermer.avif", name: "Kristella White" },
    { image: "./images/mermer.avif", name: "Sahara Beige" },
    { image: "./images/mermer.avif", name: "Montana" },
    { image: "./images/mermer.avif", name: "Aizano" },
    { image: "./images/mermer.avif", name: "Retro" },
    { image: "./images/mermer.avif", name: "Metropol Grey" },
    { image: "./images/mermer.avif", name: "Gala Black" },
    { image: "./images/mermer.avif", name: "Aspendos" },
    { image: "./images/mermer.avif", name: "Aurora" },
    { image: "./images/mermer.avif", name: "Belluno" },
    { image: "./images/mermer.avif", name: "Calacatta Veneto" },
    { image: "./images/mermer.avif", name: "Calacatta Verona" },
    { image: "./images/mermer.avif", name: "Carola" },
    { image: "./images/mermer.avif", name: "Teos" },
    { image: "./images/mermer.avif", name: "Daphne Crack" },
    { image: "./images/mermer.avif", name: "Elixir White" },
    { image: "./images/mermer.avif", name: "Fairy White" },
  ],
  [
    { image: "./images/mermer.avif", name: "Perla" },
    { image: "./images/mermer.avif", name: "Iceberg" },
    { image: "./images/mermer.avif", name: "Juliet White" },
    { image: "./images/mermer.avif", name: "Kashmera White" },
    { image: "./images/mermer.avif", name: "La Luna" },
    { image: "./images/mermer.avif", name: "Pixie Wings" },
    { image: "./images/mermer.avif", name: "Olympos" },
    { image: "./images/mermer.avif", name: "Mocca Mousse" },
    { image: "./images/mermer.avif", name: "Parma" },
    { image: "./images/mermer.avif", name: "Chakra" },
    { image: "./images/mermer.avif", name: "Boletus" },
    { image: "./images/mermer.avif", name: "Terre Grey" },
    { image: "./images/mermer.avif", name: "Babilon" },
    { image: "./images/mermer.avif", name: "Charmy" },
    { image: "./images/mermer.avif", name: "Forza Füme" },
    { image: "./images/mermer.avif", name: "Marquina Tierra" },
    { image: "./images/mermer.avif", name: "Spa Black" },
    { image: "./images/mermer.avif", name: "Volcano Black" },
    { image: "./images/mermer.avif", name: "Bardiglio Black 1001" },
    { image: "./images/mermer.avif", name: "Botticino 1001" },
    { image: "./images/mermer.avif", name: "Pinguino 1011" },
    { image: "./images/mermer.avif", name: "Panda White 1006" },
    { image: "./images/mermer.avif", name: "Panda White 1007" },
    { image: "./images/mermer.avif", name: "Emerald 1001" },
  ],
  [
    { image: "./images/mermer.avif", name: "Emerald 1002" },
    { image: "./images/mermer.avif", name: "Emerald 1003" },
    { image: "./images/mermer.avif", name: "Emerald 1004" },
    { image: "./images/mermer.avif", name: "Picasso 1001" },
    { image: "./images/mermer.avif", name: "Panda White 1005" },
    { image: "./images/mermer.avif", name: "Serpegiante 1001" },
    { image: "./images/mermer.avif", name: "Beyaz Oniks 1002" },
    { image: "./images/mermer.avif", name: "Beyaz Oniks 1003" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Mermer Oniks 1001" },
    { image: "./images/mermer.avif", name: "Marmara Beyaz Mermer 1001" },
    { image: "./images/mermer.avif", name: "Zebra White 1001" },
    { image: "./images/mermer.avif", name: "Blue Rain 1001" },
    { image: "./images/mermer.avif", name: "Hills 1001" },
    { image: "./images/mermer.avif", name: "Bruno 1001" },
    { image: "./images/mermer.avif", name: "Fusion 1001" },
    { image: "./images/mermer.avif", name: "Emerald 1004" },
    { image: "./images/mermer.avif", name: "Rain Forest Brown 1002" },
    { image: "./images/mermer.avif", name: "Statuario 1001" },
    { image: "./images/mermer.avif", name: "Nero 1001" },
    { image: "./images/mermer.avif", name: "Zebra Black 1002" },
    { image: "./images/mermer.avif", name: "Turtle 1001" },
    { image: "./images/mermer.avif", name: "Pedras Granit – Cilalı 101" },
    { image: "./images/mermer.avif", name: "Pedras Granit – Kumlama 102" },
    { image: "./images/mermer.avif", name: "Calacatta Oro 1001" },
  ],
  [
    { image: "./images/mermer.avif", name: "Zebra Grey 1001" },
    { image: "./images/mermer.avif", name: "Bal Oniks 1001" },
    { image: "./images/mermer.avif", name: "Bal Oniks 1002" },
    { image: "./images/mermer.avif", name: "Bal Oniks 1003" },
    { image: "./images/mermer.avif", name: "Bal Oniks 1004" },
    { image: "./images/mermer.avif", name: "Botticino 1002" },
    { image: "./images/mermer.avif", name: "Coquillage 1001" },
    { image: "./images/mermer.avif", name: "Bianco Crema 1001" },
    { image: "./images/mermer.avif", name: "Carrara Arabescato 1001" },
    { image: "./images/mermer.avif", name: "Bubble Oniks 1001" },
    { image: "./images/mermer.avif", name: "Cappuccino Oniks 1001" },
    { image: "./images/mermer.avif", name: "Velluto Oniks 1001" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Arcobaleno 1001" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1001" },
    { image: "./images/mermer.avif", name: "Sperenza 1001" },
    { image: "./images/mermer.avif", name: "Gümüş Oniks 1001" },
    { image: "./images/mermer.avif", name: "Gümüş Traverten 1001" },
    { image: "./images/mermer.avif", name: "Gümüş Traverten Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Verde Guatemala 1001" },
    { image: "./images/mermer.avif", name: "Verde Forest 1001" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1001" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 1001" },
    { image: "./images/mermer.avif", name: "Rosalia 1001" },
    { image: "./images/mermer.avif", name: "Rosalia Light 1001" },
  ],
  [
    { image: "./images/mermer.avif", name: "Light Emperador Klasik 1001" },
    { image: "./images/mermer.avif", name: "Pedras Granit – Kumlama 103" },
    { image: "./images/mermer.avif", name: "White Walker 101" },
    { image: "./images/mermer.avif", name: "White Walker – Küp Taşlar 101" },
    { image: "./images/mermer.avif", name: "White Walker – Küp Taşlar 102" },
    { image: "./images/mermer.avif", name: "White Walker – Küp Taşlar 103" },
    { image: "./images/mermer.avif", name: "Desert Black 101" },
    { image: "./images/mermer.avif", name: "Absolute Black 101" },
    { image: "./images/mermer.avif", name: "Star Galaxy 101" },
    { image: "./images/mermer.avif", name: "Paradiso 101" },
    { image: "./images/mermer.avif", name: "P White 101" },
    { image: "./images/mermer.avif", name: "Nero Marquina 1001" },
    { image: "./images/mermer.avif", name: "Nebel 1001" },
    { image: "./images/mermer.avif", name: "Blue Moon 1002" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Arcobaleno 1002" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Arcobaleno 1003" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Arcobaleno 1004" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Arcobaleno 1005" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Arcobaleno 1006" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Arcobaleno 1007" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Golden Gray 1001" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Golden Gray 1002" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Golden Gray 1003" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Golden Gray 1004" },
  ],
  [
    { image: "./images/mermer.avif", name: "Afyon Beyaz Golden Gray 1005" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Golden Gray 1006" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz A La Vogue 1001" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz A La Vogue 1002" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz A La Vogue 1003" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz A La Vogue 1004" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1001" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1002" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1003" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1004" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1005" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1006" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1007" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1008" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1009" },
    { image: "./images/mermer.avif", name: "Afyon Şeker 1001" },
    { image: "./images/mermer.avif", name: "Afyon Şeker 1002" },
    { image: "./images/mermer.avif", name: "Afyon Şeker 1003" },
    { image: "./images/mermer.avif", name: "Afyon Şeker 1004" },
    { image: "./images/mermer.avif", name: "Afyon Şeker 1005" },
    { image: "./images/mermer.avif", name: "Afyon Şeker 1006" },
    { image: "./images/mermer.avif", name: "Calacatta 1001" },
    { image: "./images/mermer.avif", name: "Calacatta 1002" },
    { image: "./images/mermer.avif", name: "Calacatta 1003" },
  ],
  [
    { image: "./images/mermer.avif", name: "Calacatta 1004" },
    { image: "./images/mermer.avif", name: "Calacatta 1005" },
    { image: "./images/mermer.avif", name: "Calacatta 1006" },
    { image: "./images/mermer.avif", name: "Calacatta 1007" },
    { image: "./images/mermer.avif", name: "Calacatta 1008" },
    { image: "./images/mermer.avif", name: "Calacatta 1009" },
    { image: "./images/mermer.avif", name: "Calacatta 1010" },
    { image: "./images/mermer.avif", name: "Calacatta 1011" },
    { image: "./images/mermer.avif", name: "Calacatta 1012" },
    { image: "./images/mermer.avif", name: "Calacatta 1013" },
    { image: "./images/mermer.avif", name: "Calacatta 1014" },
    { image: "./images/mermer.avif", name: "Calacatta 1015" },
    { image: "./images/mermer.avif", name: "Calacatta 1016" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1001" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1002" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1003" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1004" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1005" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1006" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1007" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1008" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1009" },
    { image: "./images/mermer.avif", name: "Nuage Doré 1001" },
    { image: "./images/mermer.avif", name: "Ice Jade 10001" },
  ],
  [
    { image: "./images/mermer.avif", name: "Ice Jade 10002" },
    { image: "./images/mermer.avif", name: "Ice Jade 10003" },
    { image: "./images/mermer.avif", name: "Silk White 10001" },
    { image: "./images/mermer.avif", name: "Glacier White 10001" },
    { image: "./images/mermer.avif", name: "Pure White 10001" },
    { image: "./images/mermer.avif", name: "Ivory Travertine Porcelain 10001" },
    { image: "./images/mermer.avif", name: "Calacatta 10001" },
    { image: "./images/mermer.avif", name: "Crema Bella 1001" },
    { image: "./images/mermer.avif", name: "Botanica 1001" },
    { image: "./images/mermer.avif", name: "Luna Piera 1001" },
    { image: "./images/mermer.avif", name: "Limpido 1001" },
    { image: "./images/mermer.avif", name: "Dark Emperador 1001" },
    { image: "./images/mermer.avif", name: "Dark Emperador Klasik 1001" },
    { image: "./images/mermer.avif", name: "Dune 1001" },
    { image: "./images/mermer.avif", name: "Luna 1001" },
    { image: "./images/mermer.avif", name: "Light Emperador 1001" },
    { image: "./images/mermer.avif", name: "Emperador Perla 1001" },
    { image: "./images/mermer.avif", name: "Emperador Perla Klasik 1001" },
    { image: "./images/mermer.avif", name: "Mondo-1001" },
    { image: "./images/mermer.avif", name: "Brume 1001" },
    { image: "./images/mermer.avif", name: "Avorio 1001" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1002" },
    { image: "./images/mermer.avif", name: "Crema Foret 1001" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1003" },
  ],
  [
    { image: "./images/mermer.avif", name: "Colorata 1001" },
    { image: "./images/mermer.avif", name: "Duru 1001" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1004" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1005" },
    { image: "./images/mermer.avif", name: "Burdur Bej 1001" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1006" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1007" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1008" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1009" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1010" },
    { image: "./images/mermer.avif", name: "Blue Bahia 1001" },
    { image: "./images/mermer.avif", name: "Blue Bahia 1002" },
    { image: "./images/mermer.avif", name: "Blue Moon 1001" },
    { image: "./images/mermer.avif", name: "Blue Moon 1003" },
    { image: "./images/mermer.avif", name: "Blue Moon 1004" },
    { image: "./images/mermer.avif", name: "Blue Moon 1005" },
    { image: "./images/mermer.avif", name: "Blue Moon 1006" },
    { image: "./images/mermer.avif", name: "Blue Moon 1007" },
    { image: "./images/mermer.avif", name: "Blue Stone 1001" },
    { image: "./images/mermer.avif", name: "Blue Stone 1002" },
    { image: "./images/mermer.avif", name: "Blue Stone 1003" },
    { image: "./images/mermer.avif", name: "Blue Moon Gold 1001" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Marine Blue 1001" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Marine Blue 1002" },
  ],
  [
    { image: "./images/mermer.avif", name: "Afyon Beyaz Marine Blue 1003" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Marine Blue 1004" },
    { image: "./images/mermer.avif", name: "Gümüş Oniks 1002" },
    { image: "./images/mermer.avif", name: "Gold Oniks 1001" },
    { image: "./images/mermer.avif", name: "Gold Oniks 1002" },
    { image: "./images/mermer.avif", name: "Cocacola Oniks 1001" },
    { image: "./images/mermer.avif", name: "Cocacola Oniks 1002" },
    { image: "./images/mermer.avif", name: "Satin Oniks 1001" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Marine Blue 1005" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Marine Blue 1006" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Marine Blue 1007" },
    { image: "./images/mermer.avif", name: "River 1001" },
    { image: "./images/mermer.avif", name: "Beyaz Traverten 1001" },
    { image: "./images/mermer.avif", name: "Epica 1001" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1002" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1003" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1004" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1005" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1006" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1007" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1008" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1009" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1010" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1011" },
  ],
  [
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1012" },
    { image: "./images/mermer.avif", name: "Pinguino 1010" },
    { image: "./images/mermer.avif", name: "Verde Escuro 1001" },
    { image: "./images/mermer.avif", name: "Klasik Traverten 1001" },
    { image: "./images/mermer.avif", name: "Beyaz Traverten Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Klasik Traverten Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Golden Crema 1001" },
    { image: "./images/mermer.avif", name: "Black Olive 1001" },
    { image: "./images/mermer.avif", name: "Black Olive 1002" },
    { image: "./images/mermer.avif", name: "Black Olive 1003" },
    { image: "./images/mermer.avif", name: "Black Olive 1004" },
    { image: "./images/mermer.avif", name: "Black Olive 1005" },
    { image: "./images/mermer.avif", name: "Black Olive 1006" },
    { image: "./images/mermer.avif", name: "Black Olive 1007" },
    { image: "./images/mermer.avif", name: "Black Olive 1008" },
    { image: "./images/mermer.avif", name: "Black Olive 1009" },
    { image: "./images/mermer.avif", name: "Black Olive 1010" },
    { image: "./images/mermer.avif", name: "Black Olive 1011" },
    { image: "./images/mermer.avif", name: "Füme 1001" },
    { image: "./images/mermer.avif", name: "Füme 1002" },
    { image: "./images/mermer.avif", name: "Füme 1003" },
    { image: "./images/mermer.avif", name: "Füme 1004" },
    { image: "./images/mermer.avif", name: "Füme 1005" },
    { image: "./images/mermer.avif", name: "Füme 1006" },
  ],
  [
    { image: "./images/mermer.avif", name: "Iris 1001" },
    { image: "./images/mermer.avif", name: "Iris 1002" },
    { image: "./images/mermer.avif", name: "Iris 1003" },
    { image: "./images/mermer.avif", name: "Iris 1004" },
    { image: "./images/mermer.avif", name: "Iris 1005" },
    { image: "./images/mermer.avif", name: "Iris 1006" },
    { image: "./images/mermer.avif", name: "Iris 1007" },
    { image: "./images/mermer.avif", name: "Iris 1008" },
    { image: "./images/mermer.avif", name: "Nebel 1002" },
    { image: "./images/mermer.avif", name: "Nebel 1003" },
    { image: "./images/mermer.avif", name: "Nebel 1004" },
    { image: "./images/mermer.avif", name: "Nebel 1005" },
    { image: "./images/mermer.avif", name: "Nebel 1006" },
    { image: "./images/mermer.avif", name: "Nebel 1007" },
    { image: "./images/mermer.avif", name: "Nebel 1008" },
    { image: "./images/mermer.avif", name: "Pinguino 1001" },
    { image: "./images/mermer.avif", name: "Pinguino 1002" },
    { image: "./images/mermer.avif", name: "Pinguino 1003" },
    { image: "./images/mermer.avif", name: "Pinguino 1004" },
    { image: "./images/mermer.avif", name: "Pinguino 1005" },
    { image: "./images/mermer.avif", name: "Pinguino 1006" },
    { image: "./images/mermer.avif", name: "Pinguino 1007" },
    { image: "./images/mermer.avif", name: "Pinguino 1008" },
    { image: "./images/mermer.avif", name: "Pinguino 1009" },
  ],
  [
    { image: "./images/mermer.avif", name: "Black Orion 1001" },
    { image: "./images/mermer.avif", name: "Black Aziza 1001" },
    { image: "./images/mermer.avif", name: "Black Aziza 1002" },
    { image: "./images/mermer.avif", name: "Black Pearl 1001" },
    { image: "./images/mermer.avif", name: "Portoro 1001" },
    { image: "./images/mermer.avif", name: "İspanyol Dark Emperador 1001" },
    { image: "./images/mermer.avif", name: "Silver Dragon 1001" },
    { image: "./images/mermer.avif", name: "Saint Laurent 1001" },
    { image: "./images/mermer.avif", name: "Zebra Black 1001" },
    { image: "./images/mermer.avif", name: "Zebra Black 1004" },
    { image: "./images/mermer.avif", name: "Ice Jade 1001" },
    { image: "./images/mermer.avif", name: "Ice Jade 1002" },
    { image: "./images/mermer.avif", name: "Ice Jade 1003" },
    { image: "./images/mermer.avif", name: "Ice Jade 1004" },
    { image: "./images/mermer.avif", name: "Ice Jade 1005" },
    { image: "./images/mermer.avif", name: "Ice Jade 1006" },
    { image: "./images/mermer.avif", name: "Ice Jade 1007" },
    { image: "./images/mermer.avif", name: "Ice Jade 1008" },
    { image: "./images/mermer.avif", name: "Ice Jade 1009" },
    { image: "./images/mermer.avif", name: "Mont Blanc 1001" },
    { image: "./images/mermer.avif", name: "Mont Blanc 1002" },
    { image: "./images/mermer.avif", name: "Mont Blanc 1003" },
    { image: "./images/mermer.avif", name: "Mont Blanc 1004" },
    { image: "./images/mermer.avif", name: "Metell 1001" },
  ],
  [
    { image: "./images/mermer.avif", name: "Metell Klasik 1001" },
    { image: "./images/mermer.avif", name: "Ocean 1001" },
    { image: "./images/mermer.avif", name: "Ocean 1002" },
    { image: "./images/mermer.avif", name: "Lilla 1001" },
    { image: "./images/mermer.avif", name: "Lilla 1004" },
    { image: "./images/mermer.avif", name: "New York 1001" },
    { image: "./images/mermer.avif", name: "Volakas 1001" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 1002" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 1003" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 1004" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 1005" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 1006" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 1007" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 1008" },
    { image: "./images/mermer.avif", name: "Carrara 1001" },
    { image: "./images/mermer.avif", name: "Carrara Brezza 1001" },
    { image: "./images/mermer.avif", name: "Carrara Brezza 1002" },
    { image: "./images/mermer.avif", name: "Carrara Brezza 1003" },
    { image: "./images/mermer.avif", name: "Carrara Brezza 1004" },
    { image: "./images/mermer.avif", name: "Madreperla 1001" },
    { image: "./images/mermer.avif", name: "Madreperla Klasik 1001" },
    { image: "./images/mermer.avif", name: "Polar White 1001" },
    { image: "./images/mermer.avif", name: "Polar White 1002" },
    { image: "./images/mermer.avif", name: "Polar White 1003" },
  ],
  [
    { image: "./images/mermer.avif", name: "Polar White 1004" },
    { image: "./images/mermer.avif", name: "Polar White 1005" },
    { image: "./images/mermer.avif", name: "Polar White 1006" },
    { image: "./images/mermer.avif", name: "Polar White 1007" },
    { image: "./images/mermer.avif", name: "Polar White 1008" },
    { image: "./images/mermer.avif", name: "Muğla Grili 1001" },
    { image: "./images/mermer.avif", name: "Olea 1001" },
    { image: "./images/mermer.avif", name: "Panda White 1001" },
    { image: "./images/mermer.avif", name: "Panda White 1002" },
    { image: "./images/mermer.avif", name: "Panda White 1003" },
    { image: "./images/mermer.avif", name: "Panda White 1004" },
    { image: "./images/mermer.avif", name: "Blackberry 1001" },
    { image: "./images/mermer.avif", name: "Blackberry Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Desert Wave 1001" },
    { image: "./images/mermer.avif", name: "Marmelade 1001" },
    { image: "./images/mermer.avif", name: "Violet 1001" },
    { image: "./images/mermer.avif", name: "Zambak 1001" },
    { image: "./images/mermer.avif", name: "Zambak 1002" },
    { image: "./images/mermer.avif", name: "Zambak 1003" },
    { image: "./images/mermer.avif", name: "Rain Forest Brown 1001" },
    { image: "./images/mermer.avif", name: "Bellissima 1001" },
    { image: "./images/mermer.avif", name: "Bellissima 1002" },
    { image: "./images/mermer.avif", name: "Bellissima 1003" },
    { image: "./images/mermer.avif", name: "Tigrato 1001" },
  ],
  [
    { image: "./images/mermer.avif", name: "Calimero 1001" },
    { image: "./images/mermer.avif", name: "Cappadoce Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Cashmere 1001" },
    { image: "./images/mermer.avif", name: "Kırmızı Traverten 1001" },
    { image: "./images/mermer.avif", name: "Kırmızı Traverten Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Saffron Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Crystal White 1001" },
    { image: "./images/mermer.avif", name: "Wooden Light 1001" },
    { image: "./images/mermer.avif", name: "Beyaz Mermer 101" },
    { image: "./images/mermer.avif", name: "Dark Desert Rose 1001" },
    { image: "./images/mermer.avif", name: "S Black – Cilalı 101" },
    { image: "./images/mermer.avif", name: "S Black – Cilalı 102" },
    { image: "./images/mermer.avif", name: "S Black – Honlu 101" },
    { image: "./images/mermer.avif", name: "S Black – Honlu 102" },
    { image: "./images/mermer.avif", name: "S Black – Kumlama 101" },
    { image: "./images/mermer.avif", name: "S Black – Kumlama 102" },
    { image: "./images/mermer.avif", name: "S Black – Kumlama Fırçalı 101" },
    { image: "./images/mermer.avif", name: "S Black – Kumlama Fırçalı 102" },
    { image: "./images/mermer.avif", name: "Amazon 101" },
    { image: "./images/mermer.avif", name: "Rosa Beta 101" },
    { image: "./images/mermer.avif", name: "Rosa Minho 101" },
    { image: "./images/mermer.avif", name: "Gargamel 1001" },
    { image: "./images/mermer.avif", name: "Güneş Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Warm Walnut 1001" },
  ],
  [
    { image: "./images/mermer.avif", name: "Warm Walnut Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Noce Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Imperial Red 101" },
    { image: "./images/mermer.avif", name: "Light Desert Rose 1001" },
    { image: "./images/mermer.avif", name: "Light Desert Rose 1002" },
    { image: "./images/mermer.avif", name: "Magnifica Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Blue Moon Mavi Mermer" },
    { image: "./images/mermer.avif", name: "Nigella 1001" },
    { image: "./images/mermer.avif", name: "Pietra Gray 1001" },
    { image: "./images/mermer.avif", name: "Rosa Porinho 101" },
    { image: "./images/mermer.avif", name: "Aksaray Yaylak 101" },
    { image: "./images/mermer.avif", name: "Siyah Mermer Plakalar" },
    { image: "./images/mermer.avif", name: "Sunny 1001" },
    { image: "./images/mermer.avif", name: "Sunny Light 1001" },
    { image: "./images/mermer.avif", name: "Suni Taş – Bianco Bandia 1001" },
    { image: "./images/mermer.avif", name: "Yeşil Mermer Plakalar" },
  ],
];

export const tezgahlar = [
  [
    { image: "", name: "Amazonite 10001" },
    { image: "", name: "Patagonia 10001" },
    { image: "", name: "Azul Macoubas 10001" },
    { image: "", name: "Nero Marquina 10001" },
    { image: "", name: "Panda White 10001" },
    { image: "", name: "Roma Black 101" },
    { image: "", name: "Aqua Limo 101" },
    { image: "", name: "Arabescato Gold 101" },
    { image: "", name: "Black Marquina 101" },
    { image: "", name: "Carrara 101" },
    { image: "", name: "Diamond Gold 101" },
    { image: "", name: "Pietra Grey 101" },
    { image: "", name: "Travertino Grey 101" },
    { image: "", name: "Volga Blue 101" },
    { image: "", name: "Vivid White" },
    { image: "", name: "Snow" },
    { image: "", name: "White Shimmer" },
    { image: "", name: "Frosty Carrina" },
    { image: "", name: "Pure White" },
    { image: "", name: "Nougat" },
    { image: "", name: "Organic White" },
    { image: "", name: "Ocean Foam" },
    { image: "", name: "Intense White" },
    { image: "", name: "London Grey" },
  ],
  [
    { image: "", name: "Empira White" },
    { image: "", name: "White Attica" },
    { image: "", name: "Ice Snow" },
    { image: "", name: "Statuario Maximus" },
    { image: "", name: "Cosmopolitan White" },
    { image: "", name: "Calacatta Maximus" },
    { image: "", name: "Cloudburst Concrete" },
    { image: "", name: "Statuario Nuvo" },
    { image: "", name: "Montblanc" },
    { image: "", name: "Frozen Terra" },
    { image: "", name: "Georgian Bluffs" },
    { image: "", name: "Misty Carrera" },
    { image: "", name: "Nordic Loft" },
    { image: "", name: "Alpine Mist" },
    { image: "", name: "Dreamy Marfil" },
    { image: "", name: "Clamshell" },
    { image: "", name: "Calacatta Nuvo" },
    { image: "", name: "Bianco Drift" },
    { image: "", name: "Taj Royale" },
    { image: "", name: "Buttermilk" },
    { image: "", name: "Haze" },
    { image: "", name: "Linen" },
    { image: "", name: "Raw Concrete" },
    { image: "", name: "Urban" },
  ],
  [
    { image: "", name: "Topus Concrete" },
    { image: "", name: "Primordia" },
    { image: "", name: "Symphony Grey" },
    { image: "", name: "Airy Concrete" },
    { image: "", name: "Noble Grey" },
    { image: "", name: "Sleek Concrete" },
    { image: "", name: "Shitake" },
    { image: "", name: "Turbine Grey" },
    { image: "", name: "Oyster" },
    { image: "", name: "Atlantic Salt" },
    { image: "", name: "Titan" },
    { image: "", name: "Woodlands" },
    { image: "", name: "Oxidian" },
    { image: "", name: "Fresh Concrete" },
    { image: "", name: "Bianco Carrara 1" },
    { image: "", name: "Concrete" },
    { image: "", name: "Raven" },
    { image: "", name: "Ginger" },
    { image: "", name: "Lagos Blue" },
    { image: "", name: "Excava" },
    { image: "", name: "Rugged Concrete" },
    { image: "", name: "Piatra Grey" },
    { image: "", name: "Black Tempal" },
    { image: "", name: "Vanilla Noir" },
  ],
  [
    { image: "", name: "Piatto Black" },
    { image: "", name: "Black Noir" },
    { image: "", name: "Calcatta Caldia 1" },
    { image: "", name: "Jet Black" },
    { image: "", name: "Pearl White 1" },
    { image: "", name: "Sahara Noir 1" },
    { image: "", name: "Serpegiante Light 10001" },
    { image: "", name: "Alps Blue 10001" },
    { image: "", name: "Azul Macobus 10001" },
    { image: "", name: "Van Gogh Blue 10001" },
    { image: "", name: "Daisy" },
    { image: "", name: "Aymina" },
    { image: "", name: "Alaska" },
    { image: "", name: "Bolera" },
    { image: "", name: "Cordelia" },
    { image: "", name: "Lusetia White" },
    { image: "", name: "Sierra White" },
    { image: "", name: "Mia" },
    { image: "", name: "Aria" },
    { image: "", name: "Rossa White" },
    { image: "", name: "Visendra" },
    { image: "", name: "Tornado" },
    { image: "", name: "Admira" },
    { image: "", name: "Lusida Grey" },
  ],
  [
    { image: "", name: "Olivia" },
    { image: "", name: "Sima" },
    { image: "", name: "Elatris" },
    { image: "", name: "Caramela" },
    { image: "", name: "Lusida Black" },
    { image: "", name: "Rugiada" },
    { image: "", name: "Santa" },
    { image: "", name: "Nidia" },
    { image: "", name: "Sadira" },
    { image: "", name: "Mirat" },
    { image: "", name: "Hiearapolis" },
    { image: "", name: "Arcadia" },
    { image: "", name: "Artemis" },
    { image: "", name: "Barents" },
    { image: "", name: "Lapland" },
    { image: "", name: "Nebula" },
    { image: "", name: "Nephila" },
    { image: "", name: "Olympos" },
    { image: "", name: "Sineda" },
    { image: "", name: "Alpino" },
    { image: "", name: "Tundra" },
    { image: "", name: "Mora" },
    { image: "", name: "Fuga" },
    { image: "", name: "Versilia" },
  ],
  [
    { image: "", name: "Lebedos" },
    { image: "", name: "Keops" },
    { image: "", name: "Linen" },
    { image: "", name: "Terra" },
    { image: "", name: "Smyrna" },
    { image: "", name: "Lapaz" },
    { image: "", name: "Troas" },
    { image: "", name: "Etna" },
    { image: "", name: "Ares" },
    { image: "", name: "Boreas" },
    { image: "", name: "Elvas" },
    { image: "", name: "Kromit" },
    { image: "", name: "Savana" },
    { image: "", name: "Gharma" },
    { image: "", name: "Toros" },
    { image: "", name: "Carbone" },
    { image: "", name: "Hermes" },
    { image: "", name: "Armani Grey 10001" },
    { image: "", name: "Calacatta Victory" },
    { image: "", name: "Carrara 10001" },
    { image: "", name: "Carrara Ultimo 10001" },
    { image: "", name: "Invisible White 10001" },
    { image: "", name: "Felisia" },
    { image: "", name: "Macchia 10001" },
  ],
  [
    { image: "", name: "Marquina Venato 10001" },
    { image: "", name: "Modern Statuario 10001" },
    { image: "", name: "Pantheon" },
    { image: "", name: "Pietra Grey 10001" },
    { image: "", name: "Rome 10001" },
    { image: "", name: "Sahara Noir 10001" },
    { image: "", name: "Statuario Elite 10001" },
    { image: "", name: "Polaris" },
    { image: "", name: "Anemon" },
    { image: "", name: "Alinda" },
    { image: "", name: "Kristella White" },
    { image: "", name: "Sahara Beige" },
    { image: "", name: "Montana" },
    { image: "", name: "Aizano" },
    { image: "", name: "Retro" },
    { image: "", name: "Metropol Grey" },
    { image: "", name: "Gala Black" },
    { image: "", name: "Aspendos" },
    { image: "", name: "Aurora" },
    { image: "", name: "Belluno" },
    { image: "", name: "Calacatta Veneto" },
    { image: "", name: "Calacatta Verona" },
    { image: "", name: "Carola" },
    { image: "", name: "Teos" },
  ],
  [
    { image: "", name: "Daphne Crack" },
    { image: "", name: "Elixir White" },
    { image: "", name: "Fairy White" },
    { image: "", name: "Perla" },
    { image: "", name: "Iceberg" },
    { image: "", name: "Juliet White" },
    { image: "", name: "Kashmera White" },
    { image: "", name: "La Luna" },
    { image: "", name: "Pixie Wings" },
    { image: "", name: "Olympos" },
    { image: "", name: "Mocca Mousse" },
    { image: "", name: "Parma" },
    { image: "", name: "Chakra" },
    { image: "", name: "Boletus" },
    { image: "", name: "Terre Grey" },
    { image: "", name: "Babilon" },
    { image: "", name: "Charmy" },
    { image: "", name: "Forza Füme" },
    { image: "", name: "Marquina Tierra" },
    { image: "", name: "Spa Black" },
    { image: "", name: "Volcano Black" },
    { image: "", name: "Ice Jade 10001" },
    { image: "", name: "Ice Jade 10002" },
    { image: "", name: "Ice Jade 10003" },
  ],
  [
    { image: "", name: "Silk White 10001" },
    { image: "", name: "Glacier White 10001" },
    { image: "", name: "Pure White 10001" },
    { image: "", name: "Ivory Travertine Porcelain 10001" },
    { image: "", name: "Marquina Venato 10001" },
    { image: "", name: "Calacatta 10001" },
  ],
];
