export const projects = [
  {
    image: "/images/projectCovers/ciraganKapak.jpg",
    name: "CIRAGAN PALACE RESTORATION PROJECT",
    filter: "interior",
    context: [
      "/images/projectContext/ciragan/ciragan1.avif",
      "/images/projectContext/ciragan/ciragan2.avif",
      "/images/projectContext/ciragan/ciragan3.avif",
      "/images/projectContext/ciragan/ciragan4.avif",
    ],
  },
  {
    image: "/images/projectCovers/peraPalaceKapak.jpeg",
    name: "PERA PALACE HOTEL",
    filter: "hotel",
    context: [
      "/images/projectContext/pera/pera1.jpg",
      "/images/projectContext/pera/pera2.jpg",
      "/images/projectContext/pera/pera3.jpg",
      "/images/projectContext/pera/pera4.jpeg",
      "/images/projectContext/pera/pera5.jpg",
      "/images/projectContext/pera/pera6.jpeg",
      "/images/projectContext/pera/pera7.jpg",
      "/images/projectContext/pera/pera8.jpeg",
    ],
  },
  {
    image: "/images/projectCovers/bookMatchKapak.png",
    name: "BOOKMATCH",
    filter: "interior",
    context: [
      "/images/projectContext/bookmatch/bookmatch1.jpeg",
      "/images/projectContext/bookmatch/bookmatch2.jpeg",
      "/images/projectContext/bookmatch/bookmatch3.png",
      "/images/projectContext/bookmatch/bookmatch4.png",
    ],
  },
  {
    image: "/images/projectCovers/sagalassosKapak.png",
    name: "SAGALASSOS ANCIENT CITY RESTORATION",
    filter: "restoration",
    context: [
      "/images/projectContext/sagalassos/sagalassos1.png",
      "/images/projectContext/sagalassos/sagalassos2.jpg",
      "/images/projectContext/sagalassos/sagalassos3.jpg",
      "/images/projectContext/sagalassos/sagalassos4.jpg",
    ],
  },
  {
    image: "/images/projectCovers/poolCapingKapak.png",
    name: "POOL COPING",
    filter: "outdoor",
    context: [
      "/images/projectContext/poolcaping/poolcaping1.avif",
      "/images/projectContext/poolcaping/poolcaping2.avif",
      "/images/projectContext/poolcaping/poolcaping3.avif",
      "/images/projectContext/poolcaping/poolcaping4.avif",
    ],
  },
  {
    image: "/images/projectCovers/mozartKapak.png",
    name: "MOZART BENGHAZI – LIBYA",
    filter: "restaurant",
    context: [
      "/images/projectContext/mozart/mozart1.avif",
      "/images/projectContext/mozart/mozart2.png",
      "/images/projectContext/mozart/mozart3.png",
      "/images/projectContext/mozart/mozart4.png",
    ],
  },
  {
    image: "/images/projectCovers/turkishBathroomKapak.jpg",
    name: "TURKISH BATH REFERENCES",
    filter: "bathroom",
    context: [
      "/images/projectContext/turkishBathReferences/turkishBathReferences1.avif",
      "/images/projectContext/turkishBathReferences/turkishBathReferences2.avif",
      "/images/projectContext/turkishBathReferences/turkishBathReferences3.avif",
      "/images/projectContext/turkishBathReferences/turkishBathReferences4.avif",
    ],
  },
  {
    image: "/images/projectCovers/CNCKapak.jpg",
    name: "CNC WALL DECORATION REFERENCES",
    filter: "interior",
    context: [
      "/images/projectContext/cncReferences/cncReferences1.avif",
      "/images/projectContext/cncReferences/cncReferences2.avif",
      "/images/projectContext/cncReferences/cncReferences3.avif",
      "/images/projectContext/cncReferences/cncReferences4.avif",
    ],
  },
  {
    image: "/images/projectCovers/stairsKapak.jpg",
    name: "STAIRS REFERENCES",
    filter: "interior",
    context: [
      "/images/projectContext/stairsReferences/stairsReferences1.avif",
      "/images/projectContext/stairsReferences/stairsReferences2.avif",
      "/images/projectContext/stairsReferences/stairsReferences3.avif",
      "/images/projectContext/stairsReferences/stairsReferences4.avif",
      "/images/projectContext/stairsReferences/stairsReferences5.avif",
      "/images/projectContext/stairsReferences/stairsReferences6.avif",
      "/images/projectContext/stairsReferences/stairsReferences7.avif",
      "/images/projectContext/stairsReferences/stairsReferences8.avif",
    ],
  },
  {
    image: "/images/projectCovers/vivaSuitKapak.png",
    name: "VIVA SUIT CAPPADOCIA",
    filter: "hotel",
    context: [
      "/images/projectContext/vivaSuitCappadocia/vivaSuitCappadocia1.avif",
      "/images/projectContext/vivaSuitCappadocia/vivaSuitCappadocia2.avif",
      "/images/projectContext/vivaSuitCappadocia/vivaSuitCappadocia3.avif",
      "/images/projectContext/vivaSuitCappadocia/vivaSuitCappadocia4.avif",
    ],
  },
  {
    image: "/images/projectCovers/silverOnixKapak.png",
    name: "SILVER ONYX BULGARIA PROJECT",
    filter: "interior",
    context: [
      "/images/projectContext/silverOnyxBulgaria/silverOnyxBulgaria1.png",
      "/images/projectContext/silverOnyxBulgaria/silverOnyxBulgaria2.png",
      "/images/projectContext/silverOnyxBulgaria/silverOnyxBulgaria3.png",
      "/images/projectContext/silverOnyxBulgaria/silverOnyxBulgaria4.avif",
    ],
  },
  {
    image: "/images/projectCovers/suraKapak.jpg",
    name: "SURA HOTEL",
    filter: "hotel",
    context: [
      "/images/projectContext/suraHotel/suraHotel1.jpg",
      "/images/projectContext/suraHotel/suraHotel2.jpg",
      "/images/projectContext/suraHotel/suraHotel3.jpg",
      "/images/projectContext/suraHotel/suraHotel4.avif",
    ],
  },
  {
    image: "/images/projectCovers/bestWesternKapak.jpg",
    name: "BEST WESTERN PREMIER CAPPADOCIA",
    filter: "hotel",
    context: [
      "/images/projectContext/bestWesternCappadocia/bestWesternCappadocia1.avif",
      "/images/projectContext/bestWesternCappadocia/bestWesternCappadocia2.jpg",
      "/images/projectContext/bestWesternCappadocia/bestWesternCappadocia3.jpg",
      "/images/projectContext/bestWesternCappadocia/bestWesternCappadocia4.jpg",
    ],
  },
  {
    image: "/images/projectCovers/sarnıçKapak.jpg",
    name: "SARNIC RESTAURANT – ISTANBUL",
    filter: "restaurant",
    context: [
      "/images/projectContext/sarnicRest/sarnicRest1.jpg",
      "/images/projectContext/sarnicRest/sarnicRest2.jpg",
      "/images/projectContext/sarnicRest/sarnicRest3.jpg",
      "/images/projectContext/sarnicRest/sarnicRest4.jpg",
    ],
  },
  {
    image: "/images/projectCovers/SuadiyetheHouseCafeKapak.jpg",
    name: "THE HOUSE CAFE – SUADIYE",
    filter: "restaurant",
    context: [
      "/images/projectContext/houseSuadiye/houseSuadiye1.avif",
      "/images/projectContext/houseSuadiye/houseSuadiye2.jpg",
      "/images/projectContext/houseSuadiye/houseSuadiye3.jpg",
      "/images/projectContext/houseSuadiye/houseSuadiye4.jpg",
    ],
  },
  {
    image: "/images/projectCovers/bulgariaKapak.jpeg",
    name: "BULGARIA PROJECT",
    filter: "interior",
    context: [
      "/images/projectContext/bulgariaProject/bulgariaProject1.jpg",
      "/images/projectContext/bulgariaProject/bulgariaProject2.jpeg",
      "/images/projectContext/bulgariaProject/bulgariaProject3.avif",
      "/images/projectContext/bulgariaProject/bulgariaProject4.jpeg",
    ],
  },
  {
    image: "/images/projectCovers/tekirovaKapak.jpg",
    name: "TEKIROVA QUEEN’S PARK",
    filter: "hotel",
    context: [
      "/images/projectContext/tekirovaQueens/tekirovaQueens1.jpg",
      "/images/projectContext/tekirovaQueens/tekirovaQueens2.jpg",
      "/images/projectContext/tekirovaQueens/tekirovaQueens3.jpg",
      "/images/projectContext/tekirovaQueens/tekirovaQueens4.jpg",
    ],
  },
  {
    image: "/images/projectCovers/benerKapak.jpg",
    name: "BENER LAW OFFICE",
    filter: "office",
    context: [
      "/images/projectContext/benerLaw/benerLaw1.jpg",
      "/images/projectContext/benerLaw/benerLaw2.jpg",
      "/images/projectContext/benerLaw/benerLaw3.avif",
      "/images/projectContext/benerLaw/benerLaw4.jpg",
    ],
  },
  {
    image: "/images/projectCovers/queenParkKapak.jpg",
    name: "QUEEN’ S PARK HOTEL",
    filter: "hotel",
    context: [
      "/images/projectContext/QueensPark/QueensPark1.jpg",
      "/images/projectContext/QueensPark/QueensPark2.jpg",
      "/images/projectContext/QueensPark/QueensPark3.avif",
      "/images/projectContext/QueensPark/QueensPark4.jpg",
    ],
  },
  {
    image: "/images/projectCovers/baltaLimanıKapak.jpg",
    name: "BALTALIMANI",
    filter: "interior",
    context: [
      "/images/projectContext/baltaLimanı/baltaLimanı1.avif",
      "/images/projectContext/baltaLimanı/baltaLimanı2.avif",
      "/images/projectContext/baltaLimanı/baltaLimanı3.avif",
      "/images/projectContext/baltaLimanı/baltaLimanı4.avif",
    ],
  },
  {
    image: "/images/projectCovers/lagünKapak.jpg",
    name: "LAGUN IRIS",
    filter: "interior",
    context: [
      "/images/projectContext/lagunIris/lagunIris1.avif",
      "/images/projectContext/lagunIris/lagunIris2.avif",
      "/images/projectContext/lagunIris/lagunIris3.avif",
      "/images/projectContext/lagunIris/lagunIris4.avif",
    ],
  },
  {
    image: "/images/projectCovers/kanyonKapak.jpg",
    name: "KANYON AVM – ESCALE",
    filter: "mall",
    context: [
      "/images/projectContext/kanyonAvm/kanyonAvm1.avif",
      "/images/projectContext/kanyonAvm/kanyonAvm2.avif",
      "/images/projectContext/kanyonAvm/kanyonAvm3.avif",
      "/images/projectContext/kanyonAvm/kanyonAvm4.avif",
    ],
  },
  {
    image: "/images/projectCovers/arkadiaKapak.jpg",
    name: "ARKADIA REZIDANS",
    filter: "residence",
    context: [
      "/images/projectContext/arkadia/arkadia1.avif",
      "/images/projectContext/arkadia/arkadia2.avif",
      "/images/projectContext/arkadia/arkadia3.avif",
      "/images/projectContext/arkadia/arkadia4.avif",
    ],
  },
  {
    image: "/images/projectCovers/afyonKapak.jpg",
    name: "AFYON GOVERNOR RESTORATION",
    filter: "restoration",
    context: [
      "/images/projectContext/afyonGoverner/afyonGoverner1.avif",
      "/images/projectContext/afyonGoverner/afyonGoverner2.avif",
      "/images/projectContext/afyonGoverner/afyonGoverner3.avif",
      "/images/projectContext/afyonGoverner/afyonGoverner4.avif",
    ],
  },
  {
    image: "/images/projectCovers/theHouseKapak.jpg",
    name: "THE HOUSE CAFE",
    filter: "restaurant",
    context: [
      "/images/projectContext/theHouseCafe/theHouseCafe1.jpg",
      "/images/projectContext/theHouseCafe/theHouseCafe2.avif",
      "/images/projectContext/theHouseCafe/theHouseCafe3.jpg",
      "/images/projectContext/theHouseCafe/theHouseCafe4.avif",
    ],
  },
  {
    image: "/images/projectCovers/qatarKapak.jpg",
    name: "QATAR PROJECT",
    filter: "office",
    context: [
      "/images/projectContext/qatar/qatar1.avif",
      "/images/projectContext/qatar/qatar2.avif",
      "/images/projectContext/qatar/qatar3.avif",
      "/images/projectContext/qatar/qatar4.jpg",
    ],
  },
  {
    image: "/images/projectCovers/longbeachKapak.jpg",
    name: "LONG BEACH RESORT HOTEL",
    filter: "hotel",
    context: [
      "/images/projectContext/longBeach/longBeach1.jpg",
      "/images/projectContext/longBeach/longBeach2.avif",
      "/images/projectContext/longBeach/longBeach3.avif",
      "/images/projectContext/longBeach/longBeach4.jpg",
    ],
  },
  {
    image: "/images/projectCovers/historicalKapak.jpg",
    name: "HISTORICAL REISOĞLU MANSION AND SELCUK’S TURKISH BATH",
    filter: "bathroom",
    context: [
      "/images/projectContext/reisoglu/reisoglu1.jpg",
      "/images/projectContext/reisoglu/reisoglu2.jpg",
      "/images/projectContext/reisoglu/reisoglu3.jpg",
      "/images/projectContext/reisoglu/reisoglu4.jpg",
      "/images/projectContext/reisoglu/reisoglu5.jpg",
      "/images/projectContext/reisoglu/reisoglu6.jpg",
      "/images/projectContext/reisoglu/reisoglu7.jpg",
      "/images/projectContext/reisoglu/reisoglu8.jpg",
    ],
  },
  {
    image: "/images/projectCovers/zuleyhaKuruKapak.jpg",
    name: "ZULEYHA KURU FASHION HOUSE",
    filter: "office",
    context: [
      "/images/projectContext/zuleyhaKoru/zuleyhaKoru1.jpg",
      "/images/projectContext/zuleyhaKoru/zuleyhaKoru2.jpg",
      "/images/projectContext/zuleyhaKoru/zuleyhaKoru3.jpg",
      "/images/projectContext/zuleyhaKoru/zuleyhaKoru4.jpg",
    ],
  },
  {
    image: "/images/projectCovers/bodrumVillaKapak.jpg",
    name: "BODRUM VILLA PROJECT",
    filter: "residence",
    context: [
      "/images/projectContext/bodrumVilla/bodrumVilla1.avif",
      "/images/projectContext/bodrumVilla/bodrumVilla2.avif",
      "/images/projectContext/bodrumVilla/bodrumVilla3.avif",
      "/images/projectContext/bodrumVilla/bodrumVilla4.avif",
    ],
  },
  {
    image: "/images/projectCovers/silverUkraineKapak.jpg",
    name: "SILVER ONYX UKRAINE PROJECT",
    filter: "restaurant",
    context: [
      "/images/projectContext/silverUkraine/silverUkraine1.avif",
      "/images/projectContext/silverUkraine/silverUkraine2.avif",
      "/images/projectContext/silverUkraine/silverUkraine3.avif",
      "/images/projectContext/silverUkraine/silverUkraine4.avif",
      "/images/projectContext/silverUkraine/silverUkraine5.avif",
      "/images/projectContext/silverUkraine/silverUkraine6.avif",
      "/images/projectContext/silverUkraine/silverUkraine7.avif",
      "/images/projectContext/silverUkraine/silverUkraine8.avif",
    ],
  },
  {
    image: "/images/projectCovers/taskiranKapak.jpg",
    name: "TASKIRAN MEDICAL AESTHETICS CLINIC",
    filter: "office",
    context: [
      "/images/projectContext/taskiran/taskiran1.avif",
      "/images/projectContext/taskiran/taskiran2.avif",
      "/images/projectContext/taskiran/taskiran3.avif",
      "/images/projectContext/taskiran/taskiran4.avif",
    ],
  },
  {
    image: "/images/projectCovers/UKRestorationKapak.jpg",
    name: "UK RESTORATION PROJECT",
    filter: "restoration",
    context: [
      "/images/projectContext/ukRestoration/ukRestoration1.jpg",
      "/images/projectContext/ukRestoration/ukRestoration2.jpg",
      "/images/projectContext/ukRestoration/ukRestoration3.avif",
      "/images/projectContext/ukRestoration/ukRestoration4.jpg",
    ],
  },
  {
    image: "/images/projectCovers/silverOnixTravertainKapak.jpeg",
    name: "SILVER ONYX – SILVER TRAVERTINE PROJECT",
    filter: "residence",
    context: [
      "/images/projectContext/silverTraverten/silverTraverten1.avif",
      "/images/projectContext/silverTraverten/silverTraverten2.avif",
      "/images/projectContext/silverTraverten/silverTraverten3.avif",
      "/images/projectContext/silverTraverten/silverTraverten4.avif",
    ],
  },
  {
    image: "/images/projectCovers/abuHayatKapak.jpg",
    name: "ABU HAYAT CAVE HOTEL",
    filter: "hotel",
    context: [
      "/images/projectContext/abuHayat/abuHayat1.jpg",
      "/images/projectContext/abuHayat/abuHayat2.jpg",
      "/images/projectContext/abuHayat/abuHayat3.jpg",
      "/images/projectContext/abuHayat/abuHayat4.jpg",
    ],
  },
  {
    image: "/images/projectCovers/adoraHotelKapak.jpg",
    name: "ADORA HOTEL & RESORT PROJECT",
    filter: "hotel",
    context: [
      "/images/projectContext/adora/adora1.avif",
      "/images/projectContext/adora/adora2.jpg",
      "/images/projectContext/adora/adora3.jpg",
      "/images/projectContext/adora/adora4.jpg",
    ],
  },
  {
    image: "/images/projectCovers/rividyaKapak.png",
    name: "RIVIDA VILLA PROJECT",
    filter: "residence",
    context: [
      "/images/projectContext/rivida/rivida1.png",
      "/images/projectContext/rivida/rivida2.png",
      "/images/projectContext/rivida/rivida3.avif",
      "/images/projectContext/rivida/rivida4.png",
    ],
  },
  {
    image: "/images/projectCovers/halicProjectKapak.jpeg",
    name: "HALIC PROJECT",
    filter: "interior",
    context: [
      "/images/projectContext/halic/halic1.jpeg",
      "/images/projectContext/halic/halic2.jpeg",
      "/images/projectContext/halic/halic3.avif",
      "/images/projectContext/halic/halic4.jpeg",
    ],
  },
];
