export const urunlerDekoratifSampuanlik = [
  [
    {
      image:
        "/images/urunler/Dekoratif/Sampuanlik/alavoguesampuanlik-300x300.jpg",
      name: "Dekoratif Ürünler – Şampuanlık 1001",
      array: "urunler",
      link1: "urunler",
      linkName1: "Ürünler",
      link2: "dekoratif",
      linkName2: "Dekoratif Ürünler",
      link3: "sampuanlik",
      linkName3: "Şampuanlık",
    },
    {
      image:
        "/images/urunler/Dekoratif/Sampuanlik/classiclightsampuanlik-300x300.jpg",
      name: "Dekoratif Ürünler – Şampuanlık 1002",
      array: "urunler",
      link1: "urunler",
      linkName1: "Ürünler",
      link2: "dekoratif",
      linkName2: "Dekoratif Ürünler",
      link3: "sampuanlik",
      linkName3: "Şampuanlık",
    },
    {
      image:
        "/images/urunler/Dekoratif/Sampuanlik/dynastiesampuanlik-300x300.jpg",
      name: "Dekoratif Ürünler – Şampuanlık 1003",
      array: "urunler",
      link1: "urunler",
      linkName1: "Ürünler",
      link2: "dekoratif",
      linkName2: "Dekoratif Ürünler",
      link3: "sampuanlik",
      linkName3: "Şampuanlık",
    },
    {
      image:
        "/images/urunler/Dekoratif/Sampuanlik/euphoriesampuanlik-300x300.jpg",
      name: "Dekoratif Ürünler – Şampuanlık 1004",
      array: "urunler",
      link1: "urunler",
      linkName1: "Ürünler",
      link2: "dekoratif",
      linkName2: "Dekoratif Ürünler",
      link3: "sampuanlik",
      linkName3: "Şampuanlık",
    },
    {
      image:
        "/images/urunler/Dekoratif/Sampuanlik/eventailsampuanlik-300x300.jpg",
      name: "Dekoratif Ürünler – Şampuanlık 1005",
      array: "urunler",
      link1: "urunler",
      linkName1: "Ürünler",
      link2: "dekoratif",
      linkName2: "Dekoratif Ürünler",
      link3: "sampuanlik",
      linkName3: "Şampuanlık",
    },
    {
      image: "/images/urunler/Dekoratif/Sampuanlik/pearlsampuanlik-300x300.jpg",
      name: "Dekoratif Ürünler – Şampuanlık 1006",
      array: "urunler",
      link1: "urunler",
      linkName1: "Ürünler",
      link2: "dekoratif",
      linkName2: "Dekoratif Ürünler",
      link3: "sampuanlik",
      linkName3: "Şampuanlık",
    },
    {
      image:
        "/images/urunler/Dekoratif/Sampuanlik/saffronsampuanlik-300x300.jpg",
      name: "Dekoratif Ürünler – Şampuanlık 1007",
      array: "urunler",
      link1: "urunler",
      linkName1: "Ürünler",
      link2: "dekoratif",
      linkName2: "Dekoratif Ürünler",
      link3: "sampuanlik",
      linkName3: "Şampuanlık",
    },
    {
      image:
        "/images/urunler/Dekoratif/Sampuanlik/warmwalnutsampuanlik-300x300.jpg",
      name: "Dekoratif Ürünler – Şampuanlık 1008",
      array: "urunler",
      link1: "urunler",
      linkName1: "Ürünler",
      link2: "dekoratif",
      linkName2: "Dekoratif Ürünler",
      link3: "sampuanlik",
      linkName3: "Şampuanlık",
    },
  ],
];
