export const ozelKoleksiyon = [
  [
    { image: "./images/mermer.avif", name: "Panda Emerald Marble 101" },
    { image: "./images/mermer.avif", name: "Rain Forest Brown 103" },
    { image: "./images/mermer.avif", name: "Rain Forest Green 101" },
    { image: "./images/mermer.avif", name: "Panda Azul 101" },
    { image: "./images/mermer.avif", name: "Panda Azul 102" },
    { image: "./images/mermer.avif", name: "Agate Blue 1" },
    { image: "./images/mermer.avif", name: "Agate Blue 2" },
    { image: "./images/mermer.avif", name: "Agate Green 1" },
    { image: "./images/mermer.avif", name: "Agate Green 2" },
    { image: "./images/mermer.avif", name: "Agate Purple 1" },
    { image: "./images/mermer.avif", name: "Grey Agate 1" },
    { image: "./images/mermer.avif", name: "Petrified Wood 1" },
    { image: "./images/mermer.avif", name: "Agate White 1" },
    { image: "./images/mermer.avif", name: "Round Agathe 1" },
    { image: "./images/mermer.avif", name: "Round Agathe 2" },
    { image: "./images/mermer.avif", name: "Agate Athena Gold" },
    { image: "./images/mermer.avif", name: "Rosa Quartz 1" },
    { image: "./images/mermer.avif", name: "Yellow Tiger Agate 1" },
    { image: "./images/mermer.avif", name: "Agate Black Dim Gold" },
    { image: "./images/mermer.avif", name: "Agate Cezanne Gold" },
    { image: "./images/mermer.avif", name: "Agate Phoenix" },
    { image: "./images/mermer.avif", name: "Amazonite" },
    { image: "./images/mermer.avif", name: "Fluorite" },
    { image: "./images/mermer.avif", name: "Green Agate" },
  ],
  [
    { image: "./images/mermer.avif", name: "Turtle 101" },
    { image: "./images/mermer.avif", name: "Turtle 102" },
    { image: "./images/mermer.avif", name: "Emerald 101" },
    { image: "./images/mermer.avif", name: "Emerald 102" },
    { image: "./images/mermer.avif", name: "Emerald 103" },
    { image: "./images/mermer.avif", name: "Emerald 104" },
    { image: "./images/mermer.avif", name: "Hills 101" },
    { image: "./images/mermer.avif", name: "Beyaz Oniks 102" },
    { image: "./images/mermer.avif", name: "Rain Forest Brown 102" },
    { image: "./images/mermer.avif", name: "Verde Forest 101" },
    { image: "./images/mermer.avif", name: "Black Aziza 101" },
    { image: "./images/mermer.avif", name: "Ice Jade 101" },
    { image: "./images/mermer.avif", name: "Desert Wave 101" },
  ],
];

export const dogalTaslar = [
  [
    { image: "./images/mermer.avif", name: "Blue Ice Onyx 101" },
    { image: "./images/mermer.avif", name: "Green Ice Onyx 101" },
    { image: "./images/mermer.avif", name: "Pink Ice Onyx 101" },
    { image: "./images/mermer.avif", name: "Desert Wave 102" },
    { image: "./images/mermer.avif", name: "Panda Emerald Marble 101" },
    { image: "./images/mermer.avif", name: "Rain Forest Brown 103" },
    { image: "./images/mermer.avif", name: "Rain Forest Green 101" },
    { image: "./images/mermer.avif", name: "Panda Azul 101" },
    { image: "./images/mermer.avif", name: "Panda Azul 102" },
    { image: "./images/mermer.avif", name: "Magma Gold 102" },
    { image: "./images/mermer.avif", name: "Ice Jade 106" },
    { image: "./images/mermer.avif", name: "Petrified Wood Marble 101" },
    { image: "./images/mermer.avif", name: "Dark Emperador 102" },
    { image: "./images/mermer.avif", name: "Agate Blue 1" },
    { image: "./images/mermer.avif", name: "Agate Blue 2" },
    { image: "./images/mermer.avif", name: "Agate Green 1" },
    { image: "./images/mermer.avif", name: "Agate Green 2" },
    { image: "./images/mermer.avif", name: "Agate Purple 1" },
    { image: "./images/mermer.avif", name: "Grey Agate 1" },
    { image: "./images/mermer.avif", name: "Petrified Wood 1" },
    { image: "./images/mermer.avif", name: "Agate White 1" },
    { image: "./images/mermer.avif", name: "Round Agathe 1" },
    { image: "./images/mermer.avif", name: "Round Agathe 2" },
    { image: "./images/mermer.avif", name: "Azul Macaubas 101" },
  ],
  [
    { image: "./images/mermer.avif", name: "Azul Macaubas 102" },
    { image: "./images/mermer.avif", name: "Black Leopar 101" },
    { image: "./images/mermer.avif", name: "Serpegiante Light 101" },
    { image: "./images/mermer.avif", name: "Tiger Oniks 101" },
    { image: "./images/mermer.avif", name: "Tiger Oniks 102" },
    { image: "./images/mermer.avif", name: "Wooden Onyx 101" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Mermer Spider 101" },
    { image: "./images/mermer.avif", name: "Panda White 105" },
    { image: "./images/mermer.avif", name: "Panda White 106" },
    { image: "./images/mermer.avif", name: "Beach 101" },
    { image: "./images/mermer.avif", name: "Picasso 101" },
    { image: "./images/mermer.avif", name: "Nero Gold 101" },
    { image: "./images/mermer.avif", name: "Armani" },
    { image: "./images/mermer.avif", name: "Chateaux" },
    { image: "./images/mermer.avif", name: "Pinguino Klasik" },
    { image: "./images/mermer.avif", name: "Bardiglio Black 101" },
    { image: "./images/mermer.avif", name: "Botticino 101" },
    { image: "./images/mermer.avif", name: "Pinguino 102" },
    { image: "./images/mermer.avif", name: "Agate Athena Gold" },
    { image: "./images/mermer.avif", name: "Rosa Quartz 1" },
    { image: "./images/mermer.avif", name: "Yellow Tiger Agate 1" },
    { image: "./images/mermer.avif", name: "Agate Black Dim Gold" },
    { image: "./images/mermer.avif", name: "Agate Cezanne Gold" },
    { image: "./images/mermer.avif", name: "Agate Phoenix" },
  ],
  [
    { image: "./images/mermer.avif", name: "Amazonite" },
    { image: "./images/mermer.avif", name: "Fluorite" },
    { image: "./images/mermer.avif", name: "Green Agate" },
    { image: "./images/mermer.avif", name: "Turtle 102" },
    { image: "./images/mermer.avif", name: "Emerald 101" },
    { image: "./images/mermer.avif", name: "Emerald 102" },
    { image: "./images/mermer.avif", name: "Emerald 103" },
    { image: "./images/mermer.avif", name: "Emerald 104" },
    { image: "./images/mermer.avif", name: "Hills 101" },
    { image: "./images/mermer.avif", name: "Beyaz Oniks 102" },
    { image: "./images/mermer.avif", name: "Panda White 104" },
    { image: "./images/mermer.avif", name: "Serpegiante 101" },
    { image: "./images/mermer.avif", name: "Marmara Beyaz Mermer 101" },
    { image: "./images/mermer.avif", name: "Zebra White 101" },
    { image: "./images/mermer.avif", name: "Blue Rain 101" },
    { image: "./images/mermer.avif", name: "Fusion 101" },
    { image: "./images/mermer.avif", name: "Rain Forest Brown 102" },
    { image: "./images/mermer.avif", name: "Statuario 101" },
    { image: "./images/mermer.avif", name: "Nero 101" },
    { image: "./images/mermer.avif", name: "Bruno Perla 101" },
    { image: "./images/mermer.avif", name: "Zebra Black 102" },
    { image: "./images/mermer.avif", name: "Bruno 101" },
    { image: "./images/mermer.avif", name: "Ice Jade 102" },
    { image: "./images/mermer.avif", name: "Panda White 102" },
  ],
  [
    { image: "./images/mermer.avif", name: "Turtle 101" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Oniks 101" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Oniks 102" },
    {
      image: "./images/mermer.avif",
      name: "Afyon Beyaz Mermer Billur Gold 101",
    },
    {
      image: "./images/mermer.avif",
      name: "Afyon Beyaz Mermer Billur Gold 102",
    },
    { image: "./images/mermer.avif", name: "Pedras Granit – Cilalı 101" },
    { image: "./images/mermer.avif", name: "Pedras Granit – Kumlama 102" },
    { image: "./images/mermer.avif", name: "Antique Pewter – Honlu 101" },
    { image: "./images/mermer.avif", name: "Antique Pewter – Eskitme 101" },
    { image: "./images/mermer.avif", name: "Calacatta Oro 101" },
    { image: "./images/mermer.avif", name: "Zebra Grey 101" },
    { image: "./images/mermer.avif", name: "Bal Oniks 101" },
    { image: "./images/mermer.avif", name: "White Beauty Premium" },
    { image: "./images/mermer.avif", name: "Carrara Arabescato 101" },
    { image: "./images/mermer.avif", name: "Bubble Oniks 101" },
    { image: "./images/mermer.avif", name: "Cappuccino Oniks 101" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Blue Bahia 101" },
    { image: "./images/mermer.avif", name: "Dış Mekan – White Walker 101" },
    { image: "./images/mermer.avif", name: "Dış Mekan – White Walker 102" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 101" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 102" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 103" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 104" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 105" },
  ],
  [
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 106" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 107" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 108" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 109" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 110" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 111" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 112" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 113" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 114" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 115" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 116" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 117" },
    { image: "./images/mermer.avif", name: "Dış Mekan – Referans 118" },
    { image: "./images/mermer.avif", name: "Velluto Oniks 101" },
    { image: "./images/mermer.avif", name: "Gümüş Oniks 101" },
    { image: "./images/mermer.avif", name: "Gümüş Oniks 102" },
    {
      image: "./images/mermer.avif",
      name: "Afyon Beyaz Mermer Arcobaleno 101",
    },
    {
      image: "./images/mermer.avif",
      name: "Afyon Beyaz Mermer Golden Gray 101",
    },
    {
      image: "./images/mermer.avif",
      name: "Afyon Beyaz Mermer A La Vogue 101",
    },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Mermer Billur 101" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Mermer Billur 102" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Mermer Billur 103" },
    { image: "./images/mermer.avif", name: "Sperenza 101" },
    { image: "./images/mermer.avif", name: "Calacatta 101" },
  ],
  [
    { image: "./images/mermer.avif", name: "Calacatta 102" },
    { image: "./images/mermer.avif", name: "Gold Oniks 101" },
    { image: "./images/mermer.avif", name: "Cocacola Oniks 101" },
    { image: "./images/mermer.avif", name: "Coquillage 101" },
    { image: "./images/mermer.avif", name: "Bianco Crema 101" },
    { image: "./images/mermer.avif", name: "Bianco Crema 102" },
    { image: "./images/mermer.avif", name: "Bianco Crema 103" },
    { image: "./images/mermer.avif", name: "Golden Crema 101" },
    { image: "./images/mermer.avif", name: "Sunny 101" },
    { image: "./images/mermer.avif", name: "Sunny Light 101" },
    { image: "./images/mermer.avif", name: "Mocca – Cilalı 101" },
    { image: "./images/mermer.avif", name: "Gargamel 101" },
    { image: "./images/mermer.avif", name: "Calimero 101" },
    { image: "./images/mermer.avif", name: "Calimero – Küp Taşlar 101" },
    { image: "./images/mermer.avif", name: "Calimero – Küp Taşlar 102" },
    { image: "./images/mermer.avif", name: "Calimero – Küp Taşlar 103" },
    { image: "./images/mermer.avif", name: "Gümüş Traverten 101" },
    { image: "./images/mermer.avif", name: "Gümüş Traverten 102" },
    { image: "./images/mermer.avif", name: "Gümüş Traverten 103" },
    { image: "./images/mermer.avif", name: "Verde Guatemala 101" },
    { image: "./images/mermer.avif", name: "Verde Forest 101" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 101" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 101" },
    { image: "./images/mermer.avif", name: "Lilla 102" },
  ],
  [
    { image: "./images/mermer.avif", name: "Rosalia 101" },
    { image: "./images/mermer.avif", name: "Rosalia Light 101" },
    { image: "./images/mermer.avif", name: "Light Emperador Klasik Mermer" },
    { image: "./images/mermer.avif", name: "Pedras Granit – Kumlama 103" },
    { image: "./images/mermer.avif", name: "White Walker 101" },
    { image: "./images/mermer.avif", name: "White Walker – Küp Taşlar 101" },
    { image: "./images/mermer.avif", name: "White Walker – Küp Taşlar 102" },
    { image: "./images/mermer.avif", name: "White Walker – Küp Taşlar 103" },
    { image: "./images/mermer.avif", name: "Desert Black 101" },
    { image: "./images/mermer.avif", name: "Nero Marquina 101" },
    { image: "./images/mermer.avif", name: "Nebel 101" },
    { image: "./images/mermer.avif", name: "Absolute Black 101" },
    { image: "./images/mermer.avif", name: "Star Galaxy 101" },
    { image: "./images/mermer.avif", name: "Paradiso 101" },
    { image: "./images/mermer.avif", name: "P White 101" },
    { image: "./images/mermer.avif", name: "Mocca – Honlu 101" },
    { image: "./images/mermer.avif", name: "Mocca – Eskitme 101" },
    { image: "./images/mermer.avif", name: "Mocca – Fırçalı 101" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Mermer Şeker 101" },
    { image: "./images/mermer.avif", name: "Calacatta 103" },
    { image: "./images/mermer.avif", name: "Calacatta 104" },
    { image: "./images/mermer.avif", name: "Blue Moon 101" },
    { image: "./images/mermer.avif", name: "Blue Moon 102" },
    { image: "./images/mermer.avif", name: "Blue Moon 103" },
  ],
  [
    { image: "./images/mermer.avif", name: "Nuage Miel 101" },
    { image: "./images/mermer.avif", name: "Nuage Doré 101" },
    { image: "./images/mermer.avif", name: "Blue Bahia 101" },
    { image: "./images/mermer.avif", name: "Blue Bahia 102" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Marine Blue 101" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Marine Blue 106" },
    { image: "./images/mermer.avif", name: "Blue Stone 101" },
    { image: "./images/mermer.avif", name: "Blue Moon Gold 101" },
    { image: "./images/mermer.avif", name: "Crema Bella 101" },
    { image: "./images/mermer.avif", name: "Crema Foret 101" },
    { image: "./images/mermer.avif", name: "Luna 101" },
    { image: "./images/mermer.avif", name: "Botanica 101" },
    { image: "./images/mermer.avif", name: "Limpido 101" },
    { image: "./images/mermer.avif", name: "Luna Piera 101" },
    { image: "./images/mermer.avif", name: "Dark Emperador 101" },
    { image: "./images/mermer.avif", name: "Dark Emperador Klasik 101" },
    { image: "./images/mermer.avif", name: "Bruno Perla 102" },
    { image: "./images/mermer.avif", name: "Emperador Perla 101" },
    { image: "./images/mermer.avif", name: "Emperador Perla Klasik 101" },
    { image: "./images/mermer.avif", name: "Mondo 101" },
    { image: "./images/mermer.avif", name: "Dune 101" },
    { image: "./images/mermer.avif", name: "Brume 101" },
    { image: "./images/mermer.avif", name: "Avorio 101" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 101" },
  ],
  [
    { image: "./images/mermer.avif", name: "Bardiglio Blu 102" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 103" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 104" },
    { image: "./images/mermer.avif", name: "Iris 101" },
    { image: "./images/mermer.avif", name: "Iris 102" },
    { image: "./images/mermer.avif", name: "Iris 103" },
    { image: "./images/mermer.avif", name: "Iris 104" },
    { image: "./images/mermer.avif", name: "Nero 102" },
    { image: "./images/mermer.avif", name: "Gümüş Traverten Düz Kesim 101" },
    { image: "./images/mermer.avif", name: "Gümüş Traverten Düz Kesim 102" },
    { image: "./images/mermer.avif", name: "Gümüş Traverten Düz Kesim 103" },
    { image: "./images/mermer.avif", name: "Gümüş Traverten Düz Kesim 104" },
    { image: "./images/mermer.avif", name: "River 101" },
    { image: "./images/mermer.avif", name: "Imperial Blend 101" },
    { image: "./images/mermer.avif", name: "Royal Blend 101" },
    { image: "./images/mermer.avif", name: "Warm Walnut 101" },
    { image: "./images/mermer.avif", name: "Cashmere 101" },
    { image: "./images/mermer.avif", name: "Beyaz Traverten 101" },
    { image: "./images/mermer.avif", name: "Beyaz Traverten 102" },
    { image: "./images/mermer.avif", name: "Beyaz Traverten Düz Kesim 101" },
    { image: "./images/mermer.avif", name: "Beyaz Traverten Düz Kesim 102" },
    { image: "./images/mermer.avif", name: "Klasik Traverten 101" },
    { image: "./images/mermer.avif", name: "Klasik Traverten Düz Kesim 101" },
    { image: "./images/mermer.avif", name: "Kale 101" },
  ],
  [
    { image: "./images/mermer.avif", name: "Black Pearl 101" },
    { image: "./images/mermer.avif", name: "Kırmızı Traverten 101" },
    { image: "./images/mermer.avif", name: "Kırmızı Traverten 102" },
    { image: "./images/mermer.avif", name: "Blackberry 101" },
    { image: "./images/mermer.avif", name: "Blackberry Düz Kesim 101" },
    { image: "./images/mermer.avif", name: "Kırmızı Traverten 103" },
    { image: "./images/mermer.avif", name: "Kırmızı Traverten Düz Kesim 101" },
    { image: "./images/mermer.avif", name: "Kırmızı Traverten Düz Kesim 102" },
    { image: "./images/mermer.avif", name: "Cascade White 101" },
    { image: "./images/mermer.avif", name: "Cascade White Düz Kesim 101" },
    { image: "./images/mermer.avif", name: "Güneş Düz Kesim 101" },
    { image: "./images/mermer.avif", name: "Saffron 101" },
    { image: "./images/mermer.avif", name: "Saffron Düz Kesim 101" },
    { image: "./images/mermer.avif", name: "Bursa Bej 101" },
    { image: "./images/mermer.avif", name: "Epica Light 101" },
    { image: "./images/mermer.avif", name: "Epica Dark 101" },
    { image: "./images/mermer.avif", name: "Insula Alba 101" },
    { image: "./images/mermer.avif", name: "Verde Guatemala 102" },
    { image: "./images/mermer.avif", name: "Verde Escuro 101" },
    { image: "./images/mermer.avif", name: "Black Olive 101" },
    { image: "./images/mermer.avif", name: "Füme 101" },
    { image: "./images/mermer.avif", name: "Colorata 101" },
    { image: "./images/mermer.avif", name: "Light Emperador 101" },
    { image: "./images/mermer.avif", name: "Duru 101" },
  ],
  [
    { image: "./images/mermer.avif", name: "Pinguino 101" },
    { image: "./images/mermer.avif", name: "Black Orion 101" },
    { image: "./images/mermer.avif", name: "Black Aziza 101" },
    { image: "./images/mermer.avif", name: "Portoro 101" },
    { image: "./images/mermer.avif", name: "İspanyol Dark Emperador 101" },
    { image: "./images/mermer.avif", name: "Silver Dragon 101" },
    { image: "./images/mermer.avif", name: "Saint Laurent 101" },
    { image: "./images/mermer.avif", name: "Zebra Black 101" },
    { image: "./images/mermer.avif", name: "Mont Blanc 101" },
    { image: "./images/mermer.avif", name: "Metell 101" },
    { image: "./images/mermer.avif", name: "Metell Klasik 101" },
    { image: "./images/mermer.avif", name: "Ocean 101" },
    { image: "./images/mermer.avif", name: "Lilla 101" },
    { image: "./images/mermer.avif", name: "New York 101" },
    { image: "./images/mermer.avif", name: "Volakas 101" },
    { image: "./images/mermer.avif", name: "Calacatta 105" },
    { image: "./images/mermer.avif", name: "Carrara 101" },
    { image: "./images/mermer.avif", name: "Carrara Brezza 101" },
    { image: "./images/mermer.avif", name: "Madreperla 101" },
    { image: "./images/mermer.avif", name: "Polar White 101" },
    { image: "./images/mermer.avif", name: "Muğla Grili 101" },
    { image: "./images/mermer.avif", name: "Olea 101" },
    { image: "./images/mermer.avif", name: "Panda White 101" },
    { image: "./images/mermer.avif", name: "Panda White 103" },
  ],
  [
    { image: "./images/mermer.avif", name: "Ice Jade 101" },
    { image: "./images/mermer.avif", name: "Ice Jade 103" },
    { image: "./images/mermer.avif", name: "Ice Jade 104" },
    { image: "./images/mermer.avif", name: "Ice Jade 105" },
    { image: "./images/mermer.avif", name: "Desert Wave 101" },
    { image: "./images/mermer.avif", name: "S Black – Cilalı 101" },
    { image: "./images/mermer.avif", name: "S Black – Cilalı 102" },
    { image: "./images/mermer.avif", name: "S Black – Honlu 101" },
    { image: "./images/mermer.avif", name: "S Black – Honlu 102" },
    { image: "./images/mermer.avif", name: "S Black – Kumlama 101" },
    { image: "./images/mermer.avif", name: "S Black – Kumlama 102" },
    { image: "./images/mermer.avif", name: "S Black – Kumlama Fırçalı 101" },
    { image: "./images/mermer.avif", name: "S Black – Kumlama Fırçalı 102" },
    { image: "./images/mermer.avif", name: "Amazon 101" },
    { image: "./images/mermer.avif", name: "Rosa Beta 101" },
    { image: "./images/mermer.avif", name: "Rosa Minho 101" },
    { image: "./images/mermer.avif", name: "Glacier 101" },
    { image: "./images/mermer.avif", name: "Glacier White 101" },
    { image: "./images/mermer.avif", name: "Satin Oniks 101" },
    { image: "./images/mermer.avif", name: "Imperial Red 101" },
    { image: "./images/mermer.avif", name: "Magnifica 101" },
    { image: "./images/mermer.avif", name: "Magnifica Düz Kesim 101" },
    { image: "./images/mermer.avif", name: "Cappadoce Düz Kesim 101" },
    { image: "./images/mermer.avif", name: "Marmelade 101" },
  ],
  [
    { image: "./images/mermer.avif", name: "Violet 101" },
    { image: "./images/mermer.avif", name: "Medium Emperador 101" },
    { image: "./images/mermer.avif", name: "Zambak 101" },
    { image: "./images/mermer.avif", name: "Nigella 101" },
    { image: "./images/mermer.avif", name: "Nigella Rose 101" },
    { image: "./images/mermer.avif", name: "Pietra Grey 101" },
    { image: "./images/mermer.avif", name: "Rain Forest Brown 101" },
    { image: "./images/mermer.avif", name: "Rosa Porinho 101" },
    { image: "./images/mermer.avif", name: "Aksaray Yaylak 101" },
    { image: "./images/mermer.avif", name: "Salmon Oniks 101" },
    { image: "./images/mermer.avif", name: "Bellissima 101" },
    {
      image: "./images/mermer.avif",
      name: "Suni Taş – Bianco Bandia – Honlu 101",
    },
    {
      image: "./images/mermer.avif",
      name: "Suni Taş – Bianco Bandia – Eskitme 101",
    },
    {
      image: "./images/mermer.avif",
      name: "Suni Taş – Bianco Bandia – Kumlama 101",
    },
    { image: "./images/mermer.avif", name: "Tigrato 101" },
    { image: "./images/mermer.avif", name: "Crystal White 101" },
    { image: "./images/mermer.avif", name: "Armonia 101" },
    { image: "./images/mermer.avif", name: "Wooden Light 101" },
    { image: "./images/mermer.avif", name: "Beyaz Oniks 101" },
    { image: "./images/mermer.avif", name: "Dark Desert Rose 101" },
    { image: "./images/mermer.avif", name: "Light Desert Rose 101" },
  ],
];

export const plakalar = [
  [
    { image: "./images/mermer.avif", name: "Blue Ice Onyx 1001" },
    { image: "./images/mermer.avif", name: "Green Ice Onyx 1001" },
    { image: "./images/mermer.avif", name: "Pink Ice Onyx 1001" },
    { image: "./images/mermer.avif", name: "Amazonite 10001" },
    { image: "./images/mermer.avif", name: "Patagonia 10001" },
    { image: "./images/mermer.avif", name: "Azul Macoubas 10001" },
    { image: "./images/mermer.avif", name: "Desert Wave 1002" },
    { image: "./images/mermer.avif", name: "Panda Emerald Marble 1001" },
    { image: "./images/mermer.avif", name: "Rain Forest Brown 1003" },
    { image: "./images/mermer.avif", name: "Rain Forest Green 1001" },
    { image: "./images/mermer.avif", name: "Panda Azul 1001" },
    { image: "./images/mermer.avif", name: "Panda Azul 1002" },
    { image: "./images/mermer.avif", name: "Agate Blue 1001" },
    { image: "./images/mermer.avif", name: "Agate Green 1001" },
    { image: "./images/mermer.avif", name: "Agate Purple 1001" },
    { image: "./images/mermer.avif", name: "Grey Agate 1001" },
    { image: "./images/mermer.avif", name: "Petrified Wood 1001" },
    { image: "./images/mermer.avif", name: "Agate White 1001" },
    { image: "./images/mermer.avif", name: "Rosa Quartz 1001" },
    { image: "./images/mermer.avif", name: "Yellow Tiger Agate 1001" },
    { image: "./images/mermer.avif", name: "Round Agathe 1001" },
    { image: "./images/mermer.avif", name: "Dark Emperador 1002" },
    { image: "./images/mermer.avif", name: "Ice Jade 1010" },
    { image: "./images/mermer.avif", name: "Lilla 1005" },
  ],
  [
    { image: "./images/mermer.avif", name: "Magma Gold 1002" },
    { image: "./images/mermer.avif", name: "Petrified Wood Marble 1001" },
    { image: "./images/mermer.avif", name: "Black Aziza 1003" },
    { image: "./images/mermer.avif", name: "Green Oniks 1001" },
    { image: "./images/mermer.avif", name: "Nero Marquina 10001" },
    { image: "./images/mermer.avif", name: "Panda White 10001" },
    { image: "./images/mermer.avif", name: "Roma Black 101" },
    { image: "./images/mermer.avif", name: "Picasso 1002" },
    { image: "./images/mermer.avif", name: "Serpegiante Light 1002" },
    { image: "./images/mermer.avif", name: "Zebra Black 1003" },
    { image: "./images/mermer.avif", name: "Turtle 1002" },
    { image: "./images/mermer.avif", name: "Aqua Limo 101" },
    { image: "./images/mermer.avif", name: "Arabescato Gold 101" },
    { image: "./images/mermer.avif", name: "Salmon Oniks 1001" },
    { image: "./images/mermer.avif", name: "Black Marquina 101" },
    { image: "./images/mermer.avif", name: "Carrara 101" },
    { image: "./images/mermer.avif", name: "Diamond Gold 101" },
    { image: "./images/mermer.avif", name: "Pietra Grey 101" },
    { image: "./images/mermer.avif", name: "Salmon Oniks 1002" },
    { image: "./images/mermer.avif", name: "Tiger Oniks 1001" },
    { image: "./images/mermer.avif", name: "Tiger Oniks 1002" },
    { image: "./images/mermer.avif", name: "Wooden Oniks 1001" },
    { image: "./images/mermer.avif", name: "Travertino Grey 101" },
    { image: "./images/mermer.avif", name: "Volga Blue 101" },
  ],
  [
    { image: "./images/mermer.avif", name: "Wooden Oniks 1002" },
    { image: "./images/mermer.avif", name: "Beyaz Oniks 1001" },
    { image: "./images/mermer.avif", name: "Vivid White" },
    { image: "./images/mermer.avif", name: "Snow" },
    { image: "./images/mermer.avif", name: "White Shimmer" },
    { image: "./images/mermer.avif", name: "Frosty Carrina" },
    { image: "./images/mermer.avif", name: "Pure White" },
    { image: "./images/mermer.avif", name: "Nougat" },
    { image: "./images/mermer.avif", name: "Organic White" },
    { image: "./images/mermer.avif", name: "Ocean Foam" },
    { image: "./images/mermer.avif", name: "Intense White" },
    { image: "./images/mermer.avif", name: "London Grey" },
    { image: "./images/mermer.avif", name: "Empira White" },
    { image: "./images/mermer.avif", name: "White Attica" },
    { image: "./images/mermer.avif", name: "Ice Snow" },
    { image: "./images/mermer.avif", name: "Statuario Maximus" },
    { image: "./images/mermer.avif", name: "Cosmopolitan White" },
    { image: "./images/mermer.avif", name: "Calacatta Maximus" },
    { image: "./images/mermer.avif", name: "Cloudburst Concrete" },
    { image: "./images/mermer.avif", name: "Statuario Nuvo" },
    { image: "./images/mermer.avif", name: "Montblanc" },
    { image: "./images/mermer.avif", name: "Frozen Terra" },
    { image: "./images/mermer.avif", name: "Georgian Bluffs" },
    { image: "./images/mermer.avif", name: "Misty Carrera" },
  ],
  [
    { image: "./images/mermer.avif", name: "Nordic Loft" },
    { image: "./images/mermer.avif", name: "Alpine Mist" },
    { image: "./images/mermer.avif", name: "Dreamy Marfil" },
    { image: "./images/mermer.avif", name: "Clamshell" },
    { image: "./images/mermer.avif", name: "Calacatta Nuvo" },
    { image: "./images/mermer.avif", name: "Bianco Drift" },
    { image: "./images/mermer.avif", name: "Taj Royale" },
    { image: "./images/mermer.avif", name: "Buttermilk" },
    { image: "./images/mermer.avif", name: "Haze" },
    { image: "./images/mermer.avif", name: "Linen" },
    { image: "./images/mermer.avif", name: "Raw Concrete" },
    { image: "./images/mermer.avif", name: "Urban" },
    { image: "./images/mermer.avif", name: "Topus Concrete" },
    { image: "./images/mermer.avif", name: "Primordia" },
    { image: "./images/mermer.avif", name: "Symphony Grey" },
    { image: "./images/mermer.avif", name: "Airy Concrete" },
    { image: "./images/mermer.avif", name: "Noble Grey" },
    { image: "./images/mermer.avif", name: "Sleek Concrete" },
    { image: "./images/mermer.avif", name: "Shitake" },
    { image: "./images/mermer.avif", name: "Turbine Grey" },
    { image: "./images/mermer.avif", name: "Oyster" },
    { image: "./images/mermer.avif", name: "Atlantic Salt" },
    { image: "./images/mermer.avif", name: "Titan" },
    { image: "./images/mermer.avif", name: "Woodlands" },
  ],
  [
    { image: "./images/mermer.avif", name: "Oxidian" },
    { image: "./images/mermer.avif", name: "Fresh Concrete" },
    { image: "./images/mermer.avif", name: "Bianco Carrara 1" },
    { image: "./images/mermer.avif", name: "Concrete" },
    { image: "./images/mermer.avif", name: "Raven" },
    { image: "./images/mermer.avif", name: "Ginger" },
    { image: "./images/mermer.avif", name: "Lagos Blue" },
    { image: "./images/mermer.avif", name: "Excava" },
    { image: "./images/mermer.avif", name: "Rugged Concrete" },
    { image: "./images/mermer.avif", name: "Piatra Grey" },
    { image: "./images/mermer.avif", name: "Black Tempal" },
    { image: "./images/mermer.avif", name: "Vanilla Noir" },
    { image: "./images/mermer.avif", name: "Piatto Black" },
    { image: "./images/mermer.avif", name: "Black Noir" },
    { image: "./images/mermer.avif", name: "Calcatta Caldia 1" },
    { image: "./images/mermer.avif", name: "Jet Black" },
    { image: "./images/mermer.avif", name: "Pearl White 1" },
    { image: "./images/mermer.avif", name: "Sahara Noir 1" },
    { image: "./images/mermer.avif", name: "Serpegiante Light 10001" },
    { image: "./images/mermer.avif", name: "Azul Macaubas 1001" },
    { image: "./images/mermer.avif", name: "Azul Macaubas 1002" },
    { image: "./images/mermer.avif", name: "Black Leopar 1001" },
    { image: "./images/mermer.avif", name: "Panda White 1008" },
    { image: "./images/mermer.avif", name: "Serpegiante Light 1001" },
  ],
  [
    { image: "./images/mermer.avif", name: "Alps Blue 10001" },
    { image: "./images/mermer.avif", name: "Azul Macobus 10001" },
    { image: "./images/mermer.avif", name: "Van Gogh Blue 10001" },
    { image: "./images/mermer.avif", name: "Afyon White Spider 1001" },
    { image: "./images/mermer.avif", name: "Daisy" },
    { image: "./images/mermer.avif", name: "Aymina" },
    { image: "./images/mermer.avif", name: "Alaska" },
    { image: "./images/mermer.avif", name: "Bolera" },
    { image: "./images/mermer.avif", name: "Cordelia" },
    { image: "./images/mermer.avif", name: "Lusetia White" },
    { image: "./images/mermer.avif", name: "Sierra White" },
    { image: "./images/mermer.avif", name: "Mia" },
    { image: "./images/mermer.avif", name: "Aria" },
    { image: "./images/mermer.avif", name: "Rossa White" },
    { image: "./images/mermer.avif", name: "Visendra" },
    { image: "./images/mermer.avif", name: "Tornado" },
    { image: "./images/mermer.avif", name: "Admira" },
    { image: "./images/mermer.avif", name: "Lusida Grey" },
    { image: "./images/mermer.avif", name: "Olivia" },
    { image: "./images/mermer.avif", name: "Sima" },
    { image: "./images/mermer.avif", name: "Elatris" },
    { image: "./images/mermer.avif", name: "Caramela" },
    { image: "./images/mermer.avif", name: "Lusida Black" },
    { image: "./images/mermer.avif", name: "Rugiada" },
  ],
  [
    { image: "./images/mermer.avif", name: "Santa" },
    { image: "./images/mermer.avif", name: "Nidia" },
    { image: "./images/mermer.avif", name: "Sadira" },
    { image: "./images/mermer.avif", name: "Mirat" },
    { image: "./images/mermer.avif", name: "Hiearapolis" },
    { image: "./images/mermer.avif", name: "Arcadia" },
    { image: "./images/mermer.avif", name: "Artemis" },
    { image: "./images/mermer.avif", name: "Barents" },
    { image: "./images/mermer.avif", name: "Beach 1001" },
    { image: "./images/mermer.avif", name: "Lapland" },
    { image: "./images/mermer.avif", name: "Lilla 1002" },
    { image: "./images/mermer.avif", name: "Lilla 1003" },
    { image: "./images/mermer.avif", name: "Nebula" },
    { image: "./images/mermer.avif", name: "Nephila" },
    { image: "./images/mermer.avif", name: "Olympos" },
    { image: "./images/mermer.avif", name: "Sineda" },
    { image: "./images/mermer.avif", name: "Alpino" },
    { image: "./images/mermer.avif", name: "Tundra" },
    { image: "./images/mermer.avif", name: "Mora" },
    { image: "./images/mermer.avif", name: "Fuga" },
    { image: "./images/mermer.avif", name: "Versilia" },
    { image: "./images/mermer.avif", name: "Lebedos" },
    { image: "./images/mermer.avif", name: "Keops" },
    { image: "./images/mermer.avif", name: "Linen" },
  ],
  [
    { image: "./images/mermer.avif", name: "Terra" },
    { image: "./images/mermer.avif", name: "Smyrna" },
    { image: "./images/mermer.avif", name: "Lapaz" },
    { image: "./images/mermer.avif", name: "Troas" },
    { image: "./images/mermer.avif", name: "Etna" },
    { image: "./images/mermer.avif", name: "Ares" },
    { image: "./images/mermer.avif", name: "Boreas" },
    { image: "./images/mermer.avif", name: "Elvas" },
    { image: "./images/mermer.avif", name: "Kromit" },
    { image: "./images/mermer.avif", name: "Savana" },
    { image: "./images/mermer.avif", name: "Gharma" },
    { image: "./images/mermer.avif", name: "Toros" },
    { image: "./images/mermer.avif", name: "Carbone" },
    { image: "./images/mermer.avif", name: "Hermes" },
    { image: "./images/mermer.avif", name: "Armani Grey 10001" },
    { image: "./images/mermer.avif", name: "Calacatta Victory" },
    { image: "./images/mermer.avif", name: "Carrara 10001" },
    { image: "./images/mermer.avif", name: "Carrara Ultimo 10001" },
    { image: "./images/mermer.avif", name: "Invisible White 10001" },
    { image: "./images/mermer.avif", name: "Felisia" },
    { image: "./images/mermer.avif", name: "Macchia 10001" },
    { image: "./images/mermer.avif", name: "Marquina Venato 10001" },
    { image: "./images/mermer.avif", name: "Modern Statuario 10001" },
    { image: "./images/mermer.avif", name: "Pantheon" },
  ],
  [
    { image: "./images/mermer.avif", name: "Pietra Grey 10001" },
    { image: "./images/mermer.avif", name: "Rome 10001" },
    { image: "./images/mermer.avif", name: "Sahara Noir 10001" },
    { image: "./images/mermer.avif", name: "Statuario Elite 10001" },
    { image: "./images/mermer.avif", name: "Polaris" },
    { image: "./images/mermer.avif", name: "Anemon" },
    { image: "./images/mermer.avif", name: "Alinda" },
    { image: "./images/mermer.avif", name: "Kristella White" },
    { image: "./images/mermer.avif", name: "Sahara Beige" },
    { image: "./images/mermer.avif", name: "Montana" },
    { image: "./images/mermer.avif", name: "Aizano" },
    { image: "./images/mermer.avif", name: "Retro" },
    { image: "./images/mermer.avif", name: "Metropol Grey" },
    { image: "./images/mermer.avif", name: "Gala Black" },
    { image: "./images/mermer.avif", name: "Aspendos" },
    { image: "./images/mermer.avif", name: "Aurora" },
    { image: "./images/mermer.avif", name: "Belluno" },
    { image: "./images/mermer.avif", name: "Calacatta Veneto" },
    { image: "./images/mermer.avif", name: "Calacatta Verona" },
    { image: "./images/mermer.avif", name: "Carola" },
    { image: "./images/mermer.avif", name: "Teos" },
    { image: "./images/mermer.avif", name: "Daphne Crack" },
    { image: "./images/mermer.avif", name: "Elixir White" },
    { image: "./images/mermer.avif", name: "Fairy White" },
  ],
  [
    { image: "./images/mermer.avif", name: "Perla" },
    { image: "./images/mermer.avif", name: "Iceberg" },
    { image: "./images/mermer.avif", name: "Juliet White" },
    { image: "./images/mermer.avif", name: "Kashmera White" },
    { image: "./images/mermer.avif", name: "La Luna" },
    { image: "./images/mermer.avif", name: "Pixie Wings" },
    { image: "./images/mermer.avif", name: "Olympos" },
    { image: "./images/mermer.avif", name: "Mocca Mousse" },
    { image: "./images/mermer.avif", name: "Parma" },
    { image: "./images/mermer.avif", name: "Chakra" },
    { image: "./images/mermer.avif", name: "Boletus" },
    { image: "./images/mermer.avif", name: "Terre Grey" },
    { image: "./images/mermer.avif", name: "Babilon" },
    { image: "./images/mermer.avif", name: "Charmy" },
    { image: "./images/mermer.avif", name: "Forza Füme" },
    { image: "./images/mermer.avif", name: "Marquina Tierra" },
    { image: "./images/mermer.avif", name: "Spa Black" },
    { image: "./images/mermer.avif", name: "Volcano Black" },
    { image: "./images/mermer.avif", name: "Bardiglio Black 1001" },
    { image: "./images/mermer.avif", name: "Botticino 1001" },
    { image: "./images/mermer.avif", name: "Pinguino 1011" },
    { image: "./images/mermer.avif", name: "Panda White 1006" },
    { image: "./images/mermer.avif", name: "Panda White 1007" },
    { image: "./images/mermer.avif", name: "Emerald 1001" },
  ],
  [
    { image: "./images/mermer.avif", name: "Emerald 1002" },
    { image: "./images/mermer.avif", name: "Emerald 1003" },
    { image: "./images/mermer.avif", name: "Emerald 1004" },
    { image: "./images/mermer.avif", name: "Picasso 1001" },
    { image: "./images/mermer.avif", name: "Panda White 1005" },
    { image: "./images/mermer.avif", name: "Serpegiante 1001" },
    { image: "./images/mermer.avif", name: "Beyaz Oniks 1002" },
    { image: "./images/mermer.avif", name: "Beyaz Oniks 1003" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Mermer Oniks 1001" },
    { image: "./images/mermer.avif", name: "Marmara Beyaz Mermer 1001" },
    { image: "./images/mermer.avif", name: "Zebra White 1001" },
    { image: "./images/mermer.avif", name: "Blue Rain 1001" },
    { image: "./images/mermer.avif", name: "Hills 1001" },
    { image: "./images/mermer.avif", name: "Bruno 1001" },
    { image: "./images/mermer.avif", name: "Fusion 1001" },
    { image: "./images/mermer.avif", name: "Emerald 1004" },
    { image: "./images/mermer.avif", name: "Rain Forest Brown 1002" },
    { image: "./images/mermer.avif", name: "Statuario 1001" },
    { image: "./images/mermer.avif", name: "Nero 1001" },
    { image: "./images/mermer.avif", name: "Zebra Black 1002" },
    { image: "./images/mermer.avif", name: "Turtle 1001" },
    { image: "./images/mermer.avif", name: "Pedras Granit – Cilalı 101" },
    { image: "./images/mermer.avif", name: "Pedras Granit – Kumlama 102" },
    { image: "./images/mermer.avif", name: "Calacatta Oro 1001" },
  ],
  [
    { image: "./images/mermer.avif", name: "Zebra Grey 1001" },
    { image: "./images/mermer.avif", name: "Bal Oniks 1001" },
    { image: "./images/mermer.avif", name: "Bal Oniks 1002" },
    { image: "./images/mermer.avif", name: "Bal Oniks 1003" },
    { image: "./images/mermer.avif", name: "Bal Oniks 1004" },
    { image: "./images/mermer.avif", name: "Botticino 1002" },
    { image: "./images/mermer.avif", name: "Coquillage 1001" },
    { image: "./images/mermer.avif", name: "Bianco Crema 1001" },
    { image: "./images/mermer.avif", name: "Carrara Arabescato 1001" },
    { image: "./images/mermer.avif", name: "Bubble Oniks 1001" },
    { image: "./images/mermer.avif", name: "Cappuccino Oniks 1001" },
    { image: "./images/mermer.avif", name: "Velluto Oniks 1001" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Arcobaleno 1001" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1001" },
    { image: "./images/mermer.avif", name: "Sperenza 1001" },
    { image: "./images/mermer.avif", name: "Gümüş Oniks 1001" },
    { image: "./images/mermer.avif", name: "Gümüş Traverten 1001" },
    { image: "./images/mermer.avif", name: "Gümüş Traverten Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Verde Guatemala 1001" },
    { image: "./images/mermer.avif", name: "Verde Forest 1001" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1001" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 1001" },
    { image: "./images/mermer.avif", name: "Rosalia 1001" },
    { image: "./images/mermer.avif", name: "Rosalia Light 1001" },
  ],
  [
    { image: "./images/mermer.avif", name: "Light Emperador Klasik 1001" },
    { image: "./images/mermer.avif", name: "Pedras Granit – Kumlama 103" },
    { image: "./images/mermer.avif", name: "White Walker 101" },
    { image: "./images/mermer.avif", name: "White Walker – Küp Taşlar 101" },
    { image: "./images/mermer.avif", name: "White Walker – Küp Taşlar 102" },
    { image: "./images/mermer.avif", name: "White Walker – Küp Taşlar 103" },
    { image: "./images/mermer.avif", name: "Desert Black 101" },
    { image: "./images/mermer.avif", name: "Absolute Black 101" },
    { image: "./images/mermer.avif", name: "Star Galaxy 101" },
    { image: "./images/mermer.avif", name: "Paradiso 101" },
    { image: "./images/mermer.avif", name: "P White 101" },
    { image: "./images/mermer.avif", name: "Nero Marquina 1001" },
    { image: "./images/mermer.avif", name: "Nebel 1001" },
    { image: "./images/mermer.avif", name: "Blue Moon 1002" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Arcobaleno 1002" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Arcobaleno 1003" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Arcobaleno 1004" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Arcobaleno 1005" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Arcobaleno 1006" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Arcobaleno 1007" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Golden Gray 1001" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Golden Gray 1002" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Golden Gray 1003" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Golden Gray 1004" },
  ],
  [
    { image: "./images/mermer.avif", name: "Afyon Beyaz Golden Gray 1005" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Golden Gray 1006" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz A La Vogue 1001" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz A La Vogue 1002" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz A La Vogue 1003" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz A La Vogue 1004" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1001" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1002" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1003" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1004" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1005" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1006" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1007" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1008" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Billur 1009" },
    { image: "./images/mermer.avif", name: "Afyon Şeker 1001" },
    { image: "./images/mermer.avif", name: "Afyon Şeker 1002" },
    { image: "./images/mermer.avif", name: "Afyon Şeker 1003" },
    { image: "./images/mermer.avif", name: "Afyon Şeker 1004" },
    { image: "./images/mermer.avif", name: "Afyon Şeker 1005" },
    { image: "./images/mermer.avif", name: "Afyon Şeker 1006" },
    { image: "./images/mermer.avif", name: "Calacatta 1001" },
    { image: "./images/mermer.avif", name: "Calacatta 1002" },
    { image: "./images/mermer.avif", name: "Calacatta 1003" },
  ],
  [
    { image: "./images/mermer.avif", name: "Calacatta 1004" },
    { image: "./images/mermer.avif", name: "Calacatta 1005" },
    { image: "./images/mermer.avif", name: "Calacatta 1006" },
    { image: "./images/mermer.avif", name: "Calacatta 1007" },
    { image: "./images/mermer.avif", name: "Calacatta 1008" },
    { image: "./images/mermer.avif", name: "Calacatta 1009" },
    { image: "./images/mermer.avif", name: "Calacatta 1010" },
    { image: "./images/mermer.avif", name: "Calacatta 1011" },
    { image: "./images/mermer.avif", name: "Calacatta 1012" },
    { image: "./images/mermer.avif", name: "Calacatta 1013" },
    { image: "./images/mermer.avif", name: "Calacatta 1014" },
    { image: "./images/mermer.avif", name: "Calacatta 1015" },
    { image: "./images/mermer.avif", name: "Calacatta 1016" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1001" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1002" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1003" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1004" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1005" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1006" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1007" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1008" },
    { image: "./images/mermer.avif", name: "Nuage Miel 1009" },
    { image: "./images/mermer.avif", name: "Nuage Doré 1001" },
    { image: "./images/mermer.avif", name: "Ice Jade 10001" },
  ],
  [
    { image: "./images/mermer.avif", name: "Ice Jade 10002" },
    { image: "./images/mermer.avif", name: "Ice Jade 10003" },
    { image: "./images/mermer.avif", name: "Silk White 10001" },
    { image: "./images/mermer.avif", name: "Glacier White 10001" },
    { image: "./images/mermer.avif", name: "Pure White 10001" },
    { image: "./images/mermer.avif", name: "Ivory Travertine Porcelain 10001" },
    { image: "./images/mermer.avif", name: "Calacatta 10001" },
    { image: "./images/mermer.avif", name: "Crema Bella 1001" },
    { image: "./images/mermer.avif", name: "Botanica 1001" },
    { image: "./images/mermer.avif", name: "Luna Piera 1001" },
    { image: "./images/mermer.avif", name: "Limpido 1001" },
    { image: "./images/mermer.avif", name: "Dark Emperador 1001" },
    { image: "./images/mermer.avif", name: "Dark Emperador Klasik 1001" },
    { image: "./images/mermer.avif", name: "Dune 1001" },
    { image: "./images/mermer.avif", name: "Luna 1001" },
    { image: "./images/mermer.avif", name: "Light Emperador 1001" },
    { image: "./images/mermer.avif", name: "Emperador Perla 1001" },
    { image: "./images/mermer.avif", name: "Emperador Perla Klasik 1001" },
    { image: "./images/mermer.avif", name: "Mondo-1001" },
    { image: "./images/mermer.avif", name: "Brume 1001" },
    { image: "./images/mermer.avif", name: "Avorio 1001" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1002" },
    { image: "./images/mermer.avif", name: "Crema Foret 1001" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1003" },
  ],
  [
    { image: "./images/mermer.avif", name: "Colorata 1001" },
    { image: "./images/mermer.avif", name: "Duru 1001" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1004" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1005" },
    { image: "./images/mermer.avif", name: "Burdur Bej 1001" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1006" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1007" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1008" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1009" },
    { image: "./images/mermer.avif", name: "Bardiglio Blu 1010" },
    { image: "./images/mermer.avif", name: "Blue Bahia 1001" },
    { image: "./images/mermer.avif", name: "Blue Bahia 1002" },
    { image: "./images/mermer.avif", name: "Blue Moon 1001" },
    { image: "./images/mermer.avif", name: "Blue Moon 1003" },
    { image: "./images/mermer.avif", name: "Blue Moon 1004" },
    { image: "./images/mermer.avif", name: "Blue Moon 1005" },
    { image: "./images/mermer.avif", name: "Blue Moon 1006" },
    { image: "./images/mermer.avif", name: "Blue Moon 1007" },
    { image: "./images/mermer.avif", name: "Blue Stone 1001" },
    { image: "./images/mermer.avif", name: "Blue Stone 1002" },
    { image: "./images/mermer.avif", name: "Blue Stone 1003" },
    { image: "./images/mermer.avif", name: "Blue Moon Gold 1001" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Marine Blue 1001" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Marine Blue 1002" },
  ],
  [
    { image: "./images/mermer.avif", name: "Afyon Beyaz Marine Blue 1003" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Marine Blue 1004" },
    { image: "./images/mermer.avif", name: "Gümüş Oniks 1002" },
    { image: "./images/mermer.avif", name: "Gold Oniks 1001" },
    { image: "./images/mermer.avif", name: "Gold Oniks 1002" },
    { image: "./images/mermer.avif", name: "Cocacola Oniks 1001" },
    { image: "./images/mermer.avif", name: "Cocacola Oniks 1002" },
    { image: "./images/mermer.avif", name: "Satin Oniks 1001" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Marine Blue 1005" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Marine Blue 1006" },
    { image: "./images/mermer.avif", name: "Afyon Beyaz Marine Blue 1007" },
    { image: "./images/mermer.avif", name: "River 1001" },
    { image: "./images/mermer.avif", name: "Beyaz Traverten 1001" },
    { image: "./images/mermer.avif", name: "Epica 1001" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1002" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1003" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1004" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1005" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1006" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1007" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1008" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1009" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1010" },
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1011" },
  ],
  [
    { image: "./images/mermer.avif", name: "Elazığ Vişne 1012" },
    { image: "./images/mermer.avif", name: "Pinguino 1010" },
    { image: "./images/mermer.avif", name: "Verde Escuro 1001" },
    { image: "./images/mermer.avif", name: "Klasik Traverten 1001" },
    { image: "./images/mermer.avif", name: "Beyaz Traverten Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Klasik Traverten Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Golden Crema 1001" },
    { image: "./images/mermer.avif", name: "Black Olive 1001" },
    { image: "./images/mermer.avif", name: "Black Olive 1002" },
    { image: "./images/mermer.avif", name: "Black Olive 1003" },
    { image: "./images/mermer.avif", name: "Black Olive 1004" },
    { image: "./images/mermer.avif", name: "Black Olive 1005" },
    { image: "./images/mermer.avif", name: "Black Olive 1006" },
    { image: "./images/mermer.avif", name: "Black Olive 1007" },
    { image: "./images/mermer.avif", name: "Black Olive 1008" },
    { image: "./images/mermer.avif", name: "Black Olive 1009" },
    { image: "./images/mermer.avif", name: "Black Olive 1010" },
    { image: "./images/mermer.avif", name: "Black Olive 1011" },
    { image: "./images/mermer.avif", name: "Füme 1001" },
    { image: "./images/mermer.avif", name: "Füme 1002" },
    { image: "./images/mermer.avif", name: "Füme 1003" },
    { image: "./images/mermer.avif", name: "Füme 1004" },
    { image: "./images/mermer.avif", name: "Füme 1005" },
    { image: "./images/mermer.avif", name: "Füme 1006" },
  ],
  [
    { image: "./images/mermer.avif", name: "Iris 1001" },
    { image: "./images/mermer.avif", name: "Iris 1002" },
    { image: "./images/mermer.avif", name: "Iris 1003" },
    { image: "./images/mermer.avif", name: "Iris 1004" },
    { image: "./images/mermer.avif", name: "Iris 1005" },
    { image: "./images/mermer.avif", name: "Iris 1006" },
    { image: "./images/mermer.avif", name: "Iris 1007" },
    { image: "./images/mermer.avif", name: "Iris 1008" },
    { image: "./images/mermer.avif", name: "Nebel 1002" },
    { image: "./images/mermer.avif", name: "Nebel 1003" },
    { image: "./images/mermer.avif", name: "Nebel 1004" },
    { image: "./images/mermer.avif", name: "Nebel 1005" },
    { image: "./images/mermer.avif", name: "Nebel 1006" },
    { image: "./images/mermer.avif", name: "Nebel 1007" },
    { image: "./images/mermer.avif", name: "Nebel 1008" },
    { image: "./images/mermer.avif", name: "Pinguino 1001" },
    { image: "./images/mermer.avif", name: "Pinguino 1002" },
    { image: "./images/mermer.avif", name: "Pinguino 1003" },
    { image: "./images/mermer.avif", name: "Pinguino 1004" },
    { image: "./images/mermer.avif", name: "Pinguino 1005" },
    { image: "./images/mermer.avif", name: "Pinguino 1006" },
    { image: "./images/mermer.avif", name: "Pinguino 1007" },
    { image: "./images/mermer.avif", name: "Pinguino 1008" },
    { image: "./images/mermer.avif", name: "Pinguino 1009" },
  ],
  [
    { image: "./images/mermer.avif", name: "Black Orion 1001" },
    { image: "./images/mermer.avif", name: "Black Aziza 1001" },
    { image: "./images/mermer.avif", name: "Black Aziza 1002" },
    { image: "./images/mermer.avif", name: "Black Pearl 1001" },
    { image: "./images/mermer.avif", name: "Portoro 1001" },
    { image: "./images/mermer.avif", name: "İspanyol Dark Emperador 1001" },
    { image: "./images/mermer.avif", name: "Silver Dragon 1001" },
    { image: "./images/mermer.avif", name: "Saint Laurent 1001" },
    { image: "./images/mermer.avif", name: "Zebra Black 1001" },
    { image: "./images/mermer.avif", name: "Zebra Black 1004" },
    { image: "./images/mermer.avif", name: "Ice Jade 1001" },
    { image: "./images/mermer.avif", name: "Ice Jade 1002" },
    { image: "./images/mermer.avif", name: "Ice Jade 1003" },
    { image: "./images/mermer.avif", name: "Ice Jade 1004" },
    { image: "./images/mermer.avif", name: "Ice Jade 1005" },
    { image: "./images/mermer.avif", name: "Ice Jade 1006" },
    { image: "./images/mermer.avif", name: "Ice Jade 1007" },
    { image: "./images/mermer.avif", name: "Ice Jade 1008" },
    { image: "./images/mermer.avif", name: "Ice Jade 1009" },
    { image: "./images/mermer.avif", name: "Mont Blanc 1001" },
    { image: "./images/mermer.avif", name: "Mont Blanc 1002" },
    { image: "./images/mermer.avif", name: "Mont Blanc 1003" },
    { image: "./images/mermer.avif", name: "Mont Blanc 1004" },
    { image: "./images/mermer.avif", name: "Metell 1001" },
  ],
  [
    { image: "./images/mermer.avif", name: "Metell Klasik 1001" },
    { image: "./images/mermer.avif", name: "Ocean 1001" },
    { image: "./images/mermer.avif", name: "Ocean 1002" },
    { image: "./images/mermer.avif", name: "Lilla 1001" },
    { image: "./images/mermer.avif", name: "Lilla 1004" },
    { image: "./images/mermer.avif", name: "New York 1001" },
    { image: "./images/mermer.avif", name: "Volakas 1001" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 1002" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 1003" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 1004" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 1005" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 1006" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 1007" },
    { image: "./images/mermer.avif", name: "Volakas Bianco 1008" },
    { image: "./images/mermer.avif", name: "Carrara 1001" },
    { image: "./images/mermer.avif", name: "Carrara Brezza 1001" },
    { image: "./images/mermer.avif", name: "Carrara Brezza 1002" },
    { image: "./images/mermer.avif", name: "Carrara Brezza 1003" },
    { image: "./images/mermer.avif", name: "Carrara Brezza 1004" },
    { image: "./images/mermer.avif", name: "Madreperla 1001" },
    { image: "./images/mermer.avif", name: "Madreperla Klasik 1001" },
    { image: "./images/mermer.avif", name: "Polar White 1001" },
    { image: "./images/mermer.avif", name: "Polar White 1002" },
    { image: "./images/mermer.avif", name: "Polar White 1003" },
  ],
  [
    { image: "./images/mermer.avif", name: "Polar White 1004" },
    { image: "./images/mermer.avif", name: "Polar White 1005" },
    { image: "./images/mermer.avif", name: "Polar White 1006" },
    { image: "./images/mermer.avif", name: "Polar White 1007" },
    { image: "./images/mermer.avif", name: "Polar White 1008" },
    { image: "./images/mermer.avif", name: "Muğla Grili 1001" },
    { image: "./images/mermer.avif", name: "Olea 1001" },
    { image: "./images/mermer.avif", name: "Panda White 1001" },
    { image: "./images/mermer.avif", name: "Panda White 1002" },
    { image: "./images/mermer.avif", name: "Panda White 1003" },
    { image: "./images/mermer.avif", name: "Panda White 1004" },
    { image: "./images/mermer.avif", name: "Blackberry 1001" },
    { image: "./images/mermer.avif", name: "Blackberry Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Desert Wave 1001" },
    { image: "./images/mermer.avif", name: "Marmelade 1001" },
    { image: "./images/mermer.avif", name: "Violet 1001" },
    { image: "./images/mermer.avif", name: "Zambak 1001" },
    { image: "./images/mermer.avif", name: "Zambak 1002" },
    { image: "./images/mermer.avif", name: "Zambak 1003" },
    { image: "./images/mermer.avif", name: "Rain Forest Brown 1001" },
    { image: "./images/mermer.avif", name: "Bellissima 1001" },
    { image: "./images/mermer.avif", name: "Bellissima 1002" },
    { image: "./images/mermer.avif", name: "Bellissima 1003" },
    { image: "./images/mermer.avif", name: "Tigrato 1001" },
  ],
  [
    { image: "./images/mermer.avif", name: "Calimero 1001" },
    { image: "./images/mermer.avif", name: "Cappadoce Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Cashmere 1001" },
    { image: "./images/mermer.avif", name: "Kırmızı Traverten 1001" },
    { image: "./images/mermer.avif", name: "Kırmızı Traverten Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Saffron Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Crystal White 1001" },
    { image: "./images/mermer.avif", name: "Wooden Light 1001" },
    { image: "./images/mermer.avif", name: "Beyaz Mermer 101" },
    { image: "./images/mermer.avif", name: "Dark Desert Rose 1001" },
    { image: "./images/mermer.avif", name: "S Black – Cilalı 101" },
    { image: "./images/mermer.avif", name: "S Black – Cilalı 102" },
    { image: "./images/mermer.avif", name: "S Black – Honlu 101" },
    { image: "./images/mermer.avif", name: "S Black – Honlu 102" },
    { image: "./images/mermer.avif", name: "S Black – Kumlama 101" },
    { image: "./images/mermer.avif", name: "S Black – Kumlama 102" },
    { image: "./images/mermer.avif", name: "S Black – Kumlama Fırçalı 101" },
    { image: "./images/mermer.avif", name: "S Black – Kumlama Fırçalı 102" },
    { image: "./images/mermer.avif", name: "Amazon 101" },
    { image: "./images/mermer.avif", name: "Rosa Beta 101" },
    { image: "./images/mermer.avif", name: "Rosa Minho 101" },
    { image: "./images/mermer.avif", name: "Gargamel 1001" },
    { image: "./images/mermer.avif", name: "Güneş Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Warm Walnut 1001" },
  ],
  [
    { image: "./images/mermer.avif", name: "Warm Walnut Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Noce Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Imperial Red 101" },
    { image: "./images/mermer.avif", name: "Light Desert Rose 1001" },
    { image: "./images/mermer.avif", name: "Light Desert Rose 1002" },
    { image: "./images/mermer.avif", name: "Magnifica Düz Kesim 1001" },
    { image: "./images/mermer.avif", name: "Blue Moon Mavi Mermer" },
    { image: "./images/mermer.avif", name: "Nigella 1001" },
    { image: "./images/mermer.avif", name: "Pietra Gray 1001" },
    { image: "./images/mermer.avif", name: "Rosa Porinho 101" },
    { image: "./images/mermer.avif", name: "Aksaray Yaylak 101" },
    { image: "./images/mermer.avif", name: "Siyah Mermer Plakalar" },
    { image: "./images/mermer.avif", name: "Sunny 1001" },
    { image: "./images/mermer.avif", name: "Sunny Light 1001" },
    { image: "./images/mermer.avif", name: "Suni Taş – Bianco Bandia 1001" },
    { image: "./images/mermer.avif", name: "Yeşil Mermer Plakalar" },
  ],
];

export const urunler = [
  [
    { image: "", name: "B – 1" },
    { image: "", name: "B – 2" },
    { image: "", name: "B – 3" },
    { image: "", name: "B – 4" },
    { image: "", name: "B – 5" },
    { image: "", name: "B – 6" },
    { image: "", name: "B – 7" },
    { image: "", name: "B – 8" },
    { image: "", name: "B – 9" },
    { image: "", name: "B – 10" },
    { image: "", name: "B – 11" },
    { image: "", name: "B – 12" },
    { image: "", name: "B – 13" },
    { image: "", name: "Masa Referans 1001" },
    { image: "", name: "Masa Referans 1002" },
    { image: "", name: "Masa Referans 1003" },
    { image: "", name: "Masa Referans 1004" },
    { image: "", name: "Masa Referans 1005" },
    { image: "", name: "Masa Referans 1006" },
    { image: "", name: "Masa Referans 1007" },
    { image: "", name: "Masa Referans 1008" },
    { image: "", name: "Masa Referans 1009" },
    { image: "", name: "Masa Referans 1010" },
    { image: "", name: "Masa Referans 1011" },
  ],
  [
    { image: "", name: "Masa Referans 1012" },
    { image: "", name: "Masa Referans 1013" },
    { image: "", name: "Masa Referans 1014" },
    { image: "", name: "Masa Referans 1015" },
    { image: "", name: "Masa Referans 1016" },
    { image: "", name: "Masa Referans 1017" },
    { image: "", name: "Masa Referans 1018" },
    { image: "", name: "Masa Referans 1019" },
    { image: "", name: "Sehpa Referans 1001" },
    { image: "", name: "Sehpa Referans 1002" },
    { image: "", name: "Sehpa Referans 1003" },
    { image: "", name: "Sehpa Referans 1004" },
    { image: "", name: "Sehpa Referans 1005" },
    { image: "", name: "Sehpa Referans 1006" },
    { image: "", name: "Sehpa Referans 1007" },
    { image: "", name: "Sehpa Referans 1008" },
    { image: "", name: "Sehpa Referans 1009" },
    { image: "", name: "Sehpa Referans 1010" },
    { image: "", name: "Sehpa Referans 1011" },
    { image: "", name: "Sehpa Referans 1012" },
    { image: "", name: "Sehpa Referans 1013" },
    { image: "", name: "Sehpa Referans 1014" },
    { image: "", name: "Sehpa Referans 1015" },
    { image: "", name: "Sehpa Referans 1016" },
    { image: "", name: "Sehpa Referans 1017" },
  ],
  [
    { image: "", name: "Sehpa Referans 1018" },
    { image: "", name: "Sehpa Referans 1019" },
    { image: "", name: "Sehpa Referans 1020" },
    { image: "", name: "Sehpa Referans 1021" },
    { image: "", name: "Sehpa Referans 1022" },
    { image: "", name: "Sehpa Referans 1023" },
    { image: "", name: "Sehpa Referans 1024" },
    { image: "", name: "Sehpa Referans 1025" },
    { image: "", name: "Sehpa Referans 1026" },
    { image: "", name: "Sehpa Referans 1027" },
    { image: "", name: "Sehpa Referans 1028" },
    { image: "", name: "Sehpa Referans 1029" },
    { image: "", name: "Sehpa Referans 1030" },
    { image: "", name: "Sehpa Referans 1031" },
    { image: "", name: "Sehpa Referans 1032" },
    { image: "", name: "Sehpa Referans 1033" },
    { image: "", name: "Sehpa Referans 1034" },
    { image: "", name: "Sehpa Referans 1035" },
    { image: "", name: "Sehpa Referans 1036" },
    { image: "", name: "Sehpa Referans 1037" },
    { image: "", name: "Sehpa Referans 1038" },
    { image: "", name: "Sehpa Referans 1039" },
    { image: "", name: "Sehpa Referans 1040" },
    { image: "", name: "Sehpa Referans 1041" },
  ],
  [
    { image: "", name: "H -1" },
    { image: "", name: "H -5" },
    { image: "", name: "H -11" },
    { image: "", name: "Waterjet Madalyon 1" },
    { image: "", name: "Waterjet Madalyon 2" },
    { image: "", name: "Waterjet Madalyon 3" },
    { image: "", name: "Waterjet Madalyon 4" },
    { image: "", name: "Waterjet Madalyon 5" },
    { image: "", name: "Waterjet Madalyon 6" },
    { image: "", name: "Waterjet Madalyon 7" },
    { image: "", name: "Waterjet Madalyon 8" },
    { image: "", name: "Waterjet Madalyon 9" },
    { image: "", name: "Waterjet Madalyon 10" },
    { image: "", name: "Waterjet Madalyon 11" },
    { image: "", name: "Waterjet Madalyon 12" },
    { image: "", name: "Waterjet Madalyon 13" },
    { image: "", name: "Waterjet Madalyon 14" },
    { image: "", name: "Kenar Detayları 1001" },
    { image: "", name: "Kenar Detayları 1002" },
    { image: "", name: "Kenar Detayları 1003" },
    { image: "", name: "Kenar Detayları 1004" },
    { image: "", name: "Kenar Detayları 1005" },
    { image: "", name: "Kenar Detayları 1006" },
    { image: "", name: "Kenar Detayları 1007" },
  ],
  [
    { image: "", name: "Kenar Detayları 1008" },
    { image: "", name: "Kenar Detayları 1008-1" },
    { image: "", name: "Kenar Detayları 1009" },
    { image: "", name: "Kenar Detayları 1011" },
    { image: "", name: "Kenar Detayları 1012" },
    { image: "", name: "Kenar Detayları 1013" },
    { image: "", name: "Kenar Detayları 1014" },
    { image: "", name: "Kenar Detayları 1015" },
    { image: "", name: "Kenar Detayları 1016" },
    { image: "", name: "Kenar Detayları 1017" },
    { image: "", name: "Kenar Detayları 1018" },
    { image: "", name: "Kenar Detayları 1019" },
    { image: "", name: "Kenar Detayları 1020" },
    { image: "", name: "Kenar Detayları 1021" },
    { image: "", name: "Kenar Detayları 1022" },
    { image: "", name: "Kenar Detayları 1023" },
    { image: "", name: "Kenar Detayları 1024" },
    { image: "", name: "Kenar Detayları 1025" },
    { image: "", name: "Kenar Detayları 1026" },
    { image: "", name: "Kenar Detayları 1027" },
    { image: "", name: "Kenar Detayları 1028" },
    { image: "", name: "Kenar Detayları 1029" },
    { image: "", name: "Kenar Detayları 1030" },
    { image: "", name: "Kenar Detayları 1031" },
  ],
  [
    { image: "", name: "Kenar Detayları 1032" },
    { image: "", name: "Kenar Detayları 1033" },
    { image: "", name: "Kenar Detayları 1034" },
    { image: "", name: "Kenar Detayları 1035" },
    { image: "", name: "Kenar Detayları 1036" },
    { image: "", name: "Kenar Detayları 1037" },
    { image: "", name: "Kenar Detayları 1038" },
    { image: "", name: "Kenar Detayları 1039" },
    { image: "", name: "Kenar Detayları 1040" },
    { image: "", name: "Duş Teknesi – Referans" },
    { image: "", name: "Kolon – Referans 1001" },
    { image: "", name: "Kolon – Referans 1002" },
    { image: "", name: "Kolon – Referans 1003" },
    { image: "", name: "Kolon – Referans 1004" },
    { image: "", name: "Kolon – Referans 1005" },
    { image: "", name: "Kolon – Referans 1006" },
    { image: "", name: "Kolon – Referans 1007" },
    { image: "", name: "Kolon – Referans 1008" },
    { image: "", name: "Duvar Dekorasyonları – Referans 1001" },
    { image: "", name: "Duvar Dekorasyonları – Referans 1002" },
    { image: "", name: "Duvar Dekorasyonları – Referans 1003" },
    { image: "", name: "Duvar Dekorasyonları – Referans 1004" },
    { image: "", name: "Duvar Dekorasyonları – Referans 1005" },
    { image: "", name: "Duvar Dekorasyonları – Referans 1006" },
  ],
  [
    { image: "", name: "Duvar Dekorasyonları – Referans 1007" },
    { image: "", name: "Mozaik – Referans 1001" },
    { image: "", name: "Mozaik – Referans 1002" },
    { image: "", name: "Mozaik – Referans 1003" },
    { image: "", name: "Mozaik – Referans 1004" },
    { image: "", name: "Mozaik – Referans 1005" },
    { image: "", name: "Mozaik – Referans 1006" },
    { image: "", name: "Mozaik – Referans 1007" },
    { image: "", name: "Mozaik – Referans 1008" },
    { image: "", name: "Mozaik – Referans 1009" },
    { image: "", name: "Mozaik – Referans 1010" },
    { image: "", name: "Mozaik – Referans 1011" },
    { image: "", name: "Mozaik – Referans 1012" },
    { image: "", name: "Mozaik – Referans 1013" },
    { image: "", name: "Mozaik – Referans 1014" },
    { image: "", name: "Mozaik – Referans 1015" },
    { image: "", name: "Mozaik – Referans 1016" },
    { image: "", name: "Mozaik – Referans 1017" },
    { image: "", name: "Mozaik – Referans 1018" },
    { image: "", name: "Mozaik – Referans 1019" },
    { image: "", name: "Mozaik – Referans 1020" },
    { image: "", name: "Mozaik – Referans 1021" },
    { image: "", name: "Mozaik – Referans 1022" },
    { image: "", name: "Mozaik – Referans 1023" },
  ],
  [
    { image: "", name: "Mozaik – Referans 1024" },
    { image: "", name: "Mozaik – Referans 1025" },
    { image: "", name: "Mozaik – Referans 1026" },
    { image: "", name: "Mozaik – Referans 1027" },
    { image: "", name: "Afyon Beyaz CNC 1001" },
    { image: "", name: "Afyon Beyaz CNC 1001" },
    { image: "", name: "Afyon Beyaz CNC 1001" },
    { image: "", name: "CT-02 Afyon Beyaz Arcobaleno" },
    { image: "", name: "CT-02 Violet" },
    { image: "", name: "CT-03 Blackberry" },
    { image: "", name: "CT-04 Beyaz Traverten" },
    { image: "", name: "CT-04 Carrara" },
    { image: "", name: "CT-04-1 Carrara" },
    { image: "", name: "CT-04 Gümüş Traverten Düz Kesim" },
    { image: "", name: "CT-04 Kırmızı Traverten" },
    { image: "", name: "CT-05 Afyon Beyaz Mermer Eternal" },
    { image: "", name: "CT-05 Pearl" },
    { image: "", name: "CT-05 Silver Dragon" },
    { image: "", name: "CT-07 Olive Maron" },
    { image: "", name: "CT-08 Olive Maron" },
    { image: "", name: "CT-09 Blue Bahia" },
    { image: "", name: "CT-10 Blue Moon" },
    { image: "", name: "CT-12 Portoro" },
    { image: "", name: "CT-13 Afyon Beyaz Arcobaleno" },
  ],
  [
    { image: "", name: "CT-13 Amarante, Nuage Miel, Iris" },
    { image: "", name: "CT-13 Blue Bahia" },
    { image: "", name: "CT-13 Ice Jade" },
    { image: "", name: "CT-14 Nero Marquina" },
    { image: "", name: "CT-15 Afyon Beyaz Mermer Eternal" },
    { image: "", name: "CT-16 Afyon Beyaz Mermer Eternal" },
    { image: "", name: "CT-17 Silver Dragon" },
    { image: "", name: "CT-18 Dark Emperador" },
    { image: "", name: "CT-18 Silver Dragon" },
    { image: "", name: "CT-19 Carrara" },
    { image: "", name: "CT-20 İspanyol Dark Emperador" },
    { image: "", name: "CT-21 Afyon Beyaz Arcobaleno" },
    { image: "", name: "CT-22 Afyon Beyaz A La Vogue" },
    { image: "", name: "CT-23 Violet" },
    { image: "", name: "CT-24 İspanyol Dark Emperador" },
    { image: "", name: "CT-26 Afyon Beyaz Arcobaleno" },
    { image: "", name: "CT-26 Afyon Beyaz Arcobaleno, Blue Moon, Blue Bahia" },
    { image: "", name: "CT-26 Blue Moon" },
    { image: "", name: "CT-27 Afyon Beyaz A La Vogue" },
    { image: "", name: "Dekoratif Ürünler – Duş Teknesi 1001" },
    { image: "", name: "Dekoratif Ürünler – Duş Teknesi 1002" },
    { image: "", name: "Dekoratif Ürünler – Duş Teknesi 1003" },
    { image: "", name: "Dekoratif Ürünler – Duş Teknesi 1004" },
    { image: "", name: "Dekoratif Ürünler – Duş Teknesi 1005" },
  ],
  [
    { image: "", name: "Dekoratif Ürünler – Kolon 1001" },
    { image: "", name: "Dekoratif Ürünler – Kolon 1002" },
    { image: "", name: "Dekoratif Ürünler – Kolon 1003" },
    { image: "", name: "Dekoratif Ürünler – Kolon 1004" },
    { image: "", name: "Dekoratif Ürünler – Kolon 1005" },
    { image: "", name: "Dekoratif Ürünler – Korkuluk 1001" },
    { image: "", name: "Dekoratif Ürünler – Korkuluk 1002" },
    { image: "", name: "Dekoratif Ürünler – Korkuluk 1003" },
    { image: "", name: "Dekoratif Ürünler – Korkuluk 1004" },
    { image: "", name: "Dekoratif Ürünler – Korkuluk 1005" },
    { image: "", name: "Kurna BS-01" },
    { image: "", name: "Kurna BS-02" },
    { image: "", name: "Kurna BS-03" },
    { image: "", name: "Kurna BS-04" },
    { image: "", name: "Kurna BS-05" },
    { image: "", name: "Kurna BS-06" },
    { image: "", name: "Kurna BS-07" },
    { image: "", name: "Kurna BS-08" },
    { image: "", name: "Kurna BS-09" },
    { image: "", name: "Kurna BS-10" },
    { image: "", name: "Dekoratif Ürünler – Söve 1001" },
    { image: "", name: "Dekoratif Ürünler – Söve 1002" },
    { image: "", name: "Dekoratif Ürünler – Söve 1003" },
    { image: "", name: "Dekoratif Ürünler – Söve 1004" },
  ],
  [
    { image: "", name: "Süpürgelik EFM-18" },
    { image: "", name: "Süpürgelik EFM-19" },
    { image: "", name: "Süpürgelik EFM-20" },
    { image: "", name: "Süpürgelik EFM-25" },
    { image: "", name: "Süpürgelik EFM-26" },
    { image: "", name: "Süpürgelik EFM-27" },
    { image: "", name: "Süpürgelik EFM-43" },
    { image: "", name: "Süpürgelik EFM-44" },
    { image: "", name: "Süpürgelik EFM-45" },
    { image: "", name: "Süpürgelik EFM-46" },
    { image: "", name: "Süpürgelik EFM-47" },
    { image: "", name: "Süpürgelik EFM-48" },
    { image: "", name: "Süpürgelik EFM-49" },
    { image: "", name: "Süpürgelik EFM-50" },
    { image: "", name: "Süpürgelik EFM-51" },
    { image: "", name: "Süpürgelik EFM-52" },
    { image: "", name: "Süpürgelik EFM-54" },
    { image: "", name: "Dekoratif Ürünler – Sütun 1001" },
    { image: "", name: "Dekoratif Ürünler – Sütun 1002" },
    { image: "", name: "Dekoratif Ürünler – Sütun 1003" },
    { image: "", name: "Dekoratif Ürünler – Sütun 1004" },
    { image: "", name: "Dizayn Mozaik DM01" },
    { image: "", name: "Dizayn Mozaik DM02-1" },
    { image: "", name: "Dizayn Mozaik DM02-2" },
  ],
  [
    { image: "", name: "Dizayn Mozaik DM02-3" },
    { image: "", name: "Dizayn Mozaik DM03-1" },
    { image: "", name: "Dizayn Mozaik DM03-2" },
    { image: "", name: "Dizayn Mozaik DM03-3" },
    { image: "", name: "Dizayn Mozaik DM03-4" },
    { image: "", name: "Dizayn Mozaik DM03-5" },
    { image: "", name: "Dizayn Mozaik DM03-6" },
    { image: "", name: "Dizayn Mozaik DM03/A-1" },
    { image: "", name: "Dizayn Mozaik DM03/A-2" },
    { image: "", name: "Dizayn Mozaik DM03/B-1" },
    { image: "", name: "Dizayn Mozaik DM03/B-2" },
    { image: "", name: "Dizayn Mozaik DM03/C-1" },
    { image: "", name: "Dizayn Mozaik DM03/C-2" },
    { image: "", name: "Dizayn Mozaik DM04-3" },
    { image: "", name: "Dizayn Mozaik DM04-1" },
    { image: "", name: "Dizayn Mozaik DM04-2" },
    { image: "", name: "Dizayn Mozaik DM05-1" },
    { image: "", name: "Dizayn Mozaik DM05-2" },
    { image: "", name: "Dizayn Mozaik DM05-3" },
    { image: "", name: "Dizayn Mozaik DM06-1" },
    { image: "", name: "Dizayn Mozaik DM06-2" },
    { image: "", name: "Dizayn Mozaik DM06-3" },
    { image: "", name: "Dizayn Mozaik DM08" },
    { image: "", name: "Dizayn Mozaik DM09" },
  ],
  [
    { image: "", name: "Dizayn Mozaik DM10" },
    { image: "", name: "Dizayn Mozaik DM13" },
    { image: "", name: "Dizayn Mozaik DM14" },
    { image: "", name: "Dizayn Mozaik DM15" },
    { image: "", name: "Dizayn Mozaik DM16" },
    { image: "", name: "Dizayn Mozaik DM17-1" },
    { image: "", name: "Dizayn Mozaik DM17-2" },
    { image: "", name: "Dizayn Mozaik DM17-3" },
    { image: "", name: "Dizayn Mozaik DM18" },
    { image: "", name: "Dizayn Mozaik DM18-1" },
    { image: "", name: "Dizayn Mozaik DM22" },
    { image: "", name: "Dizayn Mozaik DM23-1" },
    { image: "", name: "Dizayn Mozaik DM23-2" },
    { image: "", name: "Dizayn Mozaik DM24-1" },
    { image: "", name: "Dizayn Mozaik DM24-2" },
    { image: "", name: "Dizayn Mozaik DM25" },
    { image: "", name: "Dizayn Mozaik DM27" },
    { image: "", name: "Dizayn Mozaik DM28" },
    { image: "", name: "Dizayn Mozaik DM29-1" },
    { image: "", name: "Dizayn Mozaik DM29-2" },
    { image: "", name: "Dizayn Mozaik DM29-3" },
    { image: "", name: "Dizayn Mozaik DM31" },
    { image: "", name: "Dizayn Mozaik DM32" },
    { image: "", name: "Dizayn Mozaik DM34" },
  ],
  [
    { image: "", name: "Dizayn Mozaik DM35-2" },
    { image: "", name: "Dizayn Mozaik DM35-1" },
    { image: "", name: "Dizayn Mozaik DM39-1" },
    { image: "", name: "Dizayn Mozaik DM39-2" },
    { image: "", name: "Dizayn Mozaik DM40" },
    { image: "", name: "Dizayn Mozaik DM41-1" },
    { image: "", name: "Dizayn Mozaik DM41-2" },
    { image: "", name: "Dizayn Mozaik DM41-3" },
    { image: "", name: "Dizayn Mozaik DM42-1" },
    { image: "", name: "Dizayn Mozaik DM42-2" },
    { image: "", name: "Dizayn Mozaik DM42-3" },
    { image: "", name: "Dizayn Mozaik DM42-4" },
    { image: "", name: "Dizayn Mozaik DM42-5" },
    { image: "", name: "Dizayn Mozaik DM42-6" },
    { image: "", name: "Dizayn Mozaik DM42-7" },
    { image: "", name: "Dizayn Mozaik DM42-8" },
    { image: "", name: "Dizayn Mozaik DM42-9" },
    { image: "", name: "ED-01 Beyaz Traverten" },
    { image: "", name: "ED-02 Bianco Crema" },
    { image: "", name: "ED-03 Bianco Crema" },
    { image: "", name: "ED-04 Beyaz Traverten" },
    { image: "", name: "ED-06 Afyon Beyaz Mermer" },
    { image: "", name: "ED-06 Beyaz Traverten" },
    { image: "", name: "ED-07 Beyaz Traverten" },
  ],
  [
    { image: "", name: "ED-08 Afyon Beyaz Mermer" },
    { image: "", name: "ED-08 Pearl" },
    { image: "", name: "ED-09 Pearl" },
    { image: "", name: "Fine Line Mozaik MM18-2" },
    { image: "", name: "Fine Line Mozaik MM18-1" },
    { image: "", name: "Fine Line Mozaik MM21" },
    { image: "", name: "Fine Line Mozaik MM22-1" },
    { image: "", name: "Fine Line Mozaik MM22-2" },
    { image: "", name: "Fine Line Mozaik MM22-3" },
    { image: "", name: "Fine Line Mozaik MM22-4" },
    { image: "", name: "Fine Line Mozaik MM23-1" },
    { image: "", name: "Fine Line Mozaik MM23-2" },
    { image: "", name: "Fine Line Mozaik MM32-1" },
    { image: "", name: "Fine Line Mozaik MM32-2" },
    { image: "", name: "Fine Line Mozaik MM38-1" },
    { image: "", name: "Fine Line Mozaik MM38-2" },
    { image: "", name: "Fine Line Mozaik MM38-3" },
    { image: "", name: "Fine Line Mozaik MM38-4" },
    { image: "", name: "Fine Line Mozaik MM38-5" },
    { image: "", name: "Fine Line Mozaik MM38-6" },
    { image: "", name: "Fine Line Mozaik MM38-7" },
    { image: "", name: "Fine Line Mozaik MM38-8" },
    { image: "", name: "Fine Line Mozaik MM38-9" },
    { image: "", name: "Fine Line Mozaik MM58-1" },
  ],
  [
    { image: "", name: "Fine Line Mozaik MM58-2" },
    { image: "", name: "Fine Line Mozaik MM66-1" },
    { image: "", name: "Fine Line Mozaik MM66-2" },
    { image: "", name: "Fine Line Mozaik MM66-3" },
    { image: "", name: "Fine Line Mozaik MM66-4" },
    { image: "", name: "Fine Line Mozaik MM66-5" },
    { image: "", name: "Fine Line Mozaik MM66-6" },
    { image: "", name: "Fine Line Mozaik MM66-7" },
    { image: "", name: "Fine Line Mozaik MM72-1" },
    { image: "", name: "Fine Line Mozaik MM72-2" },
    { image: "", name: "Klasik Mozaik MM01" },
    { image: "", name: "Klasik Mozaik MM02" },
    { image: "", name: "Klasik Mozaik MM03" },
    { image: "", name: "Klasik Mozaik MM04" },
    { image: "", name: "Klasik Mozaik MM05-1" },
    { image: "", name: "Klasik Mozaik MM05-2" },
    { image: "", name: "Klasik Mozaik MM06-1" },
    { image: "", name: "Klasik Mozaik MM06-2" },
    { image: "", name: "Klasik Mozaik MM07-1" },
    { image: "", name: "Klasik Mozaik MM07-2" },
    { image: "", name: "Klasik Mozaik MM09" },
    { image: "", name: "Klasik Mozaik MM10-1" },
    { image: "", name: "Klasik Mozaik MM10-2" },
    { image: "", name: "Klasik Mozaik MM11-1" },
  ],
  [
    { image: "", name: "Klasik Mozaik MM11-2" },
    { image: "", name: "Klasik Mozaik MM11-3" },
    { image: "", name: "Klasik Mozaik MM12-1" },
    { image: "", name: "Klasik Mozaik MM12-2" },
    { image: "", name: "Klasik Mozaik MM13-1" },
    { image: "", name: "Klasik Mozaik MM13-2" },
    { image: "", name: "Klasik Mozaik MM13-3" },
    { image: "", name: "Klasik Mozaik MM16-1" },
    { image: "", name: "Klasik Mozaik MM16-1/1" },
    { image: "", name: "Klasik Mozaik MM16-2" },
    { image: "", name: "Klasik Mozaik MM16-3" },
    { image: "", name: "Klasik Mozaik MM16-4" },
    { image: "", name: "Klasik Mozaik MM16-5" },
    { image: "", name: "Klasik Mozaik MM16-6" },
    { image: "", name: "Klasik Mozaik MM16-7" },
    { image: "", name: "Klasik Mozaik MM17-1" },
    { image: "", name: "Klasik Mozaik MM17-2" },
    { image: "", name: "Klasik Mozaik MM17-3" },
    { image: "", name: "Klasik Mozaik MM17-4" },
    { image: "", name: "Klasik Mozaik MM17-5" },
    { image: "", name: "Klasik Mozaik MM17-6" },
    { image: "", name: "Klasik Mozaik MM17/A-1" },
    { image: "", name: "Klasik Mozaik MM17/A-2" },
    { image: "", name: "Klasik Mozaik MM17/A-3" },
  ],
  [
    { image: "", name: "Klasik Mozaik MM17/A-4" },
    { image: "", name: "Klasik Mozaik MM17/A-5" },
    { image: "", name: "Klasik Mozaik MM18-1" },
    { image: "", name: "Klasik Mozaik MM18-2" },
    { image: "", name: "Klasik Mozaik MM18-3" },
    { image: "", name: "Klasik Mozaik MM18-4" },
    { image: "", name: "Klasik Mozaik MM18-5" },
    { image: "", name: "Klasik Mozaik MM18-6" },
    { image: "", name: "Klasik Mozaik MM18-7" },
    { image: "", name: "Klasik Mozaik MM19-1" },
    { image: "", name: "Klasik Mozaik MM19-2" },
    { image: "", name: "Klasik Mozaik MM20-1" },
    { image: "", name: "Klasik Mozaik MM20-2" },
    { image: "", name: "Klasik Mozaik MM21-1" },
    { image: "", name: "Klasik Mozaik MM21-2" },
    { image: "", name: "Klasik Mozaik MM21-3" },
    { image: "", name: "Klasik Mozaik MM21-4" },
    { image: "", name: "Klasik Mozaik MM21-5" },
    { image: "", name: "Klasik Mozaik MM22-1" },
    { image: "", name: "Klasik Mozaik MM22-2" },
    { image: "", name: "Klasik Mozaik MM22-3" },
    { image: "", name: "Klasik Mozaik MM22-4" },
    { image: "", name: "Klasik Mozaik MM22-5" },
    { image: "", name: "Klasik Mozaik MM22-6" },
  ],
  [
    { image: "", name: "Klasik Mozaik MM22/A-1" },
    { image: "", name: "Klasik Mozaik MM22/A-2" },
    { image: "", name: "Klasik Mozaik MM23-1" },
    { image: "", name: "Klasik Mozaik MM23-2" },
    { image: "", name: "Klasik Mozaik MM24-1" },
    { image: "", name: "Klasik Mozaik MM24-2" },
    { image: "", name: "Klasik Mozaik MM25" },
    { image: "", name: "Klasik Mozaik MM30" },
    { image: "", name: "Klasik Mozaik MM31" },
    { image: "", name: "Klasik Mozaik MM31/A" },
    { image: "", name: "Klasik Mozaik MM32-1" },
    { image: "", name: "Klasik Mozaik MM32-2" },
    { image: "", name: "Klasik Mozaik MM32-3" },
    { image: "", name: "Klasik Mozaik MM32-4" },
    { image: "", name: "Klasik Mozaik MM33-1" },
    { image: "", name: "Klasik Mozaik MM33-2" },
    { image: "", name: "Klasik Mozaik MM33-3" },
    { image: "", name: "Klasik Mozaik MM33-4" },
    { image: "", name: "Klasik Mozaik MM34-1" },
    { image: "", name: "Klasik Mozaik MM34-2" },
    { image: "", name: "Klasik Mozaik MM34-3" },
    { image: "", name: "Klasik Mozaik MM38-1" },
    { image: "", name: "Klasik Mozaik MM38-2" },
    { image: "", name: "Klasik Mozaik MM38-3" },
  ],
  [
    { image: "", name: "Klasik Mozaik MM38-4" },
    { image: "", name: "Klasik Mozaik MM38-5" },
    { image: "", name: "Klasik Mozaik MM38-6" },
    { image: "", name: "Klasik Mozaik MM38-7" },
    { image: "", name: "Klasik Mozaik MM38-8" },
    { image: "", name: "Klasik Mozaik MM38-9" },
    { image: "", name: "Klasik Mozaik MM45-1" },
    { image: "", name: "Klasik Mozaik MM45-2" },
    { image: "", name: "Klasik Mozaik MM45-3" },
    { image: "", name: "Klasik Mozaik MM45-4" },
    { image: "", name: "Klasik Mozaik MM47-1" },
    { image: "", name: "Klasik Mozaik MM47-2" },
    { image: "", name: "Klasik Mozaik MM47-3" },
    { image: "", name: "Klasik Mozaik MM50" },
    { image: "", name: "Klasik Mozaik MM52" },
    { image: "", name: "Klasik Mozaik MM56" },
    { image: "", name: "Klasik Mozaik MM57" },
    { image: "", name: "Klasik Mozaik MM58-1" },
    { image: "", name: "Klasik Mozaik MM58-2" },
    { image: "", name: "Klasik Mozaik MM58-3" },
    { image: "", name: "Klasik Mozaik MM58-4" },
    { image: "", name: "Klasik Mozaik MM59" },
    { image: "", name: "Klasik Mozaik MM60" },
    { image: "", name: "Klasik Mozaik MM61-1" },
  ],
  [
    { image: "", name: "Klasik Mozaik MM61-2" },
    { image: "", name: "Klasik Mozaik MM61-3" },
    { image: "", name: "Klasik Mozaik MM62-1" },
    { image: "", name: "Klasik Mozaik MM62-2" },
    { image: "", name: "Klasik Mozaik MM64-1" },
    { image: "", name: "Klasik Mozaik MM64-2" },
    { image: "", name: "Klasik Mozaik MM65-1" },
    { image: "", name: "Klasik Mozaik MM65-2" },
    { image: "", name: "Klasik Mozaik MM65-3" },
    { image: "", name: "Klasik Mozaik MM66-1" },
    { image: "", name: "Klasik Mozaik MM66-2" },
    { image: "", name: "Klasik Mozaik MM69" },
    { image: "", name: "Klasik Mozaik MM70" },
    { image: "", name: "Klasik Mozaik MM71" },
    { image: "", name: "Dekoratif Ürünler – Şampuanlık 1001" },
    { image: "", name: "Dekoratif Ürünler – Şampuanlık 1002" },
    { image: "", name: "Dekoratif Ürünler – Şampuanlık 1003" },
    { image: "", name: "Dekoratif Ürünler – Şampuanlık 1004" },
    { image: "", name: "Dekoratif Ürünler – Şampuanlık 1005" },
    { image: "", name: "Dekoratif Ürünler – Şampuanlık 1006" },
    { image: "", name: "Dekoratif Ürünler – Şampuanlık 1007" },
    { image: "", name: "Dekoratif Ürünler – Şampuanlık 1008" },
    { image: "", name: "Dekoratif Ürünler – Aksesuar 1001" },
    { image: "", name: "Dekoratif Ürünler – Aksesuar 1002" },
  ],
  [
    { image: "", name: "Dekoratif Ürünler – Aksesuar 1003" },
    { image: "", name: "Dekoratif Ürünler – Aksesuar 1004" },
    { image: "", name: "Dekoratif Ürünler – Aksesuar 1005" },
    { image: "", name: "Dekoratif Ürünler – Aksesuar 1006" },
    { image: "", name: "Dekoratif Ürünler – Aksesuar 1007" },
    { image: "", name: "Dekoratif Ürünler – Aksesuar 1008" },
    { image: "", name: "Dekoratif Ürünler – Aksesuar 1009" },
    { image: "", name: "Dekoratif Ürünler – Aksesuar 1010" },
    { image: "", name: "Dekoratif Ürünler – Aksesuar 1011" },
    { image: "", name: "Dekoratif Ürünler – Bahçe Süslemesi 1001" },
    { image: "", name: "Dekoratif Ürünler – Bahçe Süslemesi 1002" },
    { image: "", name: "Dekoratif Ürünler – Bahçe Süslemesi 1003" },
    { image: "", name: "Dekoratif Ürünler – Bahçe Süslemesi 1004" },
    { image: "", name: "Dekoratif Ürünler – Bahçe Süslemesi 1005" },
    { image: "", name: "Dekoratif Ürünler – Bahçe Süslemesi 1006" },
    { image: "", name: "Dekoratif Ürünler – Bahçe Süslemesi 1007" },
    { image: "", name: "Dekoratif Ürünler – Bahçe Süslemesi 1008" },
    { image: "", name: "Dekoratif Ürünler – Bahçe Süslemesi 1009" },
    { image: "", name: "Dekoratif Ürünler – Bahçe Süslemesi 1010" },
    { image: "", name: "Dekoratif Ürünler – Aplik 1001" },
    { image: "", name: "Dekoratif Ürünler – Aplik 1002" },
    { image: "", name: "Mini Pattern Mozaik MP02" },
    { image: "", name: "Mini Pattern Mozaik MP04" },
    { image: "", name: "Mini Pattern Mozaik MP05" },
  ],
  [
    { image: "", name: "Mini Pattern Mozaik MP06" },
    { image: "", name: "Patlatma Mozaik SF01-1" },
    { image: "", name: "Patlatma Mozaik SF01-3" },
    { image: "", name: "Patlatma Mozaik SF02-1" },
    { image: "", name: "Patlatma Mozaik SF02-2" },
    { image: "", name: "Patlatma Mozaik SF03-1" },
    { image: "", name: "Patlatma Mozaik SF03-2" },
    { image: "", name: "Patlatma Mozaik SF03-3" },
    { image: "", name: "Patlatma Mozaik SF04-1" },
    { image: "", name: "Patlatma Mozaik SF04-2" },
    { image: "", name: "Patlatma Mozaik SF04-3" },
    { image: "", name: "Patlatma Mozaik SF04-4" },
    { image: "", name: "Patlatma Mozaik SF04-5" },
    { image: "", name: "Patlatma Mozaik SF04-6" },
    { image: "", name: "Patlatma Mozaik SF04-7" },
    { image: "", name: "Patlatma Mozaik SF04-8" },
    { image: "", name: "Patlatma Mozaik SF05" },
    { image: "", name: "Patlatma Mozaik SF06" },
    { image: "", name: "Patlatma Mozaik SF07" },
    { image: "", name: "Patlatma Mozaik SF08" },
    { image: "", name: "Patlatma Mozaik SF09" },
    { image: "", name: "Patlatma Mozaik SF10" },
    { image: "", name: "Patlatma Mozaik SF11" },
    { image: "", name: "Patlatma Mozaik SF13" },
  ],
  [
    { image: "", name: "Patlatma Mozaik SF14" },
    { image: "", name: "Patlatma Mozaik SF15" },
    { image: "", name: "Patlatma Mozaik SF16" },
    { image: "", name: "Patlatma Mozaik SF17" },
    { image: "", name: "Patlatma Mozaik SF18" },
    { image: "", name: "Patlatma Mozaik SF19" },
    { image: "", name: "Patlatma Mozaik SF20" },
    { image: "", name: "Patlatma Mozaik SF22" },
    { image: "", name: "Patlatma Mozaik SF23-1" },
    { image: "", name: "Patlatma Mozaik SF23-2" },
    { image: "", name: "Patlatma Mozaik SF23-3" },
    { image: "", name: "Patlatma Mozaik SF23-4" },
    { image: "", name: "Patlatma Mozaik SF24" },
    { image: "", name: "Patlatma Mozaik SF26" },
    { image: "", name: "Patlatma Mozaik SF27-1" },
    { image: "", name: "Patlatma Mozaik SF27-2" },
    { image: "", name: "Patlatma Mozaik SF27-3" },
    { image: "", name: "Patlatma Mozaik SF29" },
    { image: "", name: "Patlatma Mozaik SF31" },
    { image: "", name: "Patlatma Mozaik SF32" },
    { image: "", name: "Patlatma Mozaik SF34" },
    { image: "", name: "Patlatma Mozaik SF35" },
    { image: "", name: "Patlatma Mozaik SF36" },
    { image: "", name: "Pinguino" },
  ],
  [
    { image: "", name: "Portoro" },
    { image: "", name: "Bordür Mozaik BM01" },
    { image: "", name: "Bordür Mozaik BM02" },
    { image: "", name: "Bordür Mozaik BM03" },
    { image: "", name: "Bordür Mozaik BM04" },
    { image: "", name: "Bordür Mozaik BM05" },
    { image: "", name: "Bordür Mozaik BM06" },
    { image: "", name: "Bordür Mozaik BM07" },
    { image: "", name: "Bordür Mozaik BM08" },
    { image: "", name: "Bordür Mozaik BM09" },
    { image: "", name: "Bordür Mozaik BM10" },
    { image: "", name: "Bordür Mozaik BM11" },
    { image: "", name: "Bordür Mozaik BM12" },
    { image: "", name: "Bordür Mozaik BM13" },
    { image: "", name: "Bordür Mozaik BM14" },
    { image: "", name: "Bordür Mozaik BM16" },
    { image: "", name: "Bordür Mozaik BM17" },
    { image: "", name: "Bordür Mozaik BM18" },
    { image: "", name: "Bordür Mozaik BM22" },
    { image: "", name: "Bordür Mozaik BM26" },
    { image: "", name: "Bordür Mozaik BM28" },
    { image: "", name: "Bordür Mozaik BM29" },
    { image: "", name: "Bordür Mozaik BM30" },
    { image: "", name: "Bordür Mozaik BM31" },
  ],
  [
    { image: "", name: "Bordür Mozaik BM32" },
    { image: "", name: "Bordür Mozaik BM33" },
    { image: "", name: "Bordür Mozaik BM34" },
    { image: "", name: "Bordür Mozaik BM35" },
    { image: "", name: "Bordür Mozaik BM37" },
    { image: "", name: "Bordür Mozaik BM39" },
    { image: "", name: "Bordür Mozaik BM42" },
    { image: "", name: "Bordür Mozaik BM43" },
    { image: "", name: "Bordür Mozaik BM44" },
    { image: "", name: "Bordür Mozaik BM45" },
    { image: "", name: "Bordür Mozaik BM46" },
    { image: "", name: "Bordür Mozaik BM47" },
    { image: "", name: "Bordür Mozaik BM48" },
    { image: "", name: "Bordür Mozaik BM49" },
    { image: "", name: "Bordür Mozaik BM50" },
    { image: "", name: "Bordür Mozaik BM51" },
    { image: "", name: "Bordür Mozaik BM52" },
    { image: "", name: "Bordür Mozaik BM53" },
    { image: "", name: "Bordür Mozaik BM54" },
    { image: "", name: "Bordür Mozaik BM55" },
    { image: "", name: "Bordür Mozaik BM56" },
    { image: "", name: "Silver Dragon" },
    { image: "", name: "T-02 Afyon Beyaz Arcobaleno" },
    { image: "", name: "T-03 Afyon Beyaz Arcobaleno" },
  ],
  [
    { image: "", name: "T-04 Lilla" },
    { image: "", name: "T-05 Afyon Beyaz Arcobaleno" },
    { image: "", name: "T-06 Beyaz Traverten" },
    { image: "", name: "T-07 Blue Bahia" },
    { image: "", name: "T-07 Gümüş Traverten Düz Kesim" },
    { image: "", name: "T-08 Gümüş Traverten Düz Kesim" },
    { image: "", name: "T-09 Metell" },
    { image: "", name: "T-11 Afyon Beyaz Arcobaleno" },
    { image: "", name: "T-12 Afyon Beyaz Arcobaleno" },
    { image: "", name: "T-13 Nero Marquina" },
    { image: "", name: "T-14 Gümüş Traverten Düz Kesim" },
    { image: "", name: "T-15 Carrara" },
    { image: "", name: "K-01 Dark Emperador" },
    { image: "", name: "K-03 Lilla" },
    { image: "", name: "K-05 Pearl" },
    { image: "", name: "K-07 Pinguino" },
    { image: "", name: "K-09 Warm Walnut" },
    { image: "", name: "K-10 Lilla" },
    { image: "", name: "Tabure1 – Beyaz Traverten" },
    { image: "", name: "Tabure2 – Beyaz Traverten" },
    { image: "", name: "Waterjet Bordür WJB-05" },
    { image: "", name: "Waterjet Bordür WJB-06" },
    { image: "", name: "Waterjet Bordür WJB-07" },
    { image: "", name: "Waterjet Karo WJK-01" },
  ],
  [
    { image: "", name: "Waterjet Karo WJK-02" },
    { image: "", name: "Waterjet Karo WJK-03" },
    { image: "", name: "Waterjet Karo WJK-04" },
    { image: "", name: "Waterjet Karo WJK-05" },
    { image: "", name: "Waterjet Karo WJK-06" },
    { image: "", name: "Waterjet Karo WJK-07" },
    { image: "", name: "Waterjet Karo WJK-08" },
    { image: "", name: "Waterjet Karo WJK-09" },
    { image: "", name: "Waterjet Karo WJK-10" },
    { image: "", name: "Waterjet Madalyon WJM-01" },
    { image: "", name: "Waterjet Madalyon WJM-02" },
    { image: "", name: "Waterjet Madalyon WJM-03" },
    { image: "", name: "Waterjet Madalyon WJM-04" },
    { image: "", name: "Waterjet Madalyon WJM-05" },
    { image: "", name: "Waterjet Madalyon WJM-07" },
    { image: "", name: "Waterjet Madalyon WJM-08" },
    { image: "", name: "Waterjet Madalyon WJM-09" },
    { image: "", name: "Waterjet Madalyon WJM-10" },
    { image: "", name: "Waterjet Madalyon WJM-11" },
    { image: "", name: "Waterjet Madalyon WJM-12" },
    { image: "", name: "Waterjet Madalyon WJM-13" },
    { image: "", name: "Waterjet Madalyon WJM-14-1" },
    { image: "", name: "Waterjet Madalyon WJM-14-2" },
    { image: "", name: "Waterjet Madalyon WJM-15-1" },
  ],
  [
    { image: "", name: "Waterjet Madalyon WJM-15-2" },
    { image: "", name: "Waterjet Madalyon WJM-16" },
    { image: "", name: "Waterjet Madalyon WJM-17" },
    { image: "", name: "Waterjet Madalyon WJM-18" },
    { image: "", name: "Waterjet Madalyon WJM-19-1" },
    { image: "", name: "Waterjet Madalyon WJM-19-2" },
    { image: "", name: "Waterjet Madalyon WJM-19-3" },
    { image: "", name: "Waterjet Madalyon WJM-20" },
    { image: "", name: "Waterjet Madalyon WJM-21" },
    { image: "", name: "Waterjet Madalyon WJM-22" },
    { image: "", name: "Waterjet Madalyon WJM-24" },
    { image: "", name: "Waterjet Madalyon WJM-25" },
    { image: "", name: "Waterjet Madalyon WJM-26" },
    { image: "", name: "Waterjet Madalyon WJM-27" },
    { image: "", name: "Waterjet Madalyon WJM-28" },
    { image: "", name: "Waterjet Madalyon WJM-29" },
    { image: "", name: "Waterjet Madalyon WJM-30-1" },
    { image: "", name: "Waterjet Madalyon WJM-30-2" },
    { image: "", name: "Waterjet Madalyon WJM-30-3" },
    { image: "", name: "Waterjet Madalyon WJM-31" },
    { image: "", name: "Waterjet Madalyon WJM-32" },
    { image: "", name: "Waterjet Madalyon WJM-33" },
    { image: "", name: "Waterjet Madalyon WJM-34-1" },
    { image: "", name: "Waterjet Madalyon WJM-34-2" },
  ],
  [
    { image: "", name: "Waterjet Madalyon WJM-35" },
    { image: "", name: "Waterjet Madalyon WJM-36-1" },
    { image: "", name: "Waterjet Madalyon WJM-36-2" },
    { image: "", name: "Waterjet Madalyon WJM-37" },
    { image: "", name: "Waterjet Madalyon WJM-38" },
    { image: "", name: "Waterjet Madalyon WJM-39" },
    { image: "", name: "Waterjet Madalyon WJM-40" },
    { image: "", name: "Waterjet Mozaik WJC-01" },
    { image: "", name: "Waterjet Mozaik WJC-02-1" },
    { image: "", name: "Waterjet Mozaik WJC-02-2" },
    { image: "", name: "Waterjet Mozaik WJC-03" },
  ],
];
