export const ozelKoleksiyon = [
  [
    { image: "", name: "Panda Emerald Marble 101" },
    { image: "", name: "Rain Forest Brown 103" },
    { image: "", name: "Rain Forest Green 101" },
    { image: "", name: "Panda Azul 101" },
    { image: "", name: "Panda Azul 102" },
    { image: "", name: "Agate Blue 1" },
    { image: "", name: "Agate Blue 2" },
    { image: "", name: "Agate Green 1" },
    { image: "", name: "Agate Green 2" },
    { image: "", name: "Agate Purple 1" },
    { image: "", name: "Grey Agate 1" },
    { image: "", name: "Petrified Wood 1" },
    { image: "", name: "Agate White 1" },
    { image: "", name: "Round Agathe 1" },
    { image: "", name: "Round Agathe 2" },
    { image: "", name: "Agate Athena Gold" },
    { image: "", name: "Rosa Quartz 1" },
    { image: "", name: "Yellow Tiger Agate 1" },
    { image: "", name: "Agate Black Dim Gold" },
    { image: "", name: "Agate Cezanne Gold" },
    { image: "", name: "Agate Phoenix" },
    { image: "", name: "Amazonite" },
    { image: "", name: "Fluorite" },
    { image: "", name: "Green Agate" },
  ],
  [
    { image: "", name: "Turtle 101" },
    { image: "", name: "Turtle 102" },
    { image: "", name: "Emerald 101" },
    { image: "", name: "Emerald 102" },
    { image: "", name: "Emerald 103" },
    { image: "", name: "Emerald 104" },
    { image: "", name: "Hills 101" },
    { image: "", name: "Beyaz Oniks 102" },
    { image: "", name: "Rain Forest Brown 102" },
    { image: "", name: "Verde Forest 101" },
    { image: "", name: "Black Aziza 101" },
    { image: "", name: "Ice Jade 101" },
    { image: "", name: "Desert Wave 101" },
  ],
];

export const dogalTaslar = [
  [
    { image: "", name: "Blue Ice Onyx 101" },
    { image: "", name: "Green Ice Onyx 101" },
    { image: "", name: "Pink Ice Onyx 101" },
    { image: "", name: "Desert Wave 102" },
    { image: "", name: "Panda Emerald Marble 101" },
    { image: "", name: "Rain Forest Brown 103" },
    { image: "", name: "Rain Forest Green 101" },
    { image: "", name: "Panda Azul 101" },
    { image: "", name: "Panda Azul 102" },
    { image: "", name: "Magma Gold 102" },
    { image: "", name: "Ice Jade 106" },
    { image: "", name: "Petrified Wood Marble 101" },
    { image: "", name: "Dark Emperador 102" },
    { image: "", name: "Agate Blue 1" },
    { image: "", name: "Agate Blue 2" },
    { image: "", name: "Agate Green 1" },
    { image: "", name: "Agate Green 2" },
    { image: "", name: "Agate Purple 1" },
    { image: "", name: "Grey Agate 1" },
    { image: "", name: "Petrified Wood 1" },
    { image: "", name: "Agate White 1" },
    { image: "", name: "Round Agathe 1" },
    { image: "", name: "Round Agathe 2" },
    { image: "", name: "Azul Macaubas 101" },
  ],
  [
    { image: "", name: "Azul Macaubas 102" },
    { image: "", name: "Black Leopar 101" },
    { image: "", name: "Serpegiante Light 101" },
    { image: "", name: "Tiger Oniks 101" },
    { image: "", name: "Tiger Oniks 102" },
    { image: "", name: "Wooden Onyx 101" },
    { image: "", name: "Afyon Beyaz Mermer Spider 101" },
    { image: "", name: "Panda White 105" },
    { image: "", name: "Panda White 106" },
    { image: "", name: "Beach 101" },
    { image: "", name: "Picasso 101" },
    { image: "", name: "Nero Gold 101" },
    { image: "", name: "Armani" },
    { image: "", name: "Chateaux" },
    { image: "", name: "Pinguino Klasik" },
    { image: "", name: "Bardiglio Black 101" },
    { image: "", name: "Botticino 101" },
    { image: "", name: "Pinguino 102" },
    { image: "", name: "Agate Athena Gold" },
    { image: "", name: "Rosa Quartz 1" },
    { image: "", name: "Yellow Tiger Agate 1" },
    { image: "", name: "Agate Black Dim Gold" },
    { image: "", name: "Agate Cezanne Gold" },
    { image: "", name: "Agate Phoenix" },
  ],
  [
    { image: "", name: "Amazonite" },
    { image: "", name: "Fluorite" },
    { image: "", name: "Green Agate" },
    { image: "", name: "Turtle 102" },
    { image: "", name: "Emerald 101" },
    { image: "", name: "Emerald 102" },
    { image: "", name: "Emerald 103" },
    { image: "", name: "Emerald 104" },
    { image: "", name: "Hills 101" },
    { image: "", name: "Beyaz Oniks 102" },
    { image: "", name: "Panda White 104" },
    { image: "", name: "Serpegiante 101" },
    { image: "", name: "Marmara Beyaz Mermer 101" },
    { image: "", name: "Zebra White 101" },
    { image: "", name: "Blue Rain 101" },
    { image: "", name: "Fusion 101" },
    { image: "", name: "Rain Forest Brown 102" },
    { image: "", name: "Statuario 101" },
    { image: "", name: "Nero 101" },
    { image: "", name: "Bruno Perla 101" },
    { image: "", name: "Zebra Black 102" },
    { image: "", name: "Bruno 101" },
    { image: "", name: "Ice Jade 102" },
    { image: "", name: "Panda White 102" },
  ],
  [
    { image: "", name: "Turtle 101" },
    { image: "", name: "Afyon Beyaz Oniks 101" },
    { image: "", name: "Afyon Beyaz Oniks 102" },
    { image: "", name: "Afyon Beyaz Mermer Billur Gold 101" },
    { image: "", name: "Afyon Beyaz Mermer Billur Gold 102" },
    { image: "", name: "Pedras Granit – Cilalı 101" },
    { image: "", name: "Pedras Granit – Kumlama 102" },
    { image: "", name: "Antique Pewter – Honlu 101" },
    { image: "", name: "Antique Pewter – Eskitme 101" },
    { image: "", name: "Calacatta Oro 101" },
    { image: "", name: "Zebra Grey 101" },
    { image: "", name: "Bal Oniks 101" },
    { image: "", name: "White Beauty Premium" },
    { image: "", name: "Carrara Arabescato 101" },
    { image: "", name: "Bubble Oniks 101" },
    { image: "", name: "Cappuccino Oniks 101" },
    { image: "", name: "Dış Mekan – Blue Bahia 101" },
    { image: "", name: "Dış Mekan – White Walker 101" },
    { image: "", name: "Dış Mekan – White Walker 102" },
    { image: "", name: "Dış Mekan – Referans 101" },
    { image: "", name: "Dış Mekan – Referans 102" },
    { image: "", name: "Dış Mekan – Referans 103" },
    { image: "", name: "Dış Mekan – Referans 104" },
    { image: "", name: "Dış Mekan – Referans 105" },
  ],
  [
    { image: "", name: "Dış Mekan – Referans 106" },
    { image: "", name: "Dış Mekan – Referans 107" },
    { image: "", name: "Dış Mekan – Referans 108" },
    { image: "", name: "Dış Mekan – Referans 109" },
    { image: "", name: "Dış Mekan – Referans 110" },
    { image: "", name: "Dış Mekan – Referans 111" },
    { image: "", name: "Dış Mekan – Referans 112" },
    { image: "", name: "Dış Mekan – Referans 113" },
    { image: "", name: "Dış Mekan – Referans 114" },
    { image: "", name: "Dış Mekan – Referans 115" },
    { image: "", name: "Dış Mekan – Referans 116" },
    { image: "", name: "Dış Mekan – Referans 117" },
    { image: "", name: "Dış Mekan – Referans 118" },
    { image: "", name: "Velluto Oniks 101" },
    { image: "", name: "Gümüş Oniks 101" },
    { image: "", name: "Gümüş Oniks 102" },
    { image: "", name: "Afyon Beyaz Mermer Arcobaleno 101" },
    { image: "", name: "Afyon Beyaz Mermer Golden Gray 101" },
    { image: "", name: "Afyon Beyaz Mermer A La Vogue 101" },
    { image: "", name: "Afyon Beyaz Mermer Billur 101" },
    { image: "", name: "Afyon Beyaz Mermer Billur 102" },
    { image: "", name: "Afyon Beyaz Mermer Billur 103" },
    { image: "", name: "Sperenza 101" },
    { image: "", name: "Calacatta 101" },
  ],
  [
    { image: "", name: "Calacatta 102" },
    { image: "", name: "Gold Oniks 101" },
    { image: "", name: "Cocacola Oniks 101" },
    { image: "", name: "Coquillage 101" },
    { image: "", name: "Bianco Crema 101" },
    { image: "", name: "Bianco Crema 102" },
    { image: "", name: "Bianco Crema 103" },
    { image: "", name: "Golden Crema 101" },
    { image: "", name: "Sunny 101" },
    { image: "", name: "Sunny Light 101" },
    { image: "", name: "Mocca – Cilalı 101" },
    { image: "", name: "Gargamel 101" },
    { image: "", name: "Calimero 101" },
    { image: "", name: "Calimero – Küp Taşlar 101" },
    { image: "", name: "Calimero – Küp Taşlar 102" },
    { image: "", name: "Calimero – Küp Taşlar 103" },
    { image: "", name: "Gümüş Traverten 101" },
    { image: "", name: "Gümüş Traverten 102" },
    { image: "", name: "Gümüş Traverten 103" },
    { image: "", name: "Verde Guatemala 101" },
    { image: "", name: "Verde Forest 101" },
    { image: "", name: "Elazığ Vişne 101" },
    { image: "", name: "Volakas Bianco 101" },
    { image: "", name: "Lilla 102" },
  ],
  [
    { image: "", name: "Rosalia 101" },
    { image: "", name: "Rosalia Light 101" },
    { image: "", name: "Light Emperador Klasik Mermer" },
    { image: "", name: "Pedras Granit – Kumlama 103" },
    { image: "", name: "White Walker 101" },
    { image: "", name: "White Walker – Küp Taşlar 101" },
    { image: "", name: "White Walker – Küp Taşlar 102" },
    { image: "", name: "White Walker – Küp Taşlar 103" },
    { image: "", name: "Desert Black 101" },
    { image: "", name: "Nero Marquina 101" },
    { image: "", name: "Nebel 101" },
    { image: "", name: "Absolute Black 101" },
    { image: "", name: "Star Galaxy 101" },
    { image: "", name: "Paradiso 101" },
    { image: "", name: "P White 101" },
    { image: "", name: "Mocca – Honlu 101" },
    { image: "", name: "Mocca – Eskitme 101" },
    { image: "", name: "Mocca – Fırçalı 101" },
    { image: "", name: "Afyon Beyaz Mermer Şeker 101" },
    { image: "", name: "Calacatta 103" },
    { image: "", name: "Calacatta 104" },
    { image: "", name: "Blue Moon 101" },
    { image: "", name: "Blue Moon 102" },
    { image: "", name: "Blue Moon 103" },
  ],
  [
    { image: "", name: "Nuage Miel 101" },
    { image: "", name: "Nuage Doré 101" },
    { image: "", name: "Blue Bahia 101" },
    { image: "", name: "Blue Bahia 102" },
    { image: "", name: "Afyon Beyaz Marine Blue 101" },
    { image: "", name: "Afyon Beyaz Marine Blue 106" },
    { image: "", name: "Blue Stone 101" },
    { image: "", name: "Blue Moon Gold 101" },
    { image: "", name: "Crema Bella 101" },
    { image: "", name: "Crema Foret 101" },
    { image: "", name: "Luna 101" },
    { image: "", name: "Botanica 101" },
    { image: "", name: "Limpido 101" },
    { image: "", name: "Luna Piera 101" },
    { image: "", name: "Dark Emperador 101" },
    { image: "", name: "Dark Emperador Klasik 101" },
    { image: "", name: "Bruno Perla 102" },
    { image: "", name: "Emperador Perla 101" },
    { image: "", name: "Emperador Perla Klasik 101" },
    { image: "", name: "Mondo 101" },
    { image: "", name: "Dune 101" },
    { image: "", name: "Brume 101" },
    { image: "", name: "Avorio 101" },
    { image: "", name: "Bardiglio Blu 101" },
  ],
  [
    { image: "", name: "Bardiglio Blu 102" },
    { image: "", name: "Bardiglio Blu 103" },
    { image: "", name: "Bardiglio Blu 104" },
    { image: "", name: "Iris 101" },
    { image: "", name: "Iris 102" },
    { image: "", name: "Iris 103" },
    { image: "", name: "Iris 104" },
    { image: "", name: "Nero 102" },
    { image: "", name: "Gümüş Traverten Düz Kesim 101" },
    { image: "", name: "Gümüş Traverten Düz Kesim 102" },
    { image: "", name: "Gümüş Traverten Düz Kesim 103" },
    { image: "", name: "Gümüş Traverten Düz Kesim 104" },
    { image: "", name: "River 101" },
    { image: "", name: "Imperial Blend 101" },
    { image: "", name: "Royal Blend 101" },
    { image: "", name: "Warm Walnut 101" },
    { image: "", name: "Cashmere 101" },
    { image: "", name: "Beyaz Traverten 101" },
    { image: "", name: "Beyaz Traverten 102" },
    { image: "", name: "Beyaz Traverten Düz Kesim 101" },
    { image: "", name: "Beyaz Traverten Düz Kesim 102" },
    { image: "", name: "Klasik Traverten 101" },
    { image: "", name: "Klasik Traverten Düz Kesim 101" },
    { image: "", name: "Kale 101" },
  ],
  [
    { image: "", name: "Black Pearl 101" },
    { image: "", name: "Kırmızı Traverten 101" },
    { image: "", name: "Kırmızı Traverten 102" },
    { image: "", name: "Blackberry 101" },
    { image: "", name: "Blackberry Düz Kesim 101" },
    { image: "", name: "Kırmızı Traverten 103" },
    { image: "", name: "Kırmızı Traverten Düz Kesim 101" },
    { image: "", name: "Kırmızı Traverten Düz Kesim 102" },
    { image: "", name: "Cascade White 101" },
    { image: "", name: "Cascade White Düz Kesim 101" },
    { image: "", name: "Güneş Düz Kesim 101" },
    { image: "", name: "Saffron 101" },
    { image: "", name: "Saffron Düz Kesim 101" },
    { image: "", name: "Bursa Bej 101" },
    { image: "", name: "Epica Light 101" },
    { image: "", name: "Epica Dark 101" },
    { image: "", name: "Insula Alba 101" },
    { image: "", name: "Verde Guatemala 102" },
    { image: "", name: "Verde Escuro 101" },
    { image: "", name: "Black Olive 101" },
    { image: "", name: "Füme 101" },
    { image: "", name: "Colorata 101" },
    { image: "", name: "Light Emperador 101" },
    { image: "", name: "Duru 101" },
  ],
  [
    { image: "", name: "Pinguino 101" },
    { image: "", name: "Black Orion 101" },
    { image: "", name: "Black Aziza 101" },
    { image: "", name: "Portoro 101" },
    { image: "", name: "İspanyol Dark Emperador 101" },
    { image: "", name: "Silver Dragon 101" },
    { image: "", name: "Saint Laurent 101" },
    { image: "", name: "Zebra Black 101" },
    { image: "", name: "Mont Blanc 101" },
    { image: "", name: "Metell 101" },
    { image: "", name: "Metell Klasik 101" },
    { image: "", name: "Ocean 101" },
    { image: "", name: "Lilla 101" },
    { image: "", name: "New York 101" },
    { image: "", name: "Volakas 101" },
    { image: "", name: "Calacatta 105" },
    { image: "", name: "Carrara 101" },
    { image: "", name: "Carrara Brezza 101" },
    { image: "", name: "Madreperla 101" },
    { image: "", name: "Polar White 101" },
    { image: "", name: "Muğla Grili 101" },
    { image: "", name: "Olea 101" },
    { image: "", name: "Panda White 101" },
    { image: "", name: "Panda White 103" },
  ],
  [
    { image: "", name: "Ice Jade 101" },
    { image: "", name: "Ice Jade 103" },
    { image: "", name: "Ice Jade 104" },
    { image: "", name: "Ice Jade 105" },
    { image: "", name: "Desert Wave 101" },
    { image: "", name: "S Black – Cilalı 101" },
    { image: "", name: "S Black – Cilalı 102" },
    { image: "", name: "S Black – Honlu 101" },
    { image: "", name: "S Black – Honlu 102" },
    { image: "", name: "S Black – Kumlama 101" },
    { image: "", name: "S Black – Kumlama 102" },
    { image: "", name: "S Black – Kumlama Fırçalı 101" },
    { image: "", name: "S Black – Kumlama Fırçalı 102" },
    { image: "", name: "Amazon 101" },
    { image: "", name: "Rosa Beta 101" },
    { image: "", name: "Rosa Minho 101" },
    { image: "", name: "Glacier 101" },
    { image: "", name: "Glacier White 101" },
    { image: "", name: "Satin Oniks 101" },
    { image: "", name: "Imperial Red 101" },
    { image: "", name: "Magnifica 101" },
    { image: "", name: "Magnifica Düz Kesim 101" },
    { image: "", name: "Cappadoce Düz Kesim 101" },
    { image: "", name: "Marmelade 101" },
  ],
  [
    { image: "", name: "Violet 101" },
    { image: "", name: "Medium Emperador 101" },
    { image: "", name: "Zambak 101" },
    { image: "", name: "Nigella 101" },
    { image: "", name: "Nigella Rose 101" },
    { image: "", name: "Pietra Grey 101" },
    { image: "", name: "Rain Forest Brown 101" },
    { image: "", name: "Rosa Porinho 101" },
    { image: "", name: "Aksaray Yaylak 101" },
    { image: "", name: "Salmon Oniks 101" },
    { image: "", name: "Bellissima 101" },
    { image: "", name: "Suni Taş – Bianco Bandia – Honlu 101" },
    { image: "", name: "Suni Taş – Bianco Bandia – Eskitme 101" },
    { image: "", name: "Suni Taş – Bianco Bandia – Kumlama 101" },
    { image: "", name: "Tigrato 101" },
    { image: "", name: "Crystal White 101" },
    { image: "", name: "Armonia 101" },
    { image: "", name: "Wooden Light 101" },
    { image: "", name: "Beyaz Oniks 101" },
    { image: "", name: "Dark Desert Rose 101" },
    { image: "", name: "Light Desert Rose 101" },
  ],
];

export const plakalar = [
  [
    { image: "", name: "Blue Ice Onyx 1001" },
    { image: "", name: "Green Ice Onyx 1001" },
    { image: "", name: "Pink Ice Onyx 1001" },
    { image: "", name: "Amazonite 10001" },
    { image: "", name: "Patagonia 10001" },
    { image: "", name: "Azul Macoubas 10001" },
    { image: "", name: "Desert Wave 1002" },
    { image: "", name: "Panda Emerald Marble 1001" },
    { image: "", name: "Rain Forest Brown 1003" },
    { image: "", name: "Rain Forest Green 1001" },
    { image: "", name: "Panda Azul 1001" },
    { image: "", name: "Panda Azul 1002" },
    { image: "", name: "Agate Blue 1001" },
    { image: "", name: "Agate Green 1001" },
    { image: "", name: "Agate Purple 1001" },
    { image: "", name: "Grey Agate 1001" },
    { image: "", name: "Petrified Wood 1001" },
    { image: "", name: "Agate White 1001" },
    { image: "", name: "Rosa Quartz 1001" },
    { image: "", name: "Yellow Tiger Agate 1001" },
    { image: "", name: "Round Agathe 1001" },
    { image: "", name: "Dark Emperador 1002" },
    { image: "", name: "Ice Jade 1010" },
    { image: "", name: "Lilla 1005" },
  ],
  [
    { image: "", name: "Magma Gold 1002" },
    { image: "", name: "Petrified Wood Marble 1001" },
    { image: "", name: "Black Aziza 1003" },
    { image: "", name: "Green Oniks 1001" },
    { image: "", name: "Nero Marquina 10001" },
    { image: "", name: "Panda White 10001" },
    { image: "", name: "Roma Black 101" },
    { image: "", name: "Picasso 1002" },
    { image: "", name: "Serpegiante Light 1002" },
    { image: "", name: "Zebra Black 1003" },
    { image: "", name: "Turtle 1002" },
    { image: "", name: "Aqua Limo 101" },
    { image: "", name: "Arabescato Gold 101" },
    { image: "", name: "Salmon Oniks 1001" },
    { image: "", name: "Black Marquina 101" },
    { image: "", name: "Carrara 101" },
    { image: "", name: "Diamond Gold 101" },
    { image: "", name: "Pietra Grey 101" },
    { image: "", name: "Salmon Oniks 1002" },
    { image: "", name: "Tiger Oniks 1001" },
    { image: "", name: "Tiger Oniks 1002" },
    { image: "", name: "Wooden Oniks 1001" },
    { image: "", name: "Travertino Grey 101" },
    { image: "", name: "Volga Blue 101" },
  ],
  [
    { image: "", name: "Wooden Oniks 1002" },
    { image: "", name: "Beyaz Oniks 1001" },
    { image: "", name: "Vivid White" },
    { image: "", name: "Snow" },
    { image: "", name: "White Shimmer" },
    { image: "", name: "Frosty Carrina" },
    { image: "", name: "Pure White" },
    { image: "", name: "Nougat" },
    { image: "", name: "Organic White" },
    { image: "", name: "Ocean Foam" },
    { image: "", name: "Intense White" },
    { image: "", name: "London Grey" },
    { image: "", name: "Empira White" },
    { image: "", name: "White Attica" },
    { image: "", name: "Ice Snow" },
    { image: "", name: "Statuario Maximus" },
    { image: "", name: "Cosmopolitan White" },
    { image: "", name: "Calacatta Maximus" },
    { image: "", name: "Cloudburst Concrete" },
    { image: "", name: "Statuario Nuvo" },
    { image: "", name: "Montblanc" },
    { image: "", name: "Frozen Terra" },
    { image: "", name: "Georgian Bluffs" },
    { image: "", name: "Misty Carrera" },
  ],
  [
    { image: "", name: "Nordic Loft" },
    { image: "", name: "Alpine Mist" },
    { image: "", name: "Dreamy Marfil" },
    { image: "", name: "Clamshell" },
    { image: "", name: "Calacatta Nuvo" },
    { image: "", name: "Bianco Drift" },
    { image: "", name: "Taj Royale" },
    { image: "", name: "Buttermilk" },
    { image: "", name: "Haze" },
    { image: "", name: "Linen" },
    { image: "", name: "Raw Concrete" },
    { image: "", name: "Urban" },
    { image: "", name: "Topus Concrete" },
    { image: "", name: "Primordia" },
    { image: "", name: "Symphony Grey" },
    { image: "", name: "Airy Concrete" },
    { image: "", name: "Noble Grey" },
    { image: "", name: "Sleek Concrete" },
    { image: "", name: "Shitake" },
    { image: "", name: "Turbine Grey" },
    { image: "", name: "Oyster" },
    { image: "", name: "Atlantic Salt" },
    { image: "", name: "Titan" },
    { image: "", name: "Woodlands" },
  ],
  [
    { image: "", name: "Oxidian" },
    { image: "", name: "Fresh Concrete" },
    { image: "", name: "Bianco Carrara 1" },
    { image: "", name: "Concrete" },
    { image: "", name: "Raven" },
    { image: "", name: "Ginger" },
    { image: "", name: "Lagos Blue" },
    { image: "", name: "Excava" },
    { image: "", name: "Rugged Concrete" },
    { image: "", name: "Piatra Grey" },
    { image: "", name: "Black Tempal" },
    { image: "", name: "Vanilla Noir" },
    { image: "", name: "Piatto Black" },
    { image: "", name: "Black Noir" },
    { image: "", name: "Calcatta Caldia 1" },
    { image: "", name: "Jet Black" },
    { image: "", name: "Pearl White 1" },
    { image: "", name: "Sahara Noir 1" },
    { image: "", name: "Serpegiante Light 10001" },
    { image: "", name: "Azul Macaubas 1001" },
    { image: "", name: "Azul Macaubas 1002" },
    { image: "", name: "Black Leopar 1001" },
    { image: "", name: "Panda White 1008" },
    { image: "", name: "Serpegiante Light 1001" },
  ],
  [
    { image: "", name: "Alps Blue 10001" },
    { image: "", name: "Azul Macobus 10001" },
    { image: "", name: "Van Gogh Blue 10001" },
    { image: "", name: "Afyon White Spider 1001" },
    { image: "", name: "Daisy" },
    { image: "", name: "Aymina" },
    { image: "", name: "Alaska" },
    { image: "", name: "Bolera" },
    { image: "", name: "Cordelia" },
    { image: "", name: "Lusetia White" },
    { image: "", name: "Sierra White" },
    { image: "", name: "Mia" },
    { image: "", name: "Aria" },
    { image: "", name: "Rossa White" },
    { image: "", name: "Visendra" },
    { image: "", name: "Tornado" },
    { image: "", name: "Admira" },
    { image: "", name: "Lusida Grey" },
    { image: "", name: "Olivia" },
    { image: "", name: "Sima" },
    { image: "", name: "Elatris" },
    { image: "", name: "Caramela" },
    { image: "", name: "Lusida Black" },
    { image: "", name: "Rugiada" },
  ],
  [
    { image: "", name: "Santa" },
    { image: "", name: "Nidia" },
    { image: "", name: "Sadira" },
    { image: "", name: "Mirat" },
    { image: "", name: "Hiearapolis" },
    { image: "", name: "Arcadia" },
    { image: "", name: "Artemis" },
    { image: "", name: "Barents" },
    { image: "", name: "Beach 1001" },
    { image: "", name: "Lapland" },
    { image: "", name: "Lilla 1002" },
    { image: "", name: "Lilla 1003" },
    { image: "", name: "Nebula" },
    { image: "", name: "Nephila" },
    { image: "", name: "Olympos" },
    { image: "", name: "Sineda" },
    { image: "", name: "Alpino" },
    { image: "", name: "Tundra" },
    { image: "", name: "Mora" },
    { image: "", name: "Fuga" },
    { image: "", name: "Versilia" },
    { image: "", name: "Lebedos" },
    { image: "", name: "Keops" },
    { image: "", name: "Linen" },
  ],
  [
    { image: "", name: "Terra" },
    { image: "", name: "Smyrna" },
    { image: "", name: "Lapaz" },
    { image: "", name: "Troas" },
    { image: "", name: "Etna" },
    { image: "", name: "Ares" },
    { image: "", name: "Boreas" },
    { image: "", name: "Elvas" },
    { image: "", name: "Kromit" },
    { image: "", name: "Savana" },
    { image: "", name: "Gharma" },
    { image: "", name: "Toros" },
    { image: "", name: "Carbone" },
    { image: "", name: "Hermes" },
    { image: "", name: "Armani Grey 10001" },
    { image: "", name: "Calacatta Victory" },
    { image: "", name: "Carrara 10001" },
    { image: "", name: "Carrara Ultimo 10001" },
    { image: "", name: "Invisible White 10001" },
    { image: "", name: "Felisia" },
    { image: "", name: "Macchia 10001" },
    { image: "", name: "Marquina Venato 10001" },
    { image: "", name: "Modern Statuario 10001" },
    { image: "", name: "Pantheon" },
  ],
  [
    { image: "", name: "Pietra Grey 10001" },
    { image: "", name: "Rome 10001" },
    { image: "", name: "Sahara Noir 10001" },
    { image: "", name: "Statuario Elite 10001" },
    { image: "", name: "Polaris" },
    { image: "", name: "Anemon" },
    { image: "", name: "Alinda" },
    { image: "", name: "Kristella White" },
    { image: "", name: "Sahara Beige" },
    { image: "", name: "Montana" },
    { image: "", name: "Aizano" },
    { image: "", name: "Retro" },
    { image: "", name: "Metropol Grey" },
    { image: "", name: "Gala Black" },
    { image: "", name: "Aspendos" },
    { image: "", name: "Aurora" },
    { image: "", name: "Belluno" },
    { image: "", name: "Calacatta Veneto" },
    { image: "", name: "Calacatta Verona" },
    { image: "", name: "Carola" },
    { image: "", name: "Teos" },
    { image: "", name: "Daphne Crack" },
    { image: "", name: "Elixir White" },
    { image: "", name: "Fairy White" },
  ],
  [
    { image: "", name: "Perla" },
    { image: "", name: "Iceberg" },
    { image: "", name: "Juliet White" },
    { image: "", name: "Kashmera White" },
    { image: "", name: "La Luna" },
    { image: "", name: "Pixie Wings" },
    { image: "", name: "Olympos" },
    { image: "", name: "Mocca Mousse" },
    { image: "", name: "Parma" },
    { image: "", name: "Chakra" },
    { image: "", name: "Boletus" },
    { image: "", name: "Terre Grey" },
    { image: "", name: "Babilon" },
    { image: "", name: "Charmy" },
    { image: "", name: "Forza Füme" },
    { image: "", name: "Marquina Tierra" },
    { image: "", name: "Spa Black" },
    { image: "", name: "Volcano Black" },
    { image: "", name: "Bardiglio Black 1001" },
    { image: "", name: "Botticino 1001" },
    { image: "", name: "Pinguino 1011" },
    { image: "", name: "Panda White 1006" },
    { image: "", name: "Panda White 1007" },
    { image: "", name: "Emerald 1001" },
  ],
  [
    { image: "", name: "Emerald 1002" },
    { image: "", name: "Emerald 1003" },
    { image: "", name: "Emerald 1004" },
    { image: "", name: "Picasso 1001" },
    { image: "", name: "Panda White 1005" },
    { image: "", name: "Serpegiante 1001" },
    { image: "", name: "Beyaz Oniks 1002" },
    { image: "", name: "Beyaz Oniks 1003" },
    { image: "", name: "Afyon Beyaz Mermer Oniks 1001" },
    { image: "", name: "Marmara Beyaz Mermer 1001" },
    { image: "", name: "Zebra White 1001" },
    { image: "", name: "Blue Rain 1001" },
    { image: "", name: "Hills 1001" },
    { image: "", name: "Bruno 1001" },
    { image: "", name: "Fusion 1001" },
    { image: "", name: "Emerald 1004" },
    { image: "", name: "Rain Forest Brown 1002" },
    { image: "", name: "Statuario 1001" },
    { image: "", name: "Nero 1001" },
    { image: "", name: "Zebra Black 1002" },
    { image: "", name: "Turtle 1001" },
    { image: "", name: "Pedras Granit – Cilalı 101" },
    { image: "", name: "Pedras Granit – Kumlama 102" },
    { image: "", name: "Calacatta Oro 1001" },
  ],
  [
    { image: "", name: "Zebra Grey 1001" },
    { image: "", name: "Bal Oniks 1001" },
    { image: "", name: "Bal Oniks 1002" },
    { image: "", name: "Bal Oniks 1003" },
    { image: "", name: "Bal Oniks 1004" },
    { image: "", name: "Botticino 1002" },
    { image: "", name: "Coquillage 1001" },
    { image: "", name: "Bianco Crema 1001" },
    { image: "", name: "Carrara Arabescato 1001" },
    { image: "", name: "Bubble Oniks 1001" },
    { image: "", name: "Cappuccino Oniks 1001" },
    { image: "", name: "Velluto Oniks 1001" },
    { image: "", name: "Afyon Beyaz Arcobaleno 1001" },
    { image: "", name: "Bardiglio Blu 1001" },
    { image: "", name: "Sperenza 1001" },
    { image: "", name: "Gümüş Oniks 1001" },
    { image: "", name: "Gümüş Traverten 1001" },
    { image: "", name: "Gümüş Traverten Düz Kesim 1001" },
    { image: "", name: "Verde Guatemala 1001" },
    { image: "", name: "Verde Forest 1001" },
    { image: "", name: "Elazığ Vişne 1001" },
    { image: "", name: "Volakas Bianco 1001" },
    { image: "", name: "Rosalia 1001" },
    { image: "", name: "Rosalia Light 1001" },
  ],
  [
    { image: "", name: "Light Emperador Klasik 1001" },
    { image: "", name: "Pedras Granit – Kumlama 103" },
    { image: "", name: "White Walker 101" },
    { image: "", name: "White Walker – Küp Taşlar 101" },
    { image: "", name: "White Walker – Küp Taşlar 102" },
    { image: "", name: "White Walker – Küp Taşlar 103" },
    { image: "", name: "Desert Black 101" },
    { image: "", name: "Absolute Black 101" },
    { image: "", name: "Star Galaxy 101" },
    { image: "", name: "Paradiso 101" },
    { image: "", name: "P White 101" },
    { image: "", name: "Nero Marquina 1001" },
    { image: "", name: "Nebel 1001" },
    { image: "", name: "Blue Moon 1002" },
    { image: "", name: "Afyon Beyaz Arcobaleno 1002" },
    { image: "", name: "Afyon Beyaz Arcobaleno 1003" },
    { image: "", name: "Afyon Beyaz Arcobaleno 1004" },
    { image: "", name: "Afyon Beyaz Arcobaleno 1005" },
    { image: "", name: "Afyon Beyaz Arcobaleno 1006" },
    { image: "", name: "Afyon Beyaz Arcobaleno 1007" },
    { image: "", name: "Afyon Beyaz Golden Gray 1001" },
    { image: "", name: "Afyon Beyaz Golden Gray 1002" },
    { image: "", name: "Afyon Beyaz Golden Gray 1003" },
    { image: "", name: "Afyon Beyaz Golden Gray 1004" },
  ],
  [
    { image: "", name: "Afyon Beyaz Golden Gray 1005" },
    { image: "", name: "Afyon Beyaz Golden Gray 1006" },
    { image: "", name: "Afyon Beyaz A La Vogue 1001" },
    { image: "", name: "Afyon Beyaz A La Vogue 1002" },
    { image: "", name: "Afyon Beyaz A La Vogue 1003" },
    { image: "", name: "Afyon Beyaz A La Vogue 1004" },
    { image: "", name: "Afyon Beyaz Billur 1001" },
    { image: "", name: "Afyon Beyaz Billur 1002" },
    { image: "", name: "Afyon Beyaz Billur 1003" },
    { image: "", name: "Afyon Beyaz Billur 1004" },
    { image: "", name: "Afyon Beyaz Billur 1005" },
    { image: "", name: "Afyon Beyaz Billur 1006" },
    { image: "", name: "Afyon Beyaz Billur 1007" },
    { image: "", name: "Afyon Beyaz Billur 1008" },
    { image: "", name: "Afyon Beyaz Billur 1009" },
    { image: "", name: "Afyon Şeker 1001" },
    { image: "", name: "Afyon Şeker 1002" },
    { image: "", name: "Afyon Şeker 1003" },
    { image: "", name: "Afyon Şeker 1004" },
    { image: "", name: "Afyon Şeker 1005" },
    { image: "", name: "Afyon Şeker 1006" },
    { image: "", name: "Calacatta 1001" },
    { image: "", name: "Calacatta 1002" },
    { image: "", name: "Calacatta 1003" },
  ],
  [
    { image: "", name: "Calacatta 1004" },
    { image: "", name: "Calacatta 1005" },
    { image: "", name: "Calacatta 1006" },
    { image: "", name: "Calacatta 1007" },
    { image: "", name: "Calacatta 1008" },
    { image: "", name: "Calacatta 1009" },
    { image: "", name: "Calacatta 1010" },
    { image: "", name: "Calacatta 1011" },
    { image: "", name: "Calacatta 1012" },
    { image: "", name: "Calacatta 1013" },
    { image: "", name: "Calacatta 1014" },
    { image: "", name: "Calacatta 1015" },
    { image: "", name: "Calacatta 1016" },
    { image: "", name: "Nuage Miel 1001" },
    { image: "", name: "Nuage Miel 1002" },
    { image: "", name: "Nuage Miel 1003" },
    { image: "", name: "Nuage Miel 1004" },
    { image: "", name: "Nuage Miel 1005" },
    { image: "", name: "Nuage Miel 1006" },
    { image: "", name: "Nuage Miel 1007" },
    { image: "", name: "Nuage Miel 1008" },
    { image: "", name: "Nuage Miel 1009" },
    { image: "", name: "Nuage Doré 1001" },
    { image: "", name: "Ice Jade 10001" },
  ],
  [
    { image: "", name: "Ice Jade 10002" },
    { image: "", name: "Ice Jade 10003" },
    { image: "", name: "Silk White 10001" },
    { image: "", name: "Glacier White 10001" },
    { image: "", name: "Pure White 10001" },
    { image: "", name: "Ivory Travertine Porcelain 10001" },
    { image: "", name: "Calacatta 10001" },
    { image: "", name: "Crema Bella 1001" },
    { image: "", name: "Botanica 1001" },
    { image: "", name: "Luna Piera 1001" },
    { image: "", name: "Limpido 1001" },
    { image: "", name: "Dark Emperador 1001" },
    { image: "", name: "Dark Emperador Klasik 1001" },
    { image: "", name: "Dune 1001" },
    { image: "", name: "Luna 1001" },
    { image: "", name: "Light Emperador 1001" },
    { image: "", name: "Emperador Perla 1001" },
    { image: "", name: "Emperador Perla Klasik 1001" },
    { image: "", name: "Mondo-1001" },
    { image: "", name: "Brume 1001" },
    { image: "", name: "Avorio 1001" },
    { image: "", name: "Bardiglio Blu 1002" },
    { image: "", name: "Crema Foret 1001" },
    { image: "", name: "Bardiglio Blu 1003" },
  ],
  [
    { image: "", name: "Colorata 1001" },
    { image: "", name: "Duru 1001" },
    { image: "", name: "Bardiglio Blu 1004" },
    { image: "", name: "Bardiglio Blu 1005" },
    { image: "", name: "Burdur Bej 1001" },
    { image: "", name: "Bardiglio Blu 1006" },
    { image: "", name: "Bardiglio Blu 1007" },
    { image: "", name: "Bardiglio Blu 1008" },
    { image: "", name: "Bardiglio Blu 1009" },
    { image: "", name: "Bardiglio Blu 1010" },
    { image: "", name: "Blue Bahia 1001" },
    { image: "", name: "Blue Bahia 1002" },
    { image: "", name: "Blue Moon 1001" },
    { image: "", name: "Blue Moon 1003" },
    { image: "", name: "Blue Moon 1004" },
    { image: "", name: "Blue Moon 1005" },
    { image: "", name: "Blue Moon 1006" },
    { image: "", name: "Blue Moon 1007" },
    { image: "", name: "Blue Stone 1001" },
    { image: "", name: "Blue Stone 1002" },
    { image: "", name: "Blue Stone 1003" },
    { image: "", name: "Blue Moon Gold 1001" },
    { image: "", name: "Afyon Beyaz Marine Blue 1001" },
    { image: "", name: "Afyon Beyaz Marine Blue 1002" },
  ],
  [
    { image: "", name: "Afyon Beyaz Marine Blue 1003" },
    { image: "", name: "Afyon Beyaz Marine Blue 1004" },
    { image: "", name: "Gümüş Oniks 1002" },
    { image: "", name: "Gold Oniks 1001" },
    { image: "", name: "Gold Oniks 1002" },
    { image: "", name: "Cocacola Oniks 1001" },
    { image: "", name: "Cocacola Oniks 1002" },
    { image: "", name: "Satin Oniks 1001" },
    { image: "", name: "Afyon Beyaz Marine Blue 1005" },
    { image: "", name: "Afyon Beyaz Marine Blue 1006" },
    { image: "", name: "Afyon Beyaz Marine Blue 1007" },
    { image: "", name: "River 1001" },
    { image: "", name: "Beyaz Traverten 1001" },
    { image: "", name: "Epica 1001" },
    { image: "", name: "Elazığ Vişne 1002" },
    { image: "", name: "Elazığ Vişne 1003" },
    { image: "", name: "Elazığ Vişne 1004" },
    { image: "", name: "Elazığ Vişne 1005" },
    { image: "", name: "Elazığ Vişne 1006" },
    { image: "", name: "Elazığ Vişne 1007" },
    { image: "", name: "Elazığ Vişne 1008" },
    { image: "", name: "Elazığ Vişne 1009" },
    { image: "", name: "Elazığ Vişne 1010" },
    { image: "", name: "Elazığ Vişne 1011" },
  ],
  [
    { image: "", name: "Elazığ Vişne 1012" },
    { image: "", name: "Pinguino 1010" },
    { image: "", name: "Verde Escuro 1001" },
    { image: "", name: "Klasik Traverten 1001" },
    { image: "", name: "Beyaz Traverten Düz Kesim 1001" },
    { image: "", name: "Klasik Traverten Düz Kesim 1001" },
    { image: "", name: "Golden Crema 1001" },
    { image: "", name: "Black Olive 1001" },
    { image: "", name: "Black Olive 1002" },
    { image: "", name: "Black Olive 1003" },
    { image: "", name: "Black Olive 1004" },
    { image: "", name: "Black Olive 1005" },
    { image: "", name: "Black Olive 1006" },
    { image: "", name: "Black Olive 1007" },
    { image: "", name: "Black Olive 1008" },
    { image: "", name: "Black Olive 1009" },
    { image: "", name: "Black Olive 1010" },
    { image: "", name: "Black Olive 1011" },
    { image: "", name: "Füme 1001" },
    { image: "", name: "Füme 1002" },
    { image: "", name: "Füme 1003" },
    { image: "", name: "Füme 1004" },
    { image: "", name: "Füme 1005" },
    { image: "", name: "Füme 1006" },
  ],
  [
    { image: "", name: "Iris 1001" },
    { image: "", name: "Iris 1002" },
    { image: "", name: "Iris 1003" },
    { image: "", name: "Iris 1004" },
    { image: "", name: "Iris 1005" },
    { image: "", name: "Iris 1006" },
    { image: "", name: "Iris 1007" },
    { image: "", name: "Iris 1008" },
    { image: "", name: "Nebel 1002" },
    { image: "", name: "Nebel 1003" },
    { image: "", name: "Nebel 1004" },
    { image: "", name: "Nebel 1005" },
    { image: "", name: "Nebel 1006" },
    { image: "", name: "Nebel 1007" },
    { image: "", name: "Nebel 1008" },
    { image: "", name: "Pinguino 1001" },
    { image: "", name: "Pinguino 1002" },
    { image: "", name: "Pinguino 1003" },
    { image: "", name: "Pinguino 1004" },
    { image: "", name: "Pinguino 1005" },
    { image: "", name: "Pinguino 1006" },
    { image: "", name: "Pinguino 1007" },
    { image: "", name: "Pinguino 1008" },
    { image: "", name: "Pinguino 1009" },
  ],
  [
    { image: "", name: "Black Orion 1001" },
    { image: "", name: "Black Aziza 1001" },
    { image: "", name: "Black Aziza 1002" },
    { image: "", name: "Black Pearl 1001" },
    { image: "", name: "Portoro 1001" },
    { image: "", name: "İspanyol Dark Emperador 1001" },
    { image: "", name: "Silver Dragon 1001" },
    { image: "", name: "Saint Laurent 1001" },
    { image: "", name: "Zebra Black 1001" },
    { image: "", name: "Zebra Black 1004" },
    { image: "", name: "Ice Jade 1001" },
    { image: "", name: "Ice Jade 1002" },
    { image: "", name: "Ice Jade 1003" },
    { image: "", name: "Ice Jade 1004" },
    { image: "", name: "Ice Jade 1005" },
    { image: "", name: "Ice Jade 1006" },
    { image: "", name: "Ice Jade 1007" },
    { image: "", name: "Ice Jade 1008" },
    { image: "", name: "Ice Jade 1009" },
    { image: "", name: "Mont Blanc 1001" },
    { image: "", name: "Mont Blanc 1002" },
    { image: "", name: "Mont Blanc 1003" },
    { image: "", name: "Mont Blanc 1004" },
    { image: "", name: "Metell 1001" },
  ],
  [
    { image: "", name: "Metell Klasik 1001" },
    { image: "", name: "Ocean 1001" },
    { image: "", name: "Ocean 1002" },
    { image: "", name: "Lilla 1001" },
    { image: "", name: "Lilla 1004" },
    { image: "", name: "New York 1001" },
    { image: "", name: "Volakas 1001" },
    { image: "", name: "Volakas Bianco 1002" },
    { image: "", name: "Volakas Bianco 1003" },
    { image: "", name: "Volakas Bianco 1004" },
    { image: "", name: "Volakas Bianco 1005" },
    { image: "", name: "Volakas Bianco 1006" },
    { image: "", name: "Volakas Bianco 1007" },
    { image: "", name: "Volakas Bianco 1008" },
    { image: "", name: "Carrara 1001" },
    { image: "", name: "Carrara Brezza 1001" },
    { image: "", name: "Carrara Brezza 1002" },
    { image: "", name: "Carrara Brezza 1003" },
    { image: "", name: "Carrara Brezza 1004" },
    { image: "", name: "Madreperla 1001" },
    { image: "", name: "Madreperla Klasik 1001" },
    { image: "", name: "Polar White 1001" },
    { image: "", name: "Polar White 1002" },
    { image: "", name: "Polar White 1003" },
  ],
  [
    { image: "", name: "Polar White 1004" },
    { image: "", name: "Polar White 1005" },
    { image: "", name: "Polar White 1006" },
    { image: "", name: "Polar White 1007" },
    { image: "", name: "Polar White 1008" },
    { image: "", name: "Muğla Grili 1001" },
    { image: "", name: "Olea 1001" },
    { image: "", name: "Panda White 1001" },
    { image: "", name: "Panda White 1002" },
    { image: "", name: "Panda White 1003" },
    { image: "", name: "Panda White 1004" },
    { image: "", name: "Blackberry 1001" },
    { image: "", name: "Blackberry Düz Kesim 1001" },
    { image: "", name: "Desert Wave 1001" },
    { image: "", name: "Marmelade 1001" },
    { image: "", name: "Violet 1001" },
    { image: "", name: "Zambak 1001" },
    { image: "", name: "Zambak 1002" },
    { image: "", name: "Zambak 1003" },
    { image: "", name: "Rain Forest Brown 1001" },
    { image: "", name: "Bellissima 1001" },
    { image: "", name: "Bellissima 1002" },
    { image: "", name: "Bellissima 1003" },
    { image: "", name: "Tigrato 1001" },
  ],
  [
    { image: "", name: "Calimero 1001" },
    { image: "", name: "Cappadoce Düz Kesim 1001" },
    { image: "", name: "Cashmere 1001" },
    { image: "", name: "Kırmızı Traverten 1001" },
    { image: "", name: "Kırmızı Traverten Düz Kesim 1001" },
    { image: "", name: "Saffron Düz Kesim 1001" },
    { image: "", name: "Crystal White 1001" },
    { image: "", name: "Wooden Light 1001" },
    { image: "", name: "Beyaz Mermer 101" },
    { image: "", name: "Dark Desert Rose 1001" },
    { image: "", name: "S Black – Cilalı 101" },
    { image: "", name: "S Black – Cilalı 102" },
    { image: "", name: "S Black – Honlu 101" },
    { image: "", name: "S Black – Honlu 102" },
    { image: "", name: "S Black – Kumlama 101" },
    { image: "", name: "S Black – Kumlama 102" },
    { image: "", name: "S Black – Kumlama Fırçalı 101" },
    { image: "", name: "S Black – Kumlama Fırçalı 102" },
    { image: "", name: "Amazon 101" },
    { image: "", name: "Rosa Beta 101" },
    { image: "", name: "Rosa Minho 101" },
    { image: "", name: "Gargamel 1001" },
    { image: "", name: "Güneş Düz Kesim 1001" },
    { image: "", name: "Warm Walnut 1001" },
  ],
  [
    { image: "", name: "Warm Walnut Düz Kesim 1001" },
    { image: "", name: "Noce Düz Kesim 1001" },
    { image: "", name: "Imperial Red 101" },
    { image: "", name: "Light Desert Rose 1001" },
    { image: "", name: "Light Desert Rose 1002" },
    { image: "", name: "Magnifica Düz Kesim 1001" },
    { image: "", name: "Blue Moon Mavi Mermer" },
    { image: "", name: "Nigella 1001" },
    { image: "", name: "Pietra Gray 1001" },
    { image: "", name: "Rosa Porinho 101" },
    { image: "", name: "Aksaray Yaylak 101" },
    { image: "", name: "Siyah Mermer Plakalar" },
    { image: "", name: "Sunny 1001" },
    { image: "", name: "Sunny Light 1001" },
    { image: "", name: "Suni Taş – Bianco Bandia 1001" },
    { image: "", name: "Yeşil Mermer Plakalar" },
  ],
];
